### ISSUE TITLE
Unable to connect to the mlab database.

### ISSUE THREAD

**Issue by jinmingda** [nesdis/djongo#109]
#### Python script

<The complete python script used to produce the issue.>

```python
DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'NAME': 'dbname',
        'USER': 'dbusername',
        'PASSWORD': 'dbpassword',
        'HOST': 'xxxxx.mlab.com',
        'PORT': 41056,
    }
}

```

#### Traceback
```bash
vagrant@ubuntu-xenial:/vagrant$ python3.6 manage.py makemigrations tools
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vagrant/.local/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/vagrant/.local/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/home/vagrant/.local/lib/python3.6/site-packages/django/core/management/commands/makemigrations.py", line 92, in handle
    loader.check_consistent_history(connection)
  File "/home/vagrant/.local/lib/python3.6/site-packages/django/db/migrations/loader.py", line 275, in check_consistent_history
    applied = recorder.applied_migrations()
  File "/home/vagrant/.local/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 61, in applied_migrations
    if self.has_table():
  File "/home/vagrant/.local/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 44, in has_table
    return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
  File "/home/vagrant/.local/lib/python3.6/site-packages/django/db/backends/base/introspection.py", line 56, in table_names
    return get_names(cursor)
  File "/home/vagrant/.local/lib/python3.6/site-packages/django/db/backends/base/introspection.py", line 51, in get_names
    return sorted(ti.name for ti in self.get_table_list(cursor)
  File "/home/vagrant/.local/lib/python3.6/site-packages/djongo/introspection.py", line 9, in get_table_list
    return [TableInfo(c,'t') for c in cursor.db_conn.collection_names(False)]
  File "/home/vagrant/.local/lib/python3.6/site-packages/pymongo/database.py", line 617, in collection_names
    for result in self.list_collections(session=session, **kws)]
  File "/home/vagrant/.local/lib/python3.6/site-packages/pymongo/database.py", line 586, in list_collections
    ReadPreference.PRIMARY) as (sock_info, slave_okay):
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/vagrant/.local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 983, in _socket_for_reads
    with self._get_socket(server) as sock_info:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/vagrant/.local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 947, in _get_socket
    with server.get_socket(self.__all_credentials) as sock_info:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/vagrant/.local/lib/python3.6/site-packages/pymongo/server.py", line 138, in get_socket
    with self.pool.get_socket(all_credentials, checkout) as sock_info:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/vagrant/.local/lib/python3.6/site-packages/pymongo/pool.py", line 920, in get_socket
    sock_info.check_auth(all_credentials)
  File "/home/vagrant/.local/lib/python3.6/site-packages/pymongo/pool.py", line 609, in check_auth
    auth.authenticate(credentials, self)
  File "/home/vagrant/.local/lib/python3.6/site-packages/pymongo/auth.py", line 486, in authenticate
    auth_func(credentials, sock_info)
  File "/home/vagrant/.local/lib/python3.6/site-packages/pymongo/auth.py", line 466, in _authenticate_default
    return _authenticate_scram_sha1(credentials, sock_info)
  File "/home/vagrant/.local/lib/python3.6/site-packages/pymongo/auth.py", line 209, in _authenticate_scram_sha1
    res = sock_info.command(source, cmd)
  File "/home/vagrant/.local/lib/python3.6/site-packages/pymongo/pool.py", line 517, in command
    collation=collation)
  File "/home/vagrant/.local/lib/python3.6/site-packages/pymongo/network.py", line 125, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/home/vagrant/.local/lib/python3.6/site-packages/pymongo/helpers.py", line 145, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: Authentication failed.
```

**Comment by nesdis** [comment]
You need to add auth source to your settings.
