### ISSUE TITLE
Model.objects.all().delete() occurs exceptions

### ISSUE THREAD

**Issue by ruralscenery** [nesdis/djongo#127]
#### Run Model.objects.all().delete() failure

Django:  ver 2.0.5

#### Python script

<The complete python script used to produce the issue.>

```python
class NameDate(models.Model):
    name = models.CharField(max_length=10)
    when = models.DateTimeField()

NameDate.objects.create(name='name', when='2000-01-01')
NameDate.objects.all().delete()
```

#### Traceback
<The complete stack trace of the error.>
Query DELETE FROM "mongo_namedate"
Traceback (most recent call last):
  File "/Users/blue/.local/share/virtualenvs/djongo-gAwkvrvm/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 726, in parse
    return handler(self, statement)
  File "/Users/blue/.local/share/virtualenvs/djongo-gAwkvrvm/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 841, in _delete
    self._query = DeleteQuery(self.db, self.connection_properties, sm, self._params)
  File "/Users/blue/.local/share/virtualenvs/djongo-gAwkvrvm/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 618, in __init__
    super().__init__(*args)
  File "/Users/blue/.local/share/virtualenvs/djongo-gAwkvrvm/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 72, in __init__
    self.parse()
  File "/Users/blue/.local/share/virtualenvs/djongo-gAwkvrvm/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 636, in parse
    self.result = db_con[collection].delete_many(**kw)
TypeError: delete_many() missing 1 required positional argument: 'filter'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/blue/.local/share/virtualenvs/djongo-gAwkvrvm/lib/python3.6/site-packages/django/db/models/query.py", line 662, in delete
    deleted, _rows_count = collector.delete()
  File "/Users/blue/.local/share/virtualenvs/djongo-gAwkvrvm/lib/python3.6/site-packages/django/db/models/deletion.py", line 283, in delete
    count = qs._raw_delete(using=self.using)
  File "/Users/blue/.local/share/virtualenvs/djongo-gAwkvrvm/lib/python3.6/site-packages/django/db/models/query.py", line 676, in _raw_delete
    return sql.DeleteQuery(self.model).delete_qs(self, using)
  File "/Users/blue/.local/share/virtualenvs/djongo-gAwkvrvm/lib/python3.6/site-packages/django/db/models/sql/subqueries.py", line 75, in delete_qs
    cursor = self.get_compiler(using).execute_sql(CURSOR)
  File "/Users/blue/.local/share/virtualenvs/djongo-gAwkvrvm/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1066, in execute_sql
    cursor.execute(sql, params)
  File "/Users/blue/.local/share/virtualenvs/djongo-gAwkvrvm/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/Users/blue/.local/share/virtualenvs/djongo-gAwkvrvm/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/blue/.local/share/virtualenvs/djongo-gAwkvrvm/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/blue/.local/share/virtualenvs/djongo-gAwkvrvm/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/blue/.local/share/virtualenvs/djongo-gAwkvrvm/lib/python3.6/site-packages/djongo/cursor.py", line 55, in execute
    params)
  File "/Users/blue/.local/share/virtualenvs/djongo-gAwkvrvm/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 663, in __init__
    self.parse()
  File "/Users/blue/.local/share/virtualenvs/djongo-gAwkvrvm/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 746, in parse
    raise exe from e
djongo.sql2mongo.SQLDecodeError: FAILED SQL: DELETE FROM "mongo_namedate"
Version: 1.2.27
>>>

**Comment by Yutsuten** [comment]
Same problem here, using the latest versions of django and djongo.

**Comment by sokolski** [comment]
Also, same problem here, do you know if there is any solution to workaround ?

**Comment by sokolski** [comment]
finally, I found a solution:
you need to call delete for each objects in your queryset 

for example :
instead of `Articles.objects.all().delete()` 
write
`for article in Articles.objects.all():
     article.delete()`

**Comment by ruralscenery** [comment]
It could be using pymongo api directly

SomeModel.objects.mongo_remove({})

**Comment by nesdis** [comment]
Just pushed a fixed to the main branch. I think this should be solved
