### ISSUE TITLE
Running Server after setting Djongo up failed.

### ISSUE THREAD

**Issue by Basha0** [nesdis/djongo#134]
#### One line description of the issue
Cannot run server after setting up Database.

So i am new to python and I set up a testServer with Django and Vagrant.
So now I am trying to integrate a MongoDb into Django. 
I installed Djongo and also added the code sample of the database to Setting.py
but I am getting an Error after trying to Migrate/run the Server. 

```python
Settings.py
import os
import djongo

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

DATABASES = {
    'default': {
       'ENGINE': 'djongo',
       'NAME': 'room_dataBase',
    }
}

```

This is the Error I am getting while trying to start the Server or Migrate as discripted in the documentation.
"Run manage.py makemigrations <app_name> followed by manage.py migrate (ONLY the first time to create collections in MongoDB)"
Maybe its because that I have Python3.4? 
I hope someone can Help me :/ 

#### Traceback
(venv) basha@vagrant-ubuntu-trusty-64:~/mysite/roomres$ python3 manage.py runserver 0:8080
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fc8d9001840>
Traceback (most recent call last):
  File "/home/basha/venv/lib/python3.4/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/basha/venv/lib/python3.4/site-packages/django/core/management/commands/runserver.py", line 112, in inner_run
    autoreload.raise_last_exception()
  File "/home/basha/venv/lib/python3.4/site-packages/django/utils/autoreload.py", line 248, in raise_last_exception
    raise _exception[1]
  File "/home/basha/venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 327, in execute
    autoreload.check_errors(django.setup)()
  File "/home/basha/venv/lib/python3.4/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/basha/venv/lib/python3.4/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/basha/venv/lib/python3.4/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/home/basha/venv/lib/python3.4/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/basha/venv/lib/python3.4/site-packages/django/contrib/auth/models.py", line 2, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/home/basha/venv/lib/python3.4/site-packages/django/contrib/auth/base_user.py", line 47, in <module>
    class AbstractBaseUser(models.Model):
  File "/home/basha/venv/lib/python3.4/site-packages/django/db/models/base.py", line 114, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/home/basha/venv/lib/python3.4/site-packages/django/db/models/base.py", line 315, in add_to_class
    value.contribute_to_class(cls, name)
  File "/home/basha/venv/lib/python3.4/site-packages/django/db/models/options.py", line 205, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/home/basha/venv/lib/python3.4/site-packages/django/db/__init__.py", line 33, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/home/basha/venv/lib/python3.4/site-packages/django/db/utils.py", line 202, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/home/basha/venv/lib/python3.4/site-packages/django/db/utils.py", line 110, in load_backend
    return import_module('%s.base' % backend_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/basha/venv/lib/python3.4/site-packages/djongo/base.py", line 13, in <module>
    from .operations import DatabaseOperations
  File "/home/basha/venv/lib/python3.4/site-packages/djongo/operations.py", line 81
    return [f'ALTER TABLE "{table}" FLUSH'
                                         ^
SyntaxError: invalid syntax

**Comment by pauljickling** [comment]
You are correct when you speculate that perhaps it is because you are running Python3.4. I ran into the same errors until I installed and setup Python3.6.
