### ISSUE TITLE
Migration error while running save() function.

### ISSUE THREAD

**Issue by devmishrs** [nesdis/djongo#139]
#### One line description of the issue
Error while running save()
#### Python script

<The complete python script used to produce the issue.>

```python
>>> q = Question(question_text="What is your name?", pub_date=timezone.now())
>>> q.save()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/dev/.virtualenv/django/lib/python3.6/site-packages/django/db/models/base.py", line 729, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/dev/.virtualenv/django/lib/python3.6/site-packages/django/db/models/base.py", line 759, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/dev/.virtualenv/django/lib/python3.6/site-packages/django/db/models/base.py", line 842, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/dev/.virtualenv/django/lib/python3.6/site-packages/django/db/models/base.py", line 880, in _do_insert
    using=using, raw=raw)
  File "/home/dev/.virtualenv/django/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/dev/.virtualenv/django/lib/python3.6/site-packages/django/db/models/query.py", line 1125, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/dev/.virtualenv/django/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1285, in execute_sql
    cursor.execute(sql, params)
  File "/home/dev/.virtualenv/django/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/dev/.virtualenv/django/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/dev/.virtualenv/django/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/dev/.virtualenv/django/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/dev/.virtualenv/django/lib/python3.6/site-packages/djongo/cursor.py", line 53, in execute
    params)
  File "/home/dev/.virtualenv/django/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 706, in __init__
    self.parse()
  File "/home/dev/.virtualenv/django/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 769, in parse
    return handler(self, statement)
  File "/home/dev/.virtualenv/django/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 887, in _insert
    self._query = InsertQuery(self, self.db, self.connection_properties, sm, self._params)
  File "/home/dev/.virtualenv/django/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 360, in __init__
    super().__init__(*args)
  File "/home/dev/.virtualenv/django/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 73, in __init__
    self.parse()
  File "/home/dev/.virtualenv/django/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 448, in parse
    tok_id = self._table(2)
  File "/home/dev/.virtualenv/django/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 367, in _table
    raise MigrationError(collection)
djongo.sql2mongo.MigrationError: polls_question>

```

#### Traceback
<The complete stack trace of the error.>

**Comment by nesdis** [comment]
You have not run proper migrations. Which is causing this

**Comment by kiorq** [comment]
What are the proper migrations. I've ran makemigrations and it doesn't fix the issue for me.

**Comment by hsevi** [comment]
I have the same problem. Anyone has found a solution to this ?

**Comment by fannyhub** [comment]
have you passed correct values when creating the instance?
