### ISSUE TITLE
Can not connect to mongodb , says unauthorized user

### ISSUE THREAD

**Issue by rachitbshephertz** [nesdis/djongo#147]
#### One line description of the issue
can not connect to mongodb , says unauthorized user , but i am able to do so using mongo shell. 
#### Python script

DATABASES = {
       'default': {
           'ENGINE': 'djongo',
           'SOURCE': 'storagetwo',
           'USER': 'test',                      # Not used with sqlite3.
           'PASSWORD': 'test123',                  # Not used with sqlite3.
           'HOST': 'localhost',
           'mechanism': 'SCRAM-SHA-1',  # Set to empty string for localhost. Not used with sqlite3.
           'PORT': 27017,
       }
   }
#### Traceback
<The complete stack trace of the error.>
C:\Users\Rachit\PycharmProjects\django-python\venv\djangoPython36\Scripts\python.exe E:/github/App42PaaS-Python-MongoDB-Sample/manage.py runserver
Performing system checks...

System check identified no issues (0 silenced).
MongoCredential(mechanism='DEFAULT', source='admin', username='test', password='test123', mechanism_properties=None)
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x0403F468>
Traceback (most recent call last):
  File "C:\Users\Rachit\PycharmProjects\django-python\venv\djangoPython36\lib\site-packages\django\utils\autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Rachit\PycharmProjects\django-python\venv\djangoPython36\lib\site-packages\django\core\management\commands\runserver.py", line 123, in inner_run
    self.check_migrations()
  File "C:\Users\Rachit\PycharmProjects\django-python\venv\djangoPython36\lib\site-packages\django\core\management\base.py", line 427, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "C:\Users\Rachit\PycharmProjects\django-python\venv\djangoPython36\lib\site-packages\django\db\migrations\executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "C:\Users\Rachit\PycharmProjects\django-python\venv\djangoPython36\lib\site-packages\django\db\migrations\loader.py", line 49, in __init__
    self.build_graph()
  File "C:\Users\Rachit\PycharmProjects\django-python\venv\djangoPython36\lib\site-packages\django\db\migrations\loader.py", line 206, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "C:\Users\Rachit\PycharmProjects\django-python\venv\djangoPython36\lib\site-packages\django\db\migrations\recorder.py", line 61, in applied_migrations
    if self.has_table():
  File "C:\Users\Rachit\PycharmProjects\django-python\venv\djangoPython36\lib\site-packages\django\db\migrations\recorder.py", line 44, in has_table
    return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
  File "C:\Users\Rachit\PycharmProjects\django-python\venv\djangoPython36\lib\site-packages\django\db\backends\base\introspection.py", line 56, in table_names
    return get_names(cursor)
  File "C:\Users\Rachit\PycharmProjects\django-python\venv\djangoPython36\lib\site-packages\django\db\backends\base\introspection.py", line 51, in get_names
    return sorted(ti.name for ti in self.get_table_list(cursor)
  File "C:\Users\Rachit\PycharmProjects\django-python\venv\djangoPython36\lib\site-packages\djongo\introspection.py", line 34, in get_table_list
    for c in cursor.db_conn.collection_names(False)]
  File "C:\Users\Rachit\PycharmProjects\django-python\venv\djangoPython36\lib\site-packages\pymongo\database.py", line 617, in collection_names
    for result in self.list_collections(session=session, **kws)]
  File "C:\Users\Rachit\PycharmProjects\django-python\venv\djangoPython36\lib\site-packages\pymongo\database.py", line 586, in list_collections
    ReadPreference.PRIMARY) as (sock_info, slave_okay):
  File "C:\Users\Rachit\Python36-32\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "C:\Users\Rachit\PycharmProjects\django-python\venv\djangoPython36\lib\site-packages\pymongo\mongo_client.py", line 983, in _socket_for_reads
    with self._get_socket(server) as sock_info:
  File "C:\Users\Rachit\Python36-32\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "C:\Users\Rachit\PycharmProjects\django-python\venv\djangoPython36\lib\site-packages\pymongo\mongo_client.py", line 947, in _get_socket
    with server.get_socket(self.__all_credentials) as sock_info:
  File "C:\Users\Rachit\Python36-32\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "C:\Users\Rachit\PycharmProjects\django-python\venv\djangoPython36\lib\site-packages\pymongo\server.py", line 138, in get_socket
    with self.pool.get_socket(all_credentials, checkout) as sock_info:
  File "C:\Users\Rachit\Python36-32\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "C:\Users\Rachit\PycharmProjects\django-python\venv\djangoPython36\lib\site-packages\pymongo\pool.py", line 920, in get_socket
    sock_info.check_auth(all_credentials)
  File "C:\Users\Rachit\PycharmProjects\django-python\venv\djangoPython36\lib\site-packages\pymongo\pool.py", line 609, in check_auth
    auth.authenticate(credentials, self)
  File "C:\Users\Rachit\PycharmProjects\django-python\venv\djangoPython36\lib\site-packages\pymongo\auth.py", line 486, in authenticate
    credentials.source = 'storagetwo'
AttributeError: can't set attribute
Performing system checks...

System check identified no issues (0 silenced).
admin
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x03E61468>
Traceback (most recent call last):
  File "C:\Users\Rachit\PycharmProjects\django-python\venv\djangoPython36\lib\site-packages\django\utils\autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Rachit\PycharmProjects\django-python\venv\djangoPython36\lib\site-packages\django\core\management\commands\runserver.py", line 123, in inner_run
    self.check_migrations()
  File "C:\Users\Rachit\PycharmProjects\django-python\venv\djangoPython36\lib\site-packages\django\core\management\base.py", line 427, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "C:\Users\Rachit\PycharmProjects\django-python\venv\djangoPython36\lib\site-packages\django\db\migrations\executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "C:\Users\Rachit\PycharmProjects\django-python\venv\djangoPython36\lib\site-packages\django\db\migrations\loader.py", line 49, in __init__
    self.build_graph()
  File "C:\Users\Rachit\PycharmProjects\django-python\venv\djangoPython36\lib\site-packages\django\db\migrations\loader.py", line 206, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "C:\Users\Rachit\PycharmProjects\django-python\venv\djangoPython36\lib\site-packages\django\db\migrations\recorder.py", line 61, in applied_migrations
    if self.has_table():
  File "C:\Users\Rachit\PycharmProjects\django-python\venv\djangoPython36\lib\site-packages\django\db\migrations\recorder.py", line 44, in has_table
    return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
  File "C:\Users\Rachit\PycharmProjects\django-python\venv\djangoPython36\lib\site-packages\django\db\backends\base\introspection.py", line 56, in table_names
    return get_names(cursor)
  File "C:\Users\Rachit\PycharmProjects\django-python\venv\djangoPython36\lib\site-packages\django\db\backends\base\introspection.py", line 51, in get_names
    return sorted(ti.name for ti in self.get_table_list(cursor)
  File "C:\Users\Rachit\PycharmProjects\django-python\venv\djangoPython36\lib\site-packages\djongo\introspection.py", line 34, in get_table_list
    for c in cursor.db_conn.collection_names(False)]
  File "C:\Users\Rachit\PycharmProjects\django-python\venv\djangoPython36\lib\site-packages\pymongo\database.py", line 617, in collection_names
    for result in self.list_collections(session=session, **kws)]
  File "C:\Users\Rachit\PycharmProjects\django-python\venv\djangoPython36\lib\site-packages\pymongo\database.py", line 586, in list_collections
    ReadPreference.PRIMARY) as (sock_info, slave_okay):
  File "C:\Users\Rachit\Python36-32\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "C:\Users\Rachit\PycharmProjects\django-python\venv\djangoPython36\lib\site-packages\pymongo\mongo_client.py", line 983, in _socket_for_reads
    with self._get_socket(server) as sock_info:
  File "C:\Users\Rachit\Python36-32\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "C:\Users\Rachit\PycharmProjects\django-python\venv\djangoPython36\lib\site-packages\pymongo\mongo_client.py", line 947, in _get_socket
    with server.get_socket(self.__all_credentials) as sock_info:
  File "C:\Users\Rachit\Python36-32\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "C:\Users\Rachit\PycharmProjects\django-python\venv\djangoPython36\lib\site-packages\pymongo\server.py", line 138, in get_socket
    with self.pool.get_socket(all_credentials, checkout) as sock_info:
  File "C:\Users\Rachit\Python36-32\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "C:\Users\Rachit\PycharmProjects\django-python\venv\djangoPython36\lib\site-packages\pymongo\pool.py", line 920, in get_socket
    sock_info.check_auth(all_credentials)
  File "C:\Users\Rachit\PycharmProjects\django-python\venv\djangoPython36\lib\site-packages\pymongo\pool.py", line 609, in check_auth
    auth.authenticate(credentials, self)
  File "C:\Users\Rachit\PycharmProjects\django-python\venv\djangoPython36\lib\site-packages\pymongo\auth.py", line 488, in authenticate
    auth_func(credentials, sock_info)
  File "C:\Users\Rachit\PycharmProjects\django-python\venv\djangoPython36\lib\site-packages\pymongo\auth.py", line 210, in _authenticate_scram_sha1
    res = sock_info.command(source, cmd)
  File "C:\Users\Rachit\PycharmProjects\django-python\venv\djangoPython36\lib\site-packages\pymongo\pool.py", line 517, in command
    collation=collation)
  File "C:\Users\Rachit\PycharmProjects\django-python\venv\djangoPython36\lib\site-packages\pymongo\network.py", line 125, in command
    parse_write_concern_error=parse_write_concern_error)
  File "C:\Users\Rachit\PycharmProjects\django-python\venv\djangoPython36\lib\site-packages\pymongo\helpers.py", line 145, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: Authentication failed.

Process finished with exit code -1

**Comment by dblado** [comment]
If you haven't solved this yet, I had to use 'USERNAME' not 'USER'

**Comment by nesdis** [comment]
Thank you. Was not aware of this. Will update the docs to reflect it.

**Comment by rachitbshephertz** [comment]
Now it says no users are authenticated.
 
-----Original Message-----

**Comment by dblado** [comment]
I would try using pymongo directly to make sure you can connect:
see http://api.mongodb.com/python/current/examples/authentication.html

**Comment by rachitbshephertz** [comment]
Yup. that is  the way how i was able to connect eventually. The thing is i was also able to make connection using djongo with USER itself but the problem is in how i make user in mongo the steps are different then what we generally use and because of that while my python application was able to connect to mongo via djongo but my java, node and php applications failed. if i use different steps to create a user in mongo its vice versa.  if you wish i can share those steps.
 
I am sorry i didn't said this earlier but thank you for your time.
-----Original Message-----

**Comment by nesdis** [comment]
I assume this is now solved.

**Comment by radzhome** [comment]
I have a similar problem, because I only have access to a particular DB so in pymongo I have to include the db at the end of the host string url to connect. Djongo doesn't do this so I get `pymongo.errors.OperationFailure: Authentication failed.`. If I add the table name manually it gets a different error since the table is now part of the host and the port is added last `pymongo.errors.ServerSelectionTimeoutError: localhost/wcm-dev:13480: [Errno 8] nodename nor servname provided, or not known`. I think what would solve this is to include the db name when creating connection to mongo using MongoClient().

**Comment by radzhome** [comment]
To get around this particular issue, I had to patch the connect function in `djongo/database.py`.

```
import urllib

def connect(**kwargs):
    url = "mongodb://{}:{}@{}:{}/{}".format(kwargs['username'], urllib.parse.quote_plus(kwargs['password']), kwargs['host'], kwargs['port'], kwargs['name'])
    mc =  MongoClient(url)
    return mc
```

I also had to pass the database `name` field in `get_new_connection` in `djongo/base.py`:

Replace `name = connection_params.pop('name')` with `name = connection_params.get('name')`

That seemed to fix my authentication issue, as accessing mongodb without the database name gave me authentication errors.

**Comment by vlad-elagin** [comment]
@radzhome any ideas how to get things work when deployed to heroku? I can modify djongo files on their servers.

**Comment by nesdis** [comment]
I think this can be taken up as a todo item. Modify Djongo behavior to connect either using 'url' or other parameters. In case a 'url' is provided, simply ignore other params, else use the other params to make a MongoClient connection

**Comment by cmaliwal** [comment]
getting the same issue : 

```
System check identified no issues (0 silenced).
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f7ce3fce7b8>
Traceback (most recent call last):
  File "/home/chirag/projects/python-work/envs/trading-platform/lib/python3.6/site-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/home/chirag/projects/python-work/envs/trading-platform/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 128, in inner_run
    self.check_migrations()
  File "/home/chirag/projects/python-work/envs/trading-platform/lib/python3.6/site-packages/django/core/management/base.py", line 422, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/home/chirag/projects/python-work/envs/trading-platform/lib/python3.6/site-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/chirag/projects/python-work/envs/trading-platform/lib/python3.6/site-packages/django/db/migrations/loader.py", line 52, in __init__
    self.build_graph()
  File "/home/chirag/projects/python-work/envs/trading-platform/lib/python3.6/site-packages/django/db/migrations/loader.py", line 209, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/home/chirag/projects/python-work/envs/trading-platform/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 65, in applied_migrations
    self.ensure_schema()
  File "/home/chirag/projects/python-work/envs/trading-platform/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 52, in ensure_schema
    if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):
  File "/home/chirag/projects/python-work/envs/trading-platform/lib/python3.6/site-packages/djongo/introspection.py", line 6, in table_names
    return sorted(cursor.m_cli_connection.collection_names(False))
  File "/home/chirag/projects/python-work/envs/trading-platform/lib/python3.6/site-packages/pymongo/database.py", line 715, in collection_names
    nameOnly=True, **kws)]
  File "/home/chirag/projects/python-work/envs/trading-platform/lib/python3.6/site-packages/pymongo/database.py", line 677, in list_collections
    **kwargs)
  File "/home/chirag/projects/python-work/envs/trading-platform/lib/python3.6/site-packages/pymongo/database.py", line 631, in _list_collections
    session=tmp_session)["cursor"]
  File "/home/chirag/projects/python-work/envs/trading-platform/lib/python3.6/site-packages/pymongo/database.py", line 514, in _command
    client=self.__client)
  File "/home/chirag/projects/python-work/envs/trading-platform/lib/python3.6/site-packages/pymongo/pool.py", line 579, in command
    unacknowledged=unacknowledged)
  File "/home/chirag/projects/python-work/envs/trading-platform/lib/python3.6/site-packages/pymongo/network.py", line 150, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/home/chirag/projects/python-work/envs/trading-platform/lib/python3.6/site-packages/pymongo/helpers.py", line 155, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: there are no users authenticated
```

this is my setting file : 

```
DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'NAME': 'test',
        'HOST': 'localhost',
        'PORT': 27017,
        'USERNAME': 'admin',
        'PASSWORD': 'admin'
    }
}
```

**Comment by GliderDev** [comment]
DATABASES = {
'default': {
'ENGINE': 'djongo',
'NAME': 'test_db',
'USER': 'test_user',
'PASSWORD': 'test#1',
'HOST': '127.0.0.1',
'PORT': 27017,
'AUTH_SOURCE': 'test_db',
'AUTH_MECHANISM': 'SCRAM-SHA-1'
}
}

try this configuration.. I was facing same issue and this helped!
