### ISSUE TITLE
Authentication failed while connecting to MongoDB server in mlab.com

### ISSUE THREAD

**Issue by nieltg** [nesdis/djongo#151]
#### One line description of the issue

`Authentication failed` was raised while connecting to MongoDB server in [mlab.com](https://mlab.com) with some suspicious correlation with this StackOverflow answer [here](https://stackoverflow.com/a/36201416/9186433).

#### Python script

```python
DATABASES = {{
    'default': {
        'NAME': 'django-linecms-demo',
        'USER': '<username>',
        'PASSWORD': '<password>',
        'HOST': '<code>.mlab.com',
        'PORT': <port>,
        'ENGINE': 'djongo'
    }
}}
```

#### Traceback

<details>
<summary>Full trackback can be seen here.</summary>

```
Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/home/nieltg/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/home/nieltg/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/nieltg/.local/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/nieltg/.local/lib/python3.6/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 59, in execute
    return super().execute(*args, **options)
  File "/home/nieltg/.local/lib/python3.6/site-packages/django/core/management/base.py", line 334, in execute
    self.check_migrations()
  File "/home/nieltg/.local/lib/python3.6/site-packages/django/core/management/base.py", line 427, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/home/nieltg/.local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/nieltg/.local/lib/python3.6/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/home/nieltg/.local/lib/python3.6/site-packages/django/db/migrations/loader.py", line 206, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/home/nieltg/.local/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 61, in applied_migrations
    if self.has_table():
  File "/home/nieltg/.local/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 44, in has_table
    return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
  File "/home/nieltg/.local/lib/python3.6/site-packages/django/db/backends/base/introspection.py", line 56, in table_names
    return get_names(cursor)
  File "/home/nieltg/.local/lib/python3.6/site-packages/django/db/backends/base/introspection.py", line 51, in get_names
    return sorted(ti.name for ti in self.get_table_list(cursor)
  File "/home/nieltg/.local/lib/python3.6/site-packages/djongo/introspection.py", line 34, in get_table_list
    for c in cursor.db_conn.collection_names(False)]
  File "/home/nieltg/.local/lib/python3.6/site-packages/pymongo/database.py", line 715, in collection_names
    nameOnly=True, **kws)]
  File "/home/nieltg/.local/lib/python3.6/site-packages/pymongo/database.py", line 674, in list_collections
    read_pref) as (sock_info, slave_okay):
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/nieltg/.local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1101, in _socket_for_reads
    with self._get_socket(server) as sock_info:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/nieltg/.local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1058, in _get_socket
    with server.get_socket(self.__all_credentials) as sock_info:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/nieltg/.local/lib/python3.6/site-packages/pymongo/pool.py", line 1006, in get_socket
    sock_info.check_auth(all_credentials)
  File "/home/nieltg/.local/lib/python3.6/site-packages/pymongo/pool.py", line 677, in check_auth
    auth.authenticate(credentials, self)
  File "/home/nieltg/.local/lib/python3.6/site-packages/pymongo/auth.py", line 542, in authenticate
    auth_func(credentials, sock_info)
  File "/home/nieltg/.local/lib/python3.6/site-packages/pymongo/auth.py", line 519, in _authenticate_default
    return _authenticate_scram(credentials, sock_info, 'SCRAM-SHA-1')
  File "/home/nieltg/.local/lib/python3.6/site-packages/pymongo/auth.py", line 245, in _authenticate_scram
    res = sock_info.command(source, cmd)
  File "/home/nieltg/.local/lib/python3.6/site-packages/pymongo/pool.py", line 579, in command
    unacknowledged=unacknowledged)
  File "/home/nieltg/.local/lib/python3.6/site-packages/pymongo/network.py", line 150, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/home/nieltg/.local/lib/python3.6/site-packages/pymongo/helpers.py", line 155, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: Authentication failed.
```

</details>

**Comment by nieltg** [comment]
I fixed this issue by adding `AUTH_SOURCE`, now it will works if specified like this.

```python
DATABASES = {{
    'default': {
        'NAME': 'django-linecms-demo',
        'AUTH_SOURCE': 'django-linecms-demo',
        'USER': '<username>',
        'PASSWORD': '<password>',
        'HOST': '<code>.mlab.com',
        'PORT': <port>,
        'ENGINE': 'djongo'
    }
}}
```

Thank you very much.

**Comment by AhmadAyyaz1993** [comment]
I have used the same code but getting authentication failed error. Any idea what else could cause this?

**Comment by GliderDev** [comment]
DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'NAME': 'test_db',
        'USER': 'test_user',
        'PASSWORD': 'test#1',
        'HOST': '127.0.0.1',
        'PORT': 27017,
        'AUTH_SOURCE': 'test_db',
        'AUTH_MECHANISM': 'SCRAM-SHA-1'
    }
}

try this configuration.. I was facing same issue and this helped!

**Comment by Khande1n** [comment]
@GliderDev I cannot be more thankful to you as your answer saved my day......

**Comment by victorcmoura** [comment]
@GliderDev and @nieltg, thank you very much!
