### ISSUE TITLE
mongo 3.2.x support

### ISSUE THREAD

**Issue by radzhome** [nesdis/djongo#157]
#### One line description of the issue

Was wondering what it would take to get mongo 3.2 support. Stuck on that version and can't get it running. Does maybe the old version of djongo support it?

#### Traceback

Here is the error I get when running djongo on mongo 3.2.16

```python
(content-services-djongo-32J-jGSB) bash-3.2$ python manage.py createsuperuser
Username (leave blank to use 'rwojcik'): rad
Error: That username is already taken.
Username (leave blank to use 'rwojcik'): rad
Email address: r@r.com
Password:
Password (again):
Error: Your passwords didn't match.
Password:
Password (again):
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/rwojcik/.local/share/virtualenvs/content-services-djongo-32J-jGSB/lib/python3.7/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/Users/rwojcik/.local/share/virtualenvs/content-services-djongo-32J-jGSB/lib/python3.7/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/rwojcik/.local/share/virtualenvs/content-services-djongo-32J-jGSB/lib/python3.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/rwojcik/.local/share/virtualenvs/content-services-djongo-32J-jGSB/lib/python3.7/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 59, in execute
    return super().execute(*args, **options)
  File "/Users/rwojcik/.local/share/virtualenvs/content-services-djongo-32J-jGSB/lib/python3.7/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/Users/rwojcik/.local/share/virtualenvs/content-services-djongo-32J-jGSB/lib/python3.7/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 179, in handle
    self.UserModel._default_manager.db_manager(database).create_superuser(**user_data)
  File "/Users/rwojcik/.local/share/virtualenvs/content-services-djongo-32J-jGSB/lib/python3.7/site-packages/django/contrib/auth/models.py", line 161, in create_superuser
    return self._create_user(username, email, password, **extra_fields)
  File "/Users/rwojcik/.local/share/virtualenvs/content-services-djongo-32J-jGSB/lib/python3.7/site-packages/django/contrib/auth/models.py", line 144, in _create_user
    user.save(using=self._db)
  File "/Users/rwojcik/.local/share/virtualenvs/content-services-djongo-32J-jGSB/lib/python3.7/site-packages/django/contrib/auth/base_user.py", line 73, in save
    super().save(*args, **kwargs)
  File "/Users/rwojcik/.local/share/virtualenvs/content-services-djongo-32J-jGSB/lib/python3.7/site-packages/django/db/models/base.py", line 729, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/rwojcik/.local/share/virtualenvs/content-services-djongo-32J-jGSB/lib/python3.7/site-packages/django/db/models/base.py", line 759, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/rwojcik/.local/share/virtualenvs/content-services-djongo-32J-jGSB/lib/python3.7/site-packages/django/db/models/base.py", line 842, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Users/rwojcik/.local/share/virtualenvs/content-services-djongo-32J-jGSB/lib/python3.7/site-packages/django/db/models/base.py", line 880, in _do_insert
    using=using, raw=raw)
  File "/Users/rwojcik/.local/share/virtualenvs/content-services-djongo-32J-jGSB/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/rwojcik/.local/share/virtualenvs/content-services-djongo-32J-jGSB/lib/python3.7/site-packages/django/db/models/query.py", line 1125, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/rwojcik/.local/share/virtualenvs/content-services-djongo-32J-jGSB/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1285, in execute_sql
    cursor.execute(sql, params)
  File "/Users/rwojcik/.local/share/virtualenvs/content-services-djongo-32J-jGSB/lib/python3.7/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/Users/rwojcik/.local/share/virtualenvs/content-services-djongo-32J-jGSB/lib/python3.7/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/rwojcik/.local/share/virtualenvs/content-services-djongo-32J-jGSB/lib/python3.7/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/rwojcik/.local/share/virtualenvs/content-services-djongo-32J-jGSB/lib/python3.7/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/rwojcik/.local/share/virtualenvs/content-services-djongo-32J-jGSB/lib/python3.7/site-packages/djongo/cursor.py", line 53, in execute
    params)
  File "/Users/rwojcik/.local/share/virtualenvs/content-services-djongo-32J-jGSB/lib/python3.7/site-packages/djongo/sql2mongo/query.py", line 706, in __init__
    self.parse()
  File "/Users/rwojcik/.local/share/virtualenvs/content-services-djongo-32J-jGSB/lib/python3.7/site-packages/djongo/sql2mongo/query.py", line 769, in parse
    return handler(self, statement)
  File "/Users/rwojcik/.local/share/virtualenvs/content-services-djongo-32J-jGSB/lib/python3.7/site-packages/djongo/sql2mongo/query.py", line 887, in _insert
    self._query = InsertQuery(self, self.db, self.connection_properties, sm, self._params)
  File "/Users/rwojcik/.local/share/virtualenvs/content-services-djongo-32J-jGSB/lib/python3.7/site-packages/djongo/sql2mongo/query.py", line 360, in __init__
    super().__init__(*args)
  File "/Users/rwojcik/.local/share/virtualenvs/content-services-djongo-32J-jGSB/lib/python3.7/site-packages/djongo/sql2mongo/query.py", line 73, in __init__
    self.parse()
  File "/Users/rwojcik/.local/share/virtualenvs/content-services-djongo-32J-jGSB/lib/python3.7/site-packages/djongo/sql2mongo/query.py", line 448, in parse
    tok_id = self._table(2)
  File "/Users/rwojcik/.local/share/virtualenvs/content-services-djongo-32J-jGSB/lib/python3.7/site-packages/djongo/sql2mongo/query.py", line 367, in _table
    raise MigrationError(collection)
djongo.sql2mongo.MigrationError: auth_user

```

**Comment by radzhome** [comment]
I was able to fork the code and patch a few things to get things going under mongo 3.2.12 but will be upgrading to mongo 3.4+ instead

**Comment by losewin** [comment]
Can you share your alternatives?
