### ISSUE TITLE
[BUG] Random DoesNotExist exceptions when querying objects with foreign keys

### ISSUE THREAD

**Issue by m4jr0** [nesdis/djongo#162]
#### Random DoesNotExist exceptions when querying objects with foreign keys

Hello,

Sometimes, when I query the database for an object which has foreign keys, I have some random exceptions raised (please see the traceback below). I'm not sure about this, but I think it may be because of some queries happening *at the same time* and on *the same collection*, somewhere in my code.

So, to be certain it wasn't a bug from my models, I created some dummy objects in an empty Django/Djongo project:

```python
import json

from djongo import models


class ForeignKey1(models.Model):
    objects = models.DjongoManager()
    _id = models.ObjectIdField()
    name = models.TextField(unique=True)

    @classmethod
    def create(cls, *args, **kwargs):
        new_instance = cls(*args, **kwargs)

        return new_instance

    def __str__(self):
        return self.to_json()

    def to_json(self):
        return json.dumps(self.to_dict())

    def to_dict(self):
        return {
            "_id": str(self._id),
            "name": self.name
        }


class ForeignKey2(models.Model):
    objects = models.DjongoManager()
    _id = models.ObjectIdField()
    name = models.TextField(unique=True)

    @classmethod
    def create(cls, *args, **kwargs):
        new_instance = cls(*args, **kwargs)

        return new_instance

    def __str__(self):
        return self.to_json()

    def to_json(self):
        return json.dumps(self.to_dict())

    def to_dict(self):
        return {
            "_id": str(self._id),
            "name": self.name
        }


class DummyObject(models.Model):
    _id = models.ObjectIdField()
    foreign_key_1 = models.ForeignKey(ForeignKey1, on_delete=models.PROTECT)
    foreign_key_2 = models.ForeignKey(ForeignKey2, on_delete=models.PROTECT)

    def __str__(self):
        return self.to_json()

    def to_json(self):
        return json.dumps(self.to_dict())

    def to_dict(self):
        return {
            "_id": str(self._id),
            "foreign_key_1": self.foreign_key_1.to_dict(),
            "foreign_key_2": self.foreign_key_2.to_dict()
        }

    @classmethod
    def create(cls, *args, **kwargs):
        new_instance = cls(*args, **kwargs)

        return new_instance
```

And so, I was able to reproduce the bug by writing a Django-style test which make queries in different threads, to make them happening *at the same time*:

```python
from django.test import TransactionTestCase
from threading import Thread

from myapp.models import ForeignKey1, ForeignKey2, DummyObject


def make_request():
    objects = DummyObject.objects.all()

    print(objects)

class MetaScanConcurrencyTest(TransactionTestCase):
    def setUp(self):
        foreign_key_1 = ForeignKey1.create(**{
            "name": "foreign_key_1"
        })

        foreign_key_2 = ForeignKey2.create(**{
            "name": "foreign_key_2"
        })

        foreign_key_1.save()
        foreign_key_2.save()

        for i in range(0, 1):
            dummy = DummyObject.create(**{
                "foreign_key_1": foreign_key_1,
                "foreign_key_2": foreign_key_2
            })

            dummy.save()

    def test_concurrency_test(self):
        for i in range(0, 20):
            Thread(target=make_request).start()
```

When I run it, sometimes the query works (meaning, when I print my dummy objects in my query set, `foreign_key_1.to_dict()` and `foreign_key_2.to_dict()` work correctly):

```python
<QuerySet [<DummyObject: {"_id": "5b586753b70a7b291666c3ae", "foreign_key_1": {"_id": "5b586753b70a7b291666c3ac", "name": "foreign_key_1"}, "foreign_key_2": {"_id": "5b586753b70a7b291666c3ad", "name": "foreign_key_2"}}>]>
```

And sometimes, it does not:

```python
Traceback (most recent call last):
  File "/home/user/testsite/env/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 158, in __get__
    rel_obj = self.field.get_cached_value(instance)
  File "/home/user/testsite/env/lib/python3.6/site-packages/django/db/models/fields/mixins.py", line 13, in get_cached_value
    return instance._state.fields_cache[cache_name]
KeyError: 'foreign_key_1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/testsite/mysite/myapp/tests.py", line 10, in make_request
    print(objects)
  File "/home/user/testsite/env/lib/python3.6/site-packages/django/db/models/query.py", line 251, in __repr__
    return '<%s %r>' % (self.__class__.__name__, data)
  File "/home/user/testsite/env/lib/python3.6/site-packages/django/db/models/base.py", line 513, in __repr__
    return '<%s: %s>' % (self.__class__.__name__, self)
  File "/home/user/testsite/mysite/myapp/models.py", line 60, in __str__
    return self.to_json()
  File "/home/user/testsite/mysite/myapp/models.py", line 63, in to_json
    return json.dumps(self.to_dict())
  File "/home/user/testsite/mysite/myapp/models.py", line 68, in to_dict
    "foreign_key_1": self.foreign_key_1.to_dict(),
  File "/home/user/testsite/env/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 164, in __get__
    rel_obj = self.get_object(instance)
  File "/home/user/testsite/env/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 139, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
  File "/home/user/testsite/env/lib/python3.6/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
myapp.models.DoesNotExist: ForeignKey1 matching query does not exist.
```
The more threads I add (I tested up to 100), the more exceptions are raised.

For 20 threads, you can see the complete test ran [here](https://pastebin.com/SxF1aBmk).

Keep up the good work!

**Comment by m4jr0** [comment]
You can find the entire Django project [here](https://github.com/nesdis/djongo/files/2227908/mysite.zip).

**Comment by ronmorannielsen** [comment]
+1 This avoids us from moving to production with djongo!
This is a serious issue... Did anybody else came across it?

**Comment by jjourdin** [comment]
+1 djongo is not thread-safe

Issues are reproductible with Python only, django runserver and Apache WSGI.
Problems disappear as soon as threading is disabled.

We are a team ready to help develop a patch, but we need some help to figure out where to start...

**Comment by jjourdin** [comment]
The example given above is buggy. 
After calling thread.start() you need to call thread.join() in order to wait for the thread to be finished.

The above code for test_concurrency_test works perfectly:

def test_concurrency_test(self):
        tlist=list()
        for i in range(0, 20):
            t = Thread(target=make_request)
            tlist.append(t)
            t.start()

        for t in tlist:
            t.join()

**Comment by pratibhajagnere** [comment]
Hi,

Were you or anyone else. able to resolve this issue? 

I am facing the same in Django ==2.1 and djongo==1.2.31 / 1.2.33

**Comment by prakashgun** [comment]
I am also facing the same issue:

Django==2.2.4
djongo==1.2.33
sqlparse==0.2.4

**Comment by nitheeshkennedy** [comment]
I'm also having the same issue. Please find a fix for this as this would help me in continuing my project.

**Comment by nigelgutzmann** [comment]
Agreed, this is blocking me as well. Any solutions that people have found would be much appreciated!

**Comment by nitheeshkennedy** [comment]
Please anyone post a solution or walk around if you have found any..!! :(

**Comment by Rockflo** [comment]
I am also facing the same issue and this happens only when I launch some queries happening at the same time and on the same collection. Even worse, in this same context, sometimes my results are mixed between different foreign keys, which is quite frightening actually. This avoids me of course from moving to production with djongo.

**Comment by nigelgutzmann** [comment]
I am working with @nesdis to come up with a solution. I've made a complete reproduction in my project here, with a screen recording demonstrating the issue: https://github.com/nigelgutzmann/djongo-bug

I also have a screen recording demonstrating the same issue using the above `MetaScanConcurrencyTest`, with the `thread.join()` included, as pointed out in the comments in this thread. https://www.loom.com/share/35f45405b91c456eaa1754d9b946c12a
