### ISSUE TITLE
Any support added for Django 2.x ??

### ISSUE THREAD

**Issue by Rakin061** [nesdis/djongo#163]
### Specifications:-

> Python 3.6.3
> Django 2.0.7
> MongoDB 4.0.0

In **settings.py** configurations ;-

```
DATABASES = {
        'default': {
            'ENGINE': 'djongo',
            'ENFORCE_SCHEMA': True
            'NAME': 'your-db-name',
            'HOST': 'host-name or ip address',
            'PORT': port_number,
            'USER': 'db-username',
            'PASSWORD': 'password',
            'AUTH_SOURCE': 'db-name',
            'AUTH_MECHANISM': 'SCRAM-SHA-1',
            'REPLICASET': 'replicaset',
            'SSL': 'ssl',
            'SSL_CERTFILE': 'ssl_certfile',
            'SSL_CA_CERTS': 'ssl_ca_certs',
            'READ_PREFERENCE': 'read_preference'
        }
    }
```
is not working in  Djanog 2.0.7 ?

In Djanog 2.0.7  Database Engine  support some fixed set of values like `django.db.backends.sqlite3 ` ..... 

Is it tested in Django 2.x ? Wouldn't it be nice to gave support for Django 2.x ??

**Comment by nesdis** [comment]
Yes Djongo does require Django >=2.0 for working. Have not tested with 2.0.7

**Comment by nesdis** [comment]
The above settings work fine on 2.0.7. What is the error you get?

**Comment by Rakin061** [comment]
Thanks for checking that out!

As I mentioned earlier, in Djanog 2.0.7 settings,  Database Engine support some fixed set of values like django.db.backends.sqlite3 ... 
So, when I am using the Engine name 'django' I am getting errors.

### Error:


> django.core.exceptions.ImproperlyConfigured: 'django' isn't an available database backend.
> Try using 'django.db.backends.XXX', where XXX is one of:
>     'mysql', 'oracle', 'postgresql', 'sqlite3'


### Full traceback

> Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x00000005F78BB2F0>
> Traceback (most recent call last):
>   File "E:\Django\virtual\lib\site-packages\django\db\utils.py", line 110, in load_backend
>     return import_module('%s.base' % backend_name)
>   File "E:\Python 3.7.0b4\lib\importlib\__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
> ModuleNotFoundError: No module named 'django.base'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "E:\Django\virtual\lib\site-packages\django\utils\autoreload.py", line 225, in wrapper
>     fn(*args, **kwargs)
>   File "E:\Django\virtual\lib\site-packages\django\core\management\commands\runserver.py", line 112, in inner_run
>     autoreload.raise_last_exception()
>   File "E:\Django\virtual\lib\site-packages\django\utils\autoreload.py", line 248, in raise_last_exception
>     raise _exception[1]
>   File "E:\Django\virtual\lib\site-packages\django\core\management\__init__.py", line 327, in execute
>     autoreload.check_errors(django.setup)()
>   File "E:\Django\virtual\lib\site-packages\django\utils\autoreload.py", line 225, in wrapper
>     fn(*args, **kwargs)
>   File "E:\Django\virtual\lib\site-packages\django\__init__.py", line 24, in setup
>     apps.populate(settings.INSTALLED_APPS)
>   File "E:\Django\virtual\lib\site-packages\django\apps\registry.py", line 112, in populate
>     app_config.import_models()
>   File "E:\Django\virtual\lib\site-packages\django\apps\config.py", line 198, in import_models
>     self.models_module = import_module(models_module_name)
>   File "E:\Python 3.7.0b4\lib\importlib\__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 726, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "E:\Django\music\models.py", line 3, in <module>
>     class Album(models.Model):
>   File "E:\Django\virtual\lib\site-packages\django\db\models\base.py", line 114, in __new__
>     new_class.add_to_class('_meta', Options(meta, app_label))
>   File "E:\Django\virtual\lib\site-packages\django\db\models\base.py", line 315, in add_to_class
>     value.contribute_to_class(cls, name)
>   File "E:\Django\virtual\lib\site-packages\django\db\models\options.py", line 205, in contribute_to_class
>     self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
>   File "E:\Django\virtual\lib\site-packages\django\db\__init__.py", line 33, in __getattr__
>     return getattr(connections[DEFAULT_DB_ALIAS], item)
>   File "E:\Django\virtual\lib\site-packages\django\db\utils.py", line 202, in __getitem__
>     backend = load_backend(db['ENGINE'])
>   File "E:\Django\virtual\lib\site-packages\django\db\utils.py", line 125, in load_backend
>     ) from e_user
> django.core.exceptions.ImproperlyConfigured: 'django' isn't an available database backend.
> Try using 'django.db.backends.XXX', where XXX is one of:
>     'mysql', 'oracle', 'postgresql', 'sqlite3'

**Comment by yeungocanh** [comment]
> Thanks for checking that out!
> 
> As I mentioned earlier, in Djanog 2.0.7 settings, Database Engine support some fixed set of values like django.db.backends.sqlite3 ...
> So, when I am using the Engine name 'django' I am getting errors.
> 
> ### Error:
> > django.core.exceptions.ImproperlyConfigured: 'django' isn't an available database backend.
> > Try using 'django.db.backends.XXX', where XXX is one of:
> > 'mysql', 'oracle', 'postgresql', 'sqlite3'
> 
> ### Full traceback
> > Unhandled exception in thread started by <function check_errors..wrapper at 0x00000005F78BB2F0>
> > Traceback (most recent call last):
> > File "E:\Django\virtual\lib\site-packages\django\db\utils.py", line 110, in load_backend
> > return import_module('%s.base' % backend_name)
> > File "E:\Python 3.7.0b4\lib\importlib__init__.py", line 127, in import_module
> > return _bootstrap._gcd_import(name[level:], package, level)
> > File "", line 1006, in _gcd_import
> > File "", line 983, in _find_and_load
> > File "", line 965, in _find_and_load_unlocked
> > ModuleNotFoundError: No module named 'django.base'
> > The above exception was the direct cause of the following exception:
> > Traceback (most recent call last):
> > File "E:\Django\virtual\lib\site-packages\django\utils\autoreload.py", line 225, in wrapper
> > fn(*args, **kwargs)
> > File "E:\Django\virtual\lib\site-packages\django\core\management\commands\runserver.py", line 112, in inner_run
> > autoreload.raise_last_exception()
> > File "E:\Django\virtual\lib\site-packages\django\utils\autoreload.py", line 248, in raise_last_exception
> > raise _exception[1]
> > File "E:\Django\virtual\lib\site-packages\django\core\management__init__.py", line 327, in execute
> > autoreload.check_errors(django.setup)()
> > File "E:\Django\virtual\lib\site-packages\django\utils\autoreload.py", line 225, in wrapper
> > fn(*args, **kwargs)
> > File "E:\Django\virtual\lib\site-packages\django__init__.py", line 24, in setup
> > apps.populate(settings.INSTALLED_APPS)
> > File "E:\Django\virtual\lib\site-packages\django\apps\registry.py", line 112, in populate
> > app_config.import_models()
> > File "E:\Django\virtual\lib\site-packages\django\apps\config.py", line 198, in import_models
> > self.models_module = import_module(models_module_name)
> > File "E:\Python 3.7.0b4\lib\importlib__init__.py", line 127, in import_module
> > return _bootstrap._gcd_import(name[level:], package, level)
> > File "", line 1006, in _gcd_import
> > File "", line 983, in _find_and_load
> > File "", line 967, in _find_and_load_unlocked
> > File "", line 677, in _load_unlocked
> > File "", line 726, in exec_module
> > File "", line 219, in _call_with_frames_removed
> > File "E:\Django\music\models.py", line 3, in 
> > class Album(models.Model):
> > File "E:\Django\virtual\lib\site-packages\django\db\models\base.py", line 114, in **new**
> > new_class.add_to_class('_meta', Options(meta, app_label))
> > File "E:\Django\virtual\lib\site-packages\django\db\models\base.py", line 315, in add_to_class
> > value.contribute_to_class(cls, name)
> > File "E:\Django\virtual\lib\site-packages\django\db\models\options.py", line 205, in contribute_to_class
> > self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
> > File "E:\Django\virtual\lib\site-packages\django\db__init__.py", line 33, in **getattr**
> > return getattr(connections[DEFAULT_DB_ALIAS], item)
> > File "E:\Django\virtual\lib\site-packages\django\db\utils.py", line 202, in **getitem**
> > backend = load_backend(db['ENGINE'])
> > File "E:\Django\virtual\lib\site-packages\django\db\utils.py", line 125, in load_backend
> > ) from e_user
> > django.core.exceptions.ImproperlyConfigured: 'django' isn't an available database backend.
> > Try using 'django.db.backends.XXX', where XXX is one of:
> > 'mysql', 'oracle', 'postgresql', 'sqlite3'

`djongo` not `django`

**Comment by anubhavpsit** [comment]
Is it working with 3.0.dev20190215005738 ? as i am also getting the same error.

> ```
> django.core.exceptions.ImproperlyConfigured: 'djongo' isn't an available database backend.
> Try using 'django.db.backends.XXX', where XXX is one of:
>     'mysql', 'oracle', 'postgresql', 'sqlite3'
> 
> ```

**Comment by Error1996** [comment]
> Is it working with 3.0.dev20190215005738 ? as i am also getting the same error.
> 
> > ```
> > django.core.exceptions.ImproperlyConfigured: 'djongo' isn't an available database backend.
> > Try using 'django.db.backends.XXX', where XXX is one of:
> >     'mysql', 'oracle', 'postgresql', 'sqlite3'
> > ```

i am also getting the same error, please help me.
my django project and (python, django, mongodb) are installed on a different disc (local disk (D:) and local disk (C:)  respectively).
can this be an issue in connecting django and mongodb.

**Comment by viktorkho** [comment]
The same problem with mongo v4.2.1

**Comment by sidshrivastav** [comment]
Try using `Django 2.2`.
