### ISSUE TITLE
 No module named 'django.db.models.fields.mixins'

### ISSUE THREAD

**Issue by 728443778** [nesdis/djongo#175]
#### Python script

<The complete python script used to produce the issue.>

```python
from djongo import models

class Blog(models.Model):
    name = models.CharField(max_length=100)
    tagline=models.TextField()
    class Meta:
        abstract=True

class Entry(models.Model):
    blog = models.EmbeddedModelField(
        model_container=Blog,
    )
    headline = models.CharField(max_length=255)


```

#### Traceback
when i run python3 manage.py
```Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/management/__init__.py", line 337, in execute
    django.setup()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/edz/python_projects/djongo_test/demo/models.py", line 1, in <module>
    from djongo import models
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/djongo/models/__init__.py", line 3, in <module>
    from .fields import (
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/djongo/models/fields.py", line 28, in <module>
    from django.db.models.fields.mixins import FieldCacheMixin
ModuleNotFoundError: No module named 'django.db.models.fields.mixins'
```

**Comment by 728443778** [comment]
python version:Python 3.6.1
Django version:1.11.3
Djongo version:1.2.26
