### ISSUE TITLE
TypeError: A Formless Field cannot be modified from Django Admin.

### ISSUE THREAD

**Issue by srinivasu-apalya** [nesdis/djongo#180]
#### Python script

<The complete python script used to produce the issue.>

```python
<copy and paste code here>

```

#### Traceback
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/pyenv/myplex3.6/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/pyenv/myplex3.6/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/opt/pyenv/myplex3.6/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/pyenv/myplex3.6/lib/python3.6/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/opt/pyenv/myplex3.6/lib/python3.6/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/opt/pyenv/myplex3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/myplex/myplex_pms/myplex_pms_service/pms/models.py", line 146, in <module>
    class JobDrmForm(forms.ModelForm):
  File "/opt/pyenv/myplex3.6/lib/python3.6/site-packages/django/forms/models.py", line 256, in __new__
    apply_limit_choices_to=False,
  File "/opt/pyenv/myplex3.6/lib/python3.6/site-packages/django/forms/models.py", line 172, in fields_for_model
    formfield = f.formfield(**kwargs)
  File "/opt/pyenv/myplex3.6/lib/python3.6/site-packages/djongo/models/fields.py", line 85, in formfield
    'A Formless Field cannot be modified from Django Admin.'
TypeError: A Formless Field cannot be modified from Django Admin.

**Comment by Sandeepbasva-apalya** [comment]
I also faced same issue when I defined model field with type as ListField(blank=True).

Can any one help me on solution?

**Comment by Sandeepbasva-apalya** [comment]
Getting this error (TypeError: A Formless Field cannot be modified from Django Admin. ) while using version 1.2.29, not with older versions
But for older versions embedded query field is not working, getting empty queryset.

**Comment by bomkarram** [comment]
I solved this problem by adding `exclude` to admin class

model.py
```
class Config(models.Model):
    ...
    result = models.DictField(default={})
    ...
```

admin.py
```
from django.contrib import admin
from test_harness.models import Config

class ConfigAdmin(admin.ModelAdmin):
    exclude = ('result',)

admin.site.register(Config, ConfigAdmin)
```

**Comment by skeezus** [comment]
It doesn't look like this library allows you to edit those fields in the django admin. ListField inherits from FormlessField which raises a type error in its formfield method (just reading from their source code).

If you need to use the admin, it looks like the JSONField could be a temporary solution. You can access it here `from djongo.models.json import JSONField`

**Comment by Miladkhodabandehloo** [comment]
You can resolve this problem with this code snippet and using the `CustomListField` instead of `ListField`.

`class ListFormField(forms.CharField):
    def to_python(self, value):
        if value is None:
            value = ""
        return value.split(",")

    def prepare_value(self, value):
        if value is None:
            value = []
        return ",".join(value)


class CustomListField(models.ListField):
    def formfield(self, **kwargs):
        return ListFormField(max_length=1000)`

**Comment by akashtalole** [comment]
Facing same issue with djongo==1.2.36 and Django==2.1.3
