### ISSUE TITLE
One to One Field migration raises error

### ISSUE THREAD

**Issue by ronmorannielsen** [nesdis/djongo#182]
If a migration of a OneToOneField is done in a single migration (as opposed to first migration as foreign key, and second using onetoonefield. That's the workaround), the migration fails with the following:

#### Error
<  Applying oauth2_provider.0006_auto_20171214_2232...Traceback (most recent call last):
  File "/Users/ron/.virtualenvs/newdjango/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 639, in parse
    return handler(self, statement)
  File "/Users/ron/.virtualenvs/newdjango/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 667, in _alter
    self._query.execute()
  File "/Users/ron/.virtualenvs/newdjango/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 519, in _unique
    self.index,
AttributeError: 'AlterQuery' object has no attribute 'index'>

The SQL String failing is ```ALTER TABLE "oauth2_provider_accesstoken" ADD COLUMN "source_refresh_token_id" integer NULL UNIQUE```

It appears the issue stems in the file ```sql2mongo/query.py``` in the function ```_add```:
<            elif tok.match(tokens.Keyword, 'UNIQUE'):
                self.execute = self._unique
            elif tok.match(tokens.Keyword, 'FOREIGN'):
                self.execute = self._fk
            elif tok.match(tokens.Keyword, 'COLUMN'):
                self.execute = self._add_column>

Since the execute methods first gets the value ```COLUMN``` and then ```UNIQUE```, meaning you cannot create in a single migration a unique column, which is a reasonable operation.

The error is easy to recreate: Start a Django app with oauth2_provider:
```
pip install django-oauth-toolkit==1.2.0
pip install django==2.0
```
And add in the ```INSTALLED_APPS``` list in the ```settings.py``` file the app ```"oauth2_provider"```.
After try to migrate (no need to run ```makemigrations```) and you'll get the exception shown above.

I'm running the migrations against a brand new DB, other models with the onetoonefield failed similarly (but the workaround mentioned in the start worked).
Djongo version is newest (1.2.30) and mongo version is 3.4.10. Django is at 2.0

Any thoughts about the cause and/or about a (hopefully) quick fix?
Thanks!

**Comment by fazilbinzaid** [comment]
I'm too facing the same issue, migrating after defining a OneToOneField. The above workaround is really helpful, too. Thanks @ronmorannielsen for that.
