### ISSUE TITLE
Alter query with Unique Constrain fails with Djongo

### ISSUE THREAD

**Issue by shimulch** [nesdis/djongo#188]
#### One line description of the issue
Alter query with Unique Constrain fails with Djongo.

#### Python script

<The complete python script used to produce the issue.>

```python
# Generated by Django 2.0.7 on 2018-07-28 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dit_email_addon', '0002_emailprofile_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailprofile',
            name='code',
            field=models.SlugField(default=None, unique=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='code',
            field=models.SlugField(default=None, unique=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='body',
            field=models.TextField(help_text='Use Django Templating Syntax here. From loop to condition all are supported.'),
        ),
    ]
```

#### Traceback
Operations to perform:
  Apply all migrations: dit_common_core
Running migrations:
  Applying dit_common_core.0001_initial... OK
(johukum)➜  johukum git:(master) ✗ python manage.py migrate dit_email_addon
Operations to perform:
  Apply all migrations: dit_email_addon
Running migrations:
  Applying dit_email_addon.0001_initial... OK
  Applying dit_email_addon.0002_emailprofile_is_default... OK
  Applying dit_email_addon.0003_auto_20180728_0551...Traceback (most recent call last):
  File "/home/shimul/Projects/johukum/.venv/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 763, in parse
    return handler(self, statement)
  File "/home/shimul/Projects/johukum/.venv/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 791, in _alter
    self._query.execute()
  File "/home/shimul/Projects/johukum/.venv/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 643, in _unique
    self.field_dir,
AttributeError: 'AlterQuery' object has no attribute 'field_dir'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/shimul/Projects/johukum/.venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/shimul/Projects/johukum/.venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/shimul/Projects/johukum/.venv/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/shimul/Projects/johukum/.venv/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/home/shimul/Projects/johukum/.venv/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/shimul/Projects/johukum/.venv/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 203, in handle
    fake_initial=fake_initial,
  File "/home/shimul/Projects/johukum/.venv/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/shimul/Projects/johukum/.venv/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/shimul/Projects/johukum/.venv/lib/python3.6/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/shimul/Projects/johukum/.venv/lib/python3.6/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/shimul/Projects/johukum/.venv/lib/python3.6/site-packages/django/db/migrations/operations/fields.py", line 84, in database_forwards
    field,
  File "/home/shimul/Projects/johukum/.venv/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 435, in add_field
    self.execute(sql, params)
  File "/home/shimul/Projects/johukum/.venv/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 133, in execute
    cursor.execute(sql, params)
  File "/home/shimul/Projects/johukum/.venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/shimul/Projects/johukum/.venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/shimul/Projects/johukum/.venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/shimul/Projects/johukum/.venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/shimul/Projects/johukum/.venv/lib/python3.6/site-packages/djongo/cursor.py", line 53, in execute
    params)
  File "/home/shimul/Projects/johukum/.venv/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 700, in __init__
    self.parse()
  File "/home/shimul/Projects/johukum/.venv/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 783, in parse
    raise exe from e
djongo.sql2mongo.SQLDecodeError: FAILED SQL: ALTER TABLE "dit_email_addon_emailprofile" ADD COLUMN "code" string NOT NULL UNIQUE
Version: 1.2.30

**Comment by GliderDev** [comment]
any update on this? Getting the same error

**Comment by nesdis** [comment]
Fixed now!
