### ISSUE TITLE
Simple EmbeddedModelField and "isinstance() arg 2 must be a type or tuple of types"

### ISSUE THREAD

**Issue by jakubtalas** [nesdis/djongo#197]
Hi I have created just a very simple model I want to test, but it does not work for me with EmbeddedModelField... well, the document is saved correctly in Mongo, but attempts to read it bring following error. Am I missing something or is there some Djongo regression?

#### models.py

```python
class Wedding(models.Model):
    date = models.DateField()
    place = models.CharField(max_length=50)
    code = models.UUIDField(primary_key=False, default=uuid.uuid4, editable=False)
    budget = models.EmbeddedModelField(
        model_container='WeddingBudget',
        null=True,
    )
    objects = models.DjongoManager()

    def __str__(self):
        return 'Wedding %s at %s' % (self.date, self.place)

class WeddingBudget(models.Model):
    budget_ceremony_active = models.BooleanField()
    budget_ceremony_cost = models.FloatField()

    def __str__(self):
        return "budget test"

    class Meta:
        abstract = True

```

Then I am able to create instance in Mongo
```
{
    "_id" : ObjectId("5bd0ea59e9c241422082e813"),
    "id" : 47,
    "date" : ISODate("2019-01-22T00:00:00.000Z"),
    "place" : "place",
    "code" : LUUID("6abf7c8b-1d18-4a6d-af6a-48a28dbe4f0b"),
    "budget" : {
        "budget_ceremony_active" : false,
        "budget_ceremony_cost" : 1.0
    }
}
```
But trying to work with created data then fails. See output from Django shell:

#### Traceback
```python
>>> from frontend.models import *
>>> e = Wedding.objects.create(date="2019-01-22", place='place',budget=WeddingBudget(
...     budget_ceremony_active=False,
...     budget_ceremony_cost=1))
>>>
>>> e
<Wedding: Wedding 2019-01-22 at place>
>>> f=Wedding.objects.get(code="6abf7c8b-1d18-4a6d-af6a-48a28dbe4f0b")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/kuba_talas/sthblue_env/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/kuba_talas/sthblue_env/lib64/python3.6/site-packages/django/db/models/query.py", line 393, in get
    num = len(clone)
  File "/home/kuba_talas/sthblue_env/lib64/python3.6/site-packages/django/db/models/query.py", line 250, in __len__
    self._fetch_all()
  File "/home/kuba_talas/sthblue_env/lib64/python3.6/site-packages/django/db/models/query.py", line 1186, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/kuba_talas/sthblue_env/lib64/python3.6/site-packages/django/db/models/query.py", line 63, in __iter__
    for row in compiler.results_iter(results):
  File "/home/kuba_talas/sthblue_env/lib64/python3.6/site-packages/django/db/models/sql/compiler.py", line 1009, in apply_converters
    value = converter(value, expression, connection)
  File "/home/kuba_talas/sthblue_env/lib64/python3.6/site-packages/djongo/models/fields.py", line 503, in from_db_value
    return self.to_python(value)
  File "/home/kuba_talas/sthblue_env/lib64/python3.6/site-packages/djongo/models/fields.py", line 510, in to_python
    if value is None or isinstance(value, self.model_container):
TypeError: isinstance() arg 2 must be a type or tuple of types
>>>
```

**Comment by jakubtalas** [comment]
Helped removal of apostrophes when declaring the model_container.

**Comment by vikitripathi** [comment]
@jakubtalas  how did you fix the issue  ? getting the same error.

**Comment by vikitripathi** [comment]
Hi, 

I am getting similar issue. 

Django Version: | 2.1.8
TypeError
**isinstance() arg 2 must be a type or tuple of types**

Trying to read after inserting embedded document in mongo.

```
class TransactionsLocation(models.Model):
    address = models.CharField(max_length= 200)
    city = models.CharField(max_length= 100)
    state = models.CharField(max_length= 100)
    zipcode = models.CharField(max_length= 40)
    latitude = models.CharField(max_length= 100)
    longitude = models.CharField(max_length= 100)
    store_number = models.CharField(max_length= 100)

    def __str__(self):
        return self.address

    class Meta:
        abstract = True
```

```
class PlaidTransaction(models.Model):
    account_id = models.CharField(max_length=500)
    amount = models.IntegerField(blank=True, null=True)
    category_id = models.CharField(max_length=100)
    date = models.CharField(max_length=50)
    iso_currency_code = models.CharField(max_length=20)
    name = models.CharField(max_length=200)
    #embedded documents
    location = models.EmbeddedModelField(
        model_container='TransactionsLocation'
    )
    objects = models.DjongoManager()

    def __str__(self):
        return "account_id = " + str(self.account_id) + " amount = " + self.amount + " date = " + self.date 

    class Meta:
        app_label = 'mongo'
```

```
class PlaidTransactionSerializer(serializers.ModelSerializer):
	location = serializers.SerializerMethodField()

	class Meta:
		model = PlaidTransaction
		fields = ('account_id', 'amount', 'category_id', 'name', 'location')

	def get_location(self, obj):
		return_data = None
		if type(obj.location) == list:
			embedded_list = []
			for item in obj.location:
				embedded_dict = item.__dict__
				for key in list(embedded_dict.keys()):
					if key.startswith('_'):
						embedded_dict.pop(key)
				embedded_list.append(embedded_dict)
			return_data = embedded_list
		else:
			embedded_dict = obj.location.__dict__
			for key in list(embedded_dict.keys()):
				if key.startswith('_'):
					embedded_dict.pop(key)
			return_data = embedded_dict
		return return_data
```

```
@api_view(['GET'])
def getTransactionsMongoData(request, pk, format=None):
    transactionsQuerySet = PlaidTransaction.objects.filter(name= "Madison Bicycle Shop")
    serializer = PlaidTransactionSerializer(transactionsQuerySet, many= True)

    return Response(serializer.data)
```
