### ISSUE TITLE
Migrating oauth2_provider app causes KeyError

### ISSUE THREAD

**Issue by smn-snkl** [nesdis/djongo#227]
#### One line description of the issue
When migrating the oauth2_provider app from the popular [django-oauth-toolkit](https://github.com/jazzband/django-oauth-toolkit), it seems like some constraint related issue causes a KeyError when applying migration [oauth2_provider.0004_auto_20160525_1623](https://github.com/jazzband/django-oauth-toolkit/blob/master/oauth2_provider/migrations/0004_auto_20160525_1623.py).

#### Python script
``` python manage.py migrate oauth2_provider```

#### Traceback
```
  Applying oauth2_provider.0001_initial... OK
  Applying oauth2_provider.0002_08_updates... OK
  Applying oauth2_provider.0003_auto_20160316_1503... OK
  Applying oauth2_provider.0004_auto_20160525_1623...Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 203, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/operations/fields.py", line 216, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 523, in alter_field
    old_db_params, new_db_params, strict)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 585, in _alter_field
    index_names = self._constraint_names(model, [old_field.column], index=True, type_=Index.suffix)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 1043, in _constraint_names
    if type_ is not None and infodict['type'] != type_:
KeyError: 'type'
```

Looking for any ideas how to work around this issue ...

**Comment by vaishnavmhetre** [comment]
Facing the same problem. Need an urgent solution. Working over a college project. Dev please respond asap.

**Comment by AcckiyGerman** [comment]
I have the same problem, but with "mysql-connector-python", not "djongo", so I suppose the problem could be in oauth2_provider, not the database connector.

**Comment by vaishnavmhetre** [comment]
> I have the same problem, but with **"mysql-connector-python"**, not **"djongo"**, so I suppose the problem could be in **oauth2_provider**, not the database connector.

1. Does this mean that Django uses base Mysql C libraries to connect to MySql db? Asking coz that's the reason mentioned in the description of **mysql-connector-python** on _pypi_.
2. But as _mysql-connector-python_ provides additional **MySql** support and _Djongo_ to **MongoDB**, and as the errors are thrown from _Django Core Management_ (approx. as of path in error stack), this might be the **Django core issue/feature** with new attachable libraries (MySql and/or MongoDB)
3. This error has been observed over other library usage too where oauth2-provider was not involved
    - Issue: [Removing an index from an IntegerField causes a KeyError exception - closed Bug (needsinfo)](https://code.djangoproject.com/ticket/28684)

Hence I think, this is an **issue/feature** in terms of _Django Core Handling_ and **not** _oauth2-provider_ package.

**Comment by AcckiyGerman** [comment]
> Does this mean that Django uses base Mysql C libraries to connect to MySql db? 

Django itself does not use C libs, but Django can use different drivers to connect to MySQL. **[mysql-connector-python](https://pypi.org/project/mysql-connector-python/)** is one of those drivers which:
  > MySQL driver written in Python which **does not depend on MySQL C client libraries** and implements the DB API v2.0 specification (PEP-249).

But you @vaishnavmhetre  gave me an idea to test other MySQL drivers for Django, so I've tried [mysqlclient](https://pypi.org/project/mysqlclient/) (which, btw, is using C libs):
```python
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        ...
```
and Voi la :smile::
```
Running migrations:
  Applying oauth2_provider.0001_initial... OK
  Applying oauth2_provider.0002_08_updates... OK
  Applying oauth2_provider.0003_auto_20160316_1503... OK
  Applying oauth2_provider.0004_auto_20160525_1623... OK
  Applying oauth2_provider.0005_auto_20170514_1141... OK
  Applying oauth2_provider.0006_auto_20171214_2232... OK
```
## Conclusions:
- Bug is probably not related to any C-libs
- Bug could be related to some **Django core issue/feature**
- Bug shows with **mysql-connector-python** to MySQL v5.7
- Bug shows with **Djongo** to MongoDB
- Bug not shows with **[mysqlclient](https://pypi.org/project/mysqlclient/)** to MySQL v5.7

## Bug Reproduce steps:
- start a new Django project
- set a DB connection via **mysql-connector-python** or **Djongo**
- `pip install django-oauth-toolkit` 
- add `'oauth2_provider'` to the `settings.py/INSTALLED_APPS` list
- run `python migrate.py`

*bug could triggers with other django models, not only **oauth2_provider**

## Bug Workaround 
Use **[mysqlclient](https://pypi.org/project/mysqlclient/)** to MySQL v5.7
@smn-snkl

**Comment by MMohamad70** [comment]
I have the same problem when using djongo, Is there any solution?

**Comment by amitsarwara** [comment]
@MMohamad70 , @smn-snkl , @vaishnavmhetre , @AcckiyGerman 

I am stuck on same issue, i have to use mongo itself, please let me know if any of you guys found any solution for this.

**Comment by iserranoe** [comment]
Any news about this problem?

**Comment by iserranoe** [comment]
Ok, I found a temporary solution and it is not always working... Please, let me know if it is working for you or I was just lucky...
- Copy the oauth2-provider site-packages to your project folder.
- Edit settings.py and add:
  OAUTH2_PROVIDER_APPLICATION_MODEL = 'oauth2_provider.Application'
  OAUTH2_PROVIDER_REFRESH_TOKEN_MODEL = 'oauth2_provider.RefreshToken'
  OAUTH2_PROVIDER_ACCESS_TOKEN_MODEL = 'oauth2_provider.AccessToken'  
- Delete all migrations from oauth2-provider/migrations/ but  __init__
- Create a new migrations file: python manage.py makemigrations oauth2_provider
- Edit oauth2-provider/migrations/0001_initial.py and comment the following lines, which are the ones causing problems:
```
        # migrations.AddField(
        #     model_name='accesstoken',
        #     name='application',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        # ),
        # migrations.AddField(
        #     model_name='accesstoken',
        #     name='source_refresh_token',
        #     field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refreshed_access_token', to=settings.OAUTH2_PROVIDER_REFRESH_TOKEN_MODEL),
        # ),
        # migrations.AddField(
        #     model_name='accesstoken',
        #     name='user',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oauth2_provider_accesstoken', to=settings.AUTH_USER_MODEL),
        # ),
```
- Install django version 2.1.8: pip install django=2.1.8, because newest versions cause problems with sql (https://github.com/nesdis/djongo/issues/254)
- Apply all migrations: python manage.py migrate
- Runserver and it works, more or less... I had some problems with the refresh_token but the rest is working fine.

**Comment by horiyomi** [comment]
Is there any a solution for djongo, i'm having the same issue.
