### ISSUE TITLE
count sql is very slow, using mongo 3.6, with 2.5m records

### ISSUE THREAD

**Issue by radzhome** [nesdis/djongo#233]
#### Python script

I will produce a mini project. When I go to my content model in admin which has 2.6m docs, it hangs and never returns. If I trunk the collection down to say 100k records, it works again.

This operation via mongo client seems to return quickly:

`db.getCollection('content').count()` I get 2492309. so I suspect that the query conversion is doing something funky and reading every single doc in the collection to get len/count.

#### Traceback

I only see  sql_command: SELECT COUNT(*) AS "__count" FROM "content"

and it hangs, will never return, I have about 2.5m docs in content collection. I'll see if I can reproduce using a mini project.

**Comment by thestick613** [comment]
Enable performance logging in mongo and try to figure out what query is being run?
https://docs.mongodb.com/manual/reference/method/db.setLogLevel/

**Comment by radzhome** [comment]
You will update that shortly, just trying to get output from `db.currentOp()` when the query is run.

**Comment by radzhome** [comment]
Sorry bit behind with this. I'm going to create a small project that reproduces the issue.

**Comment by radzhome** [comment]
So here is the queries I see
```
DEBUG 2019-02-01 15:30:15,371 query 26249 123145518166016 DEBUG params: ()
DEBUG 2019-02-01 15:30:15,371 query 26249 123145518166016 DEBUG
 sql_command: SELECT COUNT(*) AS "__count" FROM "content"
DEBUG 2019-02-01 15:30:17,431 query 26249 123145518166016 DEBUG Aggregation query: [{'$group': {'_id': 0, '_count': {'$sum': 1}}}]
DEBUG 2019-02-01 15:30:17,432 query 26249 123145518166016 DEBUG params: ()
DEBUG 2019-02-01 15:30:17,432 query 26249 123145518166016 DEBUG
 sql_command: SELECT COUNT(*) AS "__count" FROM "content"
DEBUG 2019-02-01 15:30:19,384 query 26249 123145518166016 DEBUG Aggregation query: [{'$group': {'_id': 0, '_count': {'$sum': 1}}}]
DEBUG 2019-02-01 15:30:19,387 query 26249 123145518166016 DEBUG params: ()
DEBUG 2019-02-01 15:30:19,387 query 26249 123145518166016 DEBUG
 sql_command: SELECT "content"."_id", "content"."titles", "content"."credits", "content"."taxonomies", "content"."content_elements", "content"."metadata", "content"."featured_media", "content"."client_id", "content"."license_id", "content"."origin_id", "content"."origin_url", "content"."origin_url_path", "content"."origin_cms", "content"."origin_slug", "content"."type", "content"."status", "content"."version", "content"."order", "content"."excerpt", "content"."global_slug", "content"."nlp", "content"."created_on", "content"."modified_on", "content"."published_on", "content"."imported_on" FROM "content" ORDER BY "content"."_id" DESC  LIMIT 100
DEBUG 2019-02-01 15:30:19,401 query 26249 123145518166016 DEBUG Find query: {'projection': ['_id', 'titles', 'credits', 'taxonomies', 'content_elements', 'metadata', 'featured_media', 'client_id', 'license_id', 'origin_id', 'origin_url', 'origin_url_path', 'origin_cms', 'origin_slug', 'type', 'status', 'version', 'order', 'excerpt', 'global_slug', 'nlp', 'created_on', 'modified_on', 'published_on', 'imported_on'], 'limit': 100, 'sort': [('_id', -1)]}
```

And here is the project that will help reproduce it

https://github.com/radzhome/djongo-count-bug

this project once you generate more data, the page starts to slow down from initially 800ms load down to about 4-5s when its at 2.5m

The real data, each doc is much bigger so will try with bigger docs next. It takes 30+ seconds to do those queries when the data is bigger in our dev env.

**Comment by radzhome** [comment]
So on the larger doc size, it seems to load very slowly, perhaps the mongo instance is less powerful and the docs are bigger.. I haven't loaded large docs yet into my local to try this. It eventually loads but throws JSON decode errors later


```
DEBUG 2019-02-01 15:55:56,527 query 27064 123145434890240 DEBUG params: ()
DEBUG 2019-02-01 15:55:56,527 query 27064 123145434890240 DEBUG
 sql_command: SELECT COUNT(*) AS "__count" FROM "content"

DEBUG 2019-02-01 15:59:45,137 query 27064 123145434890240 DEBUG Aggregation query: [{'$count': '_count'}]
DEBUG 2019-02-01 15:59:45,137 query 27064 123145434890240 DEBUG params: ()
DEBUG 2019-02-01 15:59:45,137 query 27064 123145434890240 DEBUG
 sql_command: SELECT COUNT(*) AS "__count" FROM "content"

DEBUG 2019-02-01 16:03:36,540 query 27064 123145434890240 DEBUG Aggregation query: [{'$count': '_count'}]
DEBUG 2019-02-01 16:03:36,542 query 27064 123145434890240 DEBUG params: ()
DEBUG 2019-02-01 16:03:36,543 query 27064 123145434890240 DEBUG
 sql_command: SELECT "content"."_id", "content"."titles", "content"."credits", "content"."taxonomies", "content"."content_elements", "content"."metadata", "content"."featured_media", "content"."client_id", "content"."origin_id", "content"."origin_url", "content"."origin_url_path", "content"."origin_cms", "content"."origin_slug", "content"."type", "content"."status", "content"."version", "content"."order", "content"."excerpt", "content"."global_slug", "content"."nlp", "content"."created_on", "content"."modified_on", "content"."published_on", "content"."imported_on" FROM "content" ORDER BY "content"."_id" DESC  LIMIT 100
DEBUG 2019-02-01 16:03:36,550 query 27064 123145434890240 DEBUG Find query: {'projection': ['_id', 'titles', 'credits', 'taxonomies', 'content_elements', 'metadata', 'featured_media', 'client_id', 'origin_id', 'origin_url', 'origin_url_path', 'origin_cms', 'origin_slug', 'type', 'status', 'version', 'order', 'excerpt', 'global_slug', 'nlp', 'created_on', 'modified_on', 'published_on', 'imported_on'], 'limit': 100, 'sort': [('_id', -1)]}
DEBUG 2019-02-01 16:03:39,454 query 27064 123145434890240 DEBUG params: ()
DEBUG 2019-02-01 16:03:39,454 query 27064 123145434890240 DEBUG
 sql_command: SELECT "content"."_id", "content"."titles", "content"."credits", "content"."taxonomies", "content"."content_elements", "content"."metadata", "content"."featured_media", "content"."client_id", "content"."origin_id", "content"."origin_url", "content"."origin_url_path", "content"."origin_cms", "content"."origin_slug", "content"."type", "content"."status", "content"."version", "content"."order", "content"."excerpt", "content"."global_slug", "content"."nlp", "content"."created_on", "content"."modified_on", "content"."published_on", "content"."imported_on" FROM "content" ORDER BY "content"."_id" DESC  LIMIT 21
DEBUG 2019-02-01 16:03:39,462 query 27064 123145434890240 DEBUG Find query: {'projection': ['_id', 'titles', 'credits', 'taxonomies', 'content_elements', 'metadata', 'featured_media', 'client_id', 'origin_id', 'origin_url', 'origin_url_path', 'origin_cms', 'origin_slug', 'type', 'status', 'version', 'order', 'excerpt', 'global_slug', 'nlp', 'created_on', 'modified_on', 'published_on', 'imported_on'], 'limit': 21, 'sort': [('_id', -1)]}
DEBUG 2019-02-01 16:03:40,096 query 27064 123145434890240 DEBUG params: ()
DEBUG 2019-02-01 16:03:40,096 query 27064 123145434890240 DEBUG
 sql_command: SELECT "content"."_id", "content"."titles", "content"."credits", "content"."taxonomies", "content"."content_elements", "content"."metadata", "content"."featured_media", "content"."client_id", "content"."origin_id", "content"."origin_url", "content"."origin_url_path", "content"."origin_cms", "content"."origin_slug", "content"."type", "content"."status", "content"."version", "content"."order", "content"."excerpt", "content"."global_slug", "content"."nlp", "content"."created_on", "content"."modified_on", "content"."published_on", "content"."imported_on" FROM "content" ORDER BY "content"."_id" DESC  LIMIT 21
DEBUG 2019-02-01 16:03:40,104 query 27064 123145434890240 DEBUG Find query: {'projection': ['_id', 'titles', 'credits', 'taxonomies', 'content_elements', 'metadata', 'featured_media', 'client_id', 'origin_id', 'origin_url', 'origin_url_path', 'origin_cms', 'origin_slug', 'type', 'status', 'version', 'order', 'excerpt', 'global_slug', 'nlp', 'created_on', 'modified_on', 'published_on', 'imported_on'], 'limit': 21, 'sort': [('_id', -1)]}
DEBUG 2019-02-01 16:03:40,567 query 27064 123145434890240 DEBUG params: ()
DEBUG 2019-02-01 16:03:40,567 query 27064 123145434890240 DEBUG
 sql_command: SELECT "content"."_id", "content"."titles", "content"."credits", "content"."taxonomies", "content"."content_elements", "content"."metadata", "content"."featured_media", "content"."client_id", "content"."origin_id", "content"."origin_url", "content"."origin_url_path", "content"."origin_cms", "content"."origin_slug", "content"."type", "content"."status", "content"."version", "content"."order", "content"."excerpt", "content"."global_slug", "content"."nlp", "content"."created_on", "content"."modified_on", "content"."published_on", "content"."imported_on" FROM "content" ORDER BY "content"."_id" DESC  LIMIT 21
DEBUG 2019-02-01 16:03:40,575 query 27064 123145434890240 DEBUG Find query: {'projection': ['_id', 'titles', 'credits', 'taxonomies', 'content_elements', 'metadata', 'featured_media', 'client_id', 'origin_id', 'origin_url', 'origin_url_path', 'origin_cms', 'origin_slug', 'type', 'status', 'version', 'order', 'excerpt', 'global_slug', 'nlp', 'created_on', 'modified_on', 'published_on', 'imported_on'], 'limit': 21, 'sort': [('_id', -1)]}
ERROR 2019-02-01 16:03:40,969 log 27064 123145434890240 ERROR Internal Server Error: /admin/content_app/content/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/jsonfield/fields.py", line 83, in pre_init
    return json.loads(value, **self.load_kwargs)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 2 (char 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rad/Library/Python/3.7/lib/python/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/rad/Library/Python/3.7/lib/python/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/rad/Library/Python/3.7/lib/python/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/rad/Library/Python/3.7/lib/python/site-packages/django/contrib/admin/options.py", line 604, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/rad/Library/Python/3.7/lib/python/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/rad/Library/Python/3.7/lib/python/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/rad/Library/Python/3.7/lib/python/site-packages/django/contrib/admin/sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "/Users/rad/Library/Python/3.7/lib/python/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/rad/Library/Python/3.7/lib/python/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/rad/Library/Python/3.7/lib/python/site-packages/django/contrib/admin/options.py", line 1793, in changelist_view
    'selection_note': _('0 of %(cnt)s selected') % {'cnt': len(cl.result_list)},
  File "/Users/rad/Library/Python/3.7/lib/python/site-packages/django/db/models/query.py", line 250, in __len__
    self._fetch_all()
  File "/Users/rad/Library/Python/3.7/lib/python/site-packages/django/db/models/query.py", line 1186, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/rad/Library/Python/3.7/lib/python/site-packages/django/db/models/query.py", line 64, in __iter__
    obj = model_cls.from_db(db, init_list, row[model_fields_start:model_fields_end])
  File "/Users/rad/Library/Python/3.7/lib/python/site-packages/django/db/models/base.py", line 497, in from_db
    new = cls(*values)
  File "/Users/rad/Library/Python/3.7/lib/python/site-packages/django/db/models/base.py", line 414, in __init__
    _setattr(self, field.attname, val)
  File "/usr/local/lib/python3.7/site-packages/jsonfield/subclassing.py", line 43, in __set__
    obj.__dict__[self.field.name] = self.field.pre_init(value, obj)
  File "/usr/local/lib/python3.7/site-packages/jsonfield/fields.py", line 85, in pre_init
    raise ValidationError(_("Enter valid JSON"))
django.core.exceptions.ValidationError: ['Enter valid JSON']
ERROR 2019-02-01 16:03:40,972 basehttp 27064 123145434890240 ERROR "GET /admin/content_app/content/ HTTP/1.1" 500 159842
```

**Comment by radzhome** [comment]
So the issue is with this query `db.getCollection('content').aggregate( [{'$count': '_count'}] )` .. very slow vs just doing a `count()`

**Comment by thestick613** [comment]
Do a `db.getCollection('content').aggregate( [{'$count': '_count'}], {explain: true})`, you'll see a 

```
"winningPlan" : {
            "stage" : "COLLSCAN",
            "direction" : "forward"
},
```
Which means that the count will always be slow. You could probably extend the `Manager` for that `Model` and override the count. You could also open a ticket with mongodb and ask them why this simple indexable query isn't using an index.

**Comment by radzhome** [comment]
If there was a way to just realize the query is a count though in djongo i.e. `if pipeline == [{'$count': '_count'}]:`  in `_get_cursor` then you could just return `self.db_ref[self.left_table].count()` but ofcourse this is no longer a cursor but an int which causes issues. You think there is a clean way to do it in djongo?

**Comment by radzhome** [comment]
I wonder if there is a way to force it to use an index, https://docs.mongodb.com/manual/reference/command/count/

When you run just count() on a collection which is the case here, the query is fast

**Comment by radzhome** [comment]
This fixes it, you want me to create a pr? 

```
    def _get_cursor(self):
        if self._needs_aggregation():
            pipeline = self._make_pipeline()
            if pipeline == [{'$count': '_count'}]:  # Only thing we are doing is count .. lets speed it up
                cnt = self.db_ref[self.left_table].count()
                cur = self.db_ref[self.left_table].aggregate([{"$addFields": {"_count": cnt}}, {"$limit": 1},
                                                              {'$project': {'_id': 0,  '_count': 1}}])
            else:
                logger.debug(f'Aggregation query start: {pipeline}')
                logger.debug("table is {}".format(self.left_table))
                import time; s=time.time()
                cur = self.db_ref[self.left_table].aggregate(pipeline)
                logger.debug('Aggregation query: {} in time {}'.format(pipeline, time.time() -s))
        else:
            kwargs = {}
            if self.where:
                kwargs.update(self.where.to_mongo())

            if self.selected_columns:
                kwargs.update(self.selected_columns.to_mongo())

            if self.limit:
                kwargs.update(self.limit.to_mongo())

            if self.order:
                kwargs.update(self.order.to_mongo())
            
            if self.offset:
                kwargs.update(self.offset.to_mongo())

            import time; s = time.time()
            logger.debug(f'Find query: {kwargs}')
            cur = self.db_ref[self.left_table].find(**kwargs)
            logger.debug('Find query: {} in time {}'.format(kwargs, time.time() - s))

        return cur
```

**Comment by radzhome** [comment]
I added it here to my fork - https://github.com/radzhome/djongo/commit/eade8e6b41dea1f2f04282e3a5a08d4c99b2ce0c

**Comment by radzhome** [comment]
Perhaps, but there is a way around it now.

**Comment by ryanm-pm** [comment]
MongoDB does use indexing on aggregations when you use an aggregation step that supports indexing at the beginning of the pipeline (e.g. `$match`). The problem here is that the aggregation step `{ $count: '_count' }` is actually a helper method that expands to 
```
[
    {
        $group: {
            _id: null,
            _count: { $sum: 1 }
        }
    },
    { $project: { _id: 0 } }
]
```
(https://docs.mongodb.com/manual/reference/operator/aggregation/count/)

Which will run through all documents in the collection if you don't first filter the results. The use of this step is for counting results of an aggregation, not a full collection. Using `self.db_ref[self.left_table].count()` actually queries the collection metadata to get the current count of documents.

**Comment by thestick613** [comment]
This is how i fixed this:

```
from django.db.models.query import QuerySet
from django.db import connections

class CountQuerySet(QuerySet):
    def count(self):
        is_mongo = 'djongo' in connections[self.db].Database.__name__
        query = self.query

        if (is_mongo and not query.where and query.high_mark is None and query.low_mark == 0 and
                not query.select and
                not query.group_by and
                not query.distinct):
            return self.model.objects.mongo_estimated_document_count()

        else:
            return super(CountQuerySet, self).count()

# [...]

@admin.register(Books)
class BooksAdmin(admin.ModelAdmin):
    # [...]
    def get_queryset(self, request):
        return CountQuerySet(model=self.model)
```
