### ISSUE TITLE
Cannot fetch data from database when using ObjectID

### ISSUE THREAD

**Issue by Sehalsein** [nesdis/djongo#240]
Not able to fetch data from the database when using  _id as ObjectIDFeild.

```
class Songs(models.Model):
    _id = models.ObjectIdField()
    title = models.CharField(max_length=255, null=False)
    artist = models.CharField(max_length=255, null=False)

    def getAllSongs(self):
        return Songs.objects.all()

    def insertSong(self, newSong):
        song = Songs(
            title=newSong.title,
            artist=newSong.artist,
        )
        song.save()
        return song

class SongsSerializer(serializers.ModelSerializer):
    class Meta:
        model = Songs
        fields = '__all__'
```

#### Traceback
```
Traceback (most recent call last):
  File "/Users/sehalsein/Internship/Atria-Env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/sehalsein/Internship/Atria-Env/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/sehalsein/Internship/Atria-Env/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/sehalsein/Internship/Atria-Env/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/sehalsein/Internship/Atria-Env/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/sehalsein/Internship/Atria-Env/lib/python3.7/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/sehalsein/Internship/Atria-Env/lib/python3.7/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/sehalsein/Internship/Atria-Env/lib/python3.7/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/sehalsein/Internship/Atria-Env/AtriaProject/AtriaApp/views/test_view.py", line 13, in get
    data=SongsSerializer(songs, many=True).data,
  File "/Users/sehalsein/Internship/Atria-Env/lib/python3.7/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super(ListSerializer, self).data
  File "/Users/sehalsein/Internship/Atria-Env/lib/python3.7/site-packages/rest_framework/serializers.py", line 262, in data
    self._data = self.to_representation(self.instance)
  File "/Users/sehalsein/Internship/Atria-Env/lib/python3.7/site-packages/rest_framework/serializers.py", line 686, in to_representation
    self.child.to_representation(item) for item in iterable
  File "/Users/sehalsein/Internship/Atria-Env/lib/python3.7/site-packages/rest_framework/serializers.py", line 686, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/Users/sehalsein/Internship/Atria-Env/lib/python3.7/site-packages/rest_framework/serializers.py", line 530, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/Users/sehalsein/Internship/Atria-Env/lib/python3.7/site-packages/rest_framework/fields.py", line 961, in to_representation
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'ObjectId'

```
<img width="751" alt="screenshot 2019-03-06 at 3 13 02 pm" src="https://user-images.githubusercontent.com/8364374/53871529-6e978400-4022-11e9-9a51-95cc09e95489.png">

**Comment by Balagii** [comment]
I had the same error message on GET and POST from the rest framework's Browsable API pages, while the Django contrib.admin section worked fine. What ended up solving the issue was fixing the serializer class by leaving out the '_id' from the fields list, i.e

```python
class SongsSerializer(serializers.ModelSerializer):
    class Meta:
        model = Songs
        fields = ('title', 'artist')
```

I didn't even need to write custom get and insert logic. Used a simple ModelViewSet-derived view class.

**Comment by SomeoneInParticular** [comment]
The issue you are running into has the same root cause as #298; hopefully the solutions mentioned there should help!
