### ISSUE TITLE
'AlterQuery' object has no attribute 'field_dir'

### ISSUE THREAD

**Issue by yingzongliang** [nesdis/djongo#249]
#### One line description of the issue
when we used the djongo==1.2.32(May,17, 2019),  a error appeared as follows.
but once we degraded the djongo to the version of 1.2.23, (May, 18, 2018), the error disappeared.

#### Python script

<The complete python script used to produce the issue.>

python manage.py migrate.

#### Traceback
<The complete stack trace of the error.>

(base)>python manage.py migrate
Operations to perform:
  Apply all migrations: SitesApp, admin, auth, contenttypes, sessions, xadmin
Running migrations:
  Applying SitesApp.0001_initial...Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\djongo\sql2mongo\query.py", line 806, in parse
    return handler(self, statement)
  File "D:\Anaconda3\lib\site-packages\djongo\sql2mongo\query.py", line 834, in _alter
    self._query.execute()
  File "D:\Anaconda3\lib\site-packages\djongo\sql2mongo\query.py", line 686, in _unique
    self.field_dir,
AttributeError: 'AlterQuery' object has no attribute 'field_dir'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "D:\Anaconda3\lib\site-packages\django\core\management\__init__.py", line 381, in ex
ecute_from_command_line
    utility.execute()
  File "D:\Anaconda3\lib\site-packages\django\core\management\__init__.py", line 375, in ex
ecute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "D:\Anaconda3\lib\site-packages\django\core\management\base.py", line 316, in run_fr
om_argv
    self.execute(*args, **cmd_options)
  File "D:\Anaconda3\lib\site-packages\django\core\management\base.py", line 353, in execut
e
    output = self.handle(*args, **options)
  File "D:\Anaconda3\lib\site-packages\django\core\management\base.py", line 83, in wrapped

    res = handle_func(*args, **kwargs)
  File "D:\Anaconda3\lib\site-packages\django\core\management\commands\migrate.py", line 20
3, in handle
    fake_initial=fake_initial,
  File "D:\Anaconda3\lib\site-packages\django\db\migrations\executor.py", line 117, in migr
ate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake
_initial)
  File "D:\Anaconda3\lib\site-packages\django\db\migrations\executor.py", line 147, in _mig
rate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "D:\Anaconda3\lib\site-packages\django\db\migrations\executor.py", line 244, in appl
y_migration
    state = migration.apply(state, schema_editor)
  File "D:\Anaconda3\lib\site-packages\django\db\migrations\migration.py", line 124, in app
ly
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "D:\Anaconda3\lib\site-packages\django\db\migrations\operations\fields.py", line 84,
 in database_forwards
    field,
  File "D:\Anaconda3\lib\site-packages\django\db\backends\base\schema.py", line 435, in add
_field
    self.execute(sql, params)
  File "D:\Anaconda3\lib\site-packages\django\db\backends\base\schema.py", line 133, in exe
cute
    cursor.execute(sql, params)
  File "D:\Anaconda3\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "D:\Anaconda3\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\Anaconda3\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_w
ith_wrappers
    return executor(sql, params, many, context)
  File "D:\Anaconda3\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Anaconda3\lib\site-packages\djongo\cursor.py", line 53, in execute
    params)
  File "D:\Anaconda3\lib\site-packages\djongo\sql2mongo\query.py", line 743, in __init__
    self.parse()
  File "D:\Anaconda3\lib\site-packages\djongo\sql2mongo\query.py", line 826, in parse
    raise exe from e
djongo.sql2mongo.SQLDecodeError: FAILED SQL: ALTER TABLE "voteRecords" ADD COLUMN "vTypeId_
id" int32 NULL UNIQUE
Version: 1.2.32

**Comment by swapnilaryan** [comment]
+1
