### ISSUE TITLE
Cannot open the create user page

### ISSUE THREAD

**Issue by ZerNico** [nesdis/djongo#254]
#### Cannot open the create user page

When trying to open the page to create a new page in django admin it errors. The same when using reverse.

```python
url = reverse('admin:core_user_add')
res = self.client.get(url)

```

#### Traceback
Traceback (most recent call last):
  File "C:\Users\nicof\.virtualenvs\potato_django-G91PIBzp\lib\site-packages\djongo\sql2mongo\query.py", line 799, in parse
    handler = self.FUNC_MAP[sm_type]
KeyError: 'UNKNOWN'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nicof\Desktop\python\potato_django\core\tests\test_admin.py", line 40, in test_create_user_page
    res = self.client.get(url)
  File "C:\Users\nicof\.virtualenvs\potato_django-G91PIBzp\lib\site-packages\django\test\client.py", line 535, in get
    response = super().get(path, data=data, secure=secure, **extra)
  File "C:\Users\nicof\.virtualenvs\potato_django-G91PIBzp\lib\site-packages\django\test\client.py", line 347, in get
    **extra,
  File "C:\Users\nicof\.virtualenvs\potato_django-G91PIBzp\lib\site-packages\django\test\client.py", line 422, in generic
    return self.request(**r)
  File "C:\Users\nicof\.virtualenvs\potato_django-G91PIBzp\lib\site-packages\django\test\client.py", line 503, in request
    raise exc_value
  File "C:\Users\nicof\.virtualenvs\potato_django-G91PIBzp\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\nicof\.virtualenvs\potato_django-G91PIBzp\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\nicof\.virtualenvs\potato_django-G91PIBzp\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\nicof\.virtualenvs\potato_django-G91PIBzp\lib\site-packages\django\contrib\admin\options.py", line 606, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\nicof\.virtualenvs\potato_django-G91PIBzp\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\nicof\.virtualenvs\potato_django-G91PIBzp\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\nicof\.virtualenvs\potato_django-G91PIBzp\lib\site-packages\django\contrib\admin\sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\nicof\.virtualenvs\potato_django-G91PIBzp\lib\site-packages\django\utils\decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\nicof\.virtualenvs\potato_django-G91PIBzp\lib\site-packages\django\views\decorators\debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "C:\Users\nicof\.virtualenvs\potato_django-G91PIBzp\lib\site-packages\django\utils\decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\nicof\.virtualenvs\potato_django-G91PIBzp\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\nicof\.virtualenvs\potato_django-G91PIBzp\lib\site-packages\django\contrib\auth\admin.py", line 99, in add_view
    return self._add_view(request, form_url, extra_context)
  File "C:\Users\nicof\.virtualenvs\potato_django-G91PIBzp\lib\site-packages\django\contrib\auth\admin.py", line 126, in _add_view
    return super().add_view(request, form_url, extra_context)
  File "C:\Users\nicof\.virtualenvs\potato_django-G91PIBzp\lib\site-packages\django\contrib\admin\options.py", line 1634, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "C:\Users\nicof\.virtualenvs\potato_django-G91PIBzp\lib\site-packages\django\utils\decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\nicof\.virtualenvs\potato_django-G91PIBzp\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\nicof\.virtualenvs\potato_django-G91PIBzp\lib\site-packages\django\contrib\admin\options.py", line 1521, in changeform_view
    with transaction.atomic(using=router.db_for_write(self.model)):
  File "C:\Users\nicof\.virtualenvs\potato_django-G91PIBzp\lib\site-packages\django\db\transaction.py", line 196, in __enter__
    sid = connection.savepoint()
  File "C:\Users\nicof\.virtualenvs\potato_django-G91PIBzp\lib\site-packages\django\db\backends\base\base.py", line 332, in savepoint
    self._savepoint(sid)
  File "C:\Users\nicof\.virtualenvs\potato_django-G91PIBzp\lib\site-packages\django\db\backends\base\base.py", line 300, in _savepoint
    cursor.execute(self.ops.savepoint_create_sql(sid))
  File "C:\Users\nicof\.virtualenvs\potato_django-G91PIBzp\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\nicof\.virtualenvs\potato_django-G91PIBzp\lib\site-packages\django\db\backends\utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\nicof\.virtualenvs\potato_django-G91PIBzp\lib\site-packages\django\db\backends\utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "C:\Users\nicof\.virtualenvs\potato_django-G91PIBzp\lib\site-packages\djongo\cursor.py", line 53, in execute
    params)
  File "C:\Users\nicof\.virtualenvs\potato_django-G91PIBzp\lib\site-packages\djongo\sql2mongo\query.py", line 743, in __init__
    self.parse()
  File "C:\Users\nicof\.virtualenvs\potato_django-G91PIBzp\lib\site-packages\djongo\sql2mongo\query.py", line 802, in parse
    raise NotImplementedError(f'{sm_type} command not implemented for SQL {self._sql}')
NotImplementedError: UNKNOWN command not implemented for SQL SAVEPOINT "s24980_x1"

**Comment by manish-chauhan** [comment]
@ZerNico  did you solved the error I am currently facing same problem

**Comment by ZerNico** [comment]
@manish-chauhan I downgraded to Django version 2.1.8

**Comment by manish-chauhan** [comment]
@ZerNico Is there any alternative did you found out the cause. I have been banging my head for the last few hours.

**Comment by ZerNico** [comment]
@manish-chauhan Nope sadly not 
downgrade in the meantime and wait for an update to djongo I guess

**Comment by manish-chauhan** [comment]
@ZerNico thanks for reply
