### ISSUE TITLE
Negating IN/NOT IN not supported

### ISSUE THREAD

**Issue by ayakut** [nesdis/djongo#26]
#### One line description of the issue
Hi guys,

I appreciate your supporting!

Yesterday, I'd cloned your project in its current state and, really, the issue with not implemented get_constraints() function is solved.
But... ))) There is a new one issue, now. It is the _"Negating IN/NOT IN not supported" exception_!

During debugging figured out that we receive this exception due to the following SQL:

**SELECT "frontend_module"."id", "frontend_module"."label", "frontend_module"."installed" FROM "frontend_module" WHERE NOT ("frontend_module"."label" IN (viewflow_frontend))**
(further it is processed as:
SELECT (1) AS "a" FROM "frontend_module" WHERE NOT ("frontend_module"."label" IN (%(0)s)) LIMIT 1
)
I thought, maybe we can replace the WHERE part to some like that:
**WHERE "frontend_module"."label" NOT IN (viewflow_frontend)**
and in the case, the Djongo able to convert such statement to the mongo's "$nin" operator.

What do you think? Please, advise me something...

#### Python script
```djongo/sql2mongo.py, row #747
...
   def negate(self):
        raise SQLDecodeError('Negating IN/NOT IN not supported')`
...

#### Traceback
HERE IS CONSOLE OUTPUT:

> "C:\Program Files\JetBrains\PyCharm 2017.2.3\bin\runnerw.exe" C:\Users\alexk\development\projects\python\venvs\fifa_mongo\Scripts\python.exe "C:\Program Files\JetBrains\PyCharm 2017.2.3\helpers\pydev\pydevd.py" --multiproc --qt-support=auto --client 127.0.0.1 --port 53765 --file C:/Users/alexk/development/projects/python/fifa_mongo/manage.py migrate
pydev debugger: process 4824 is connecting
Connected to pydev debugger (build 173.3727.137)
Operations to perform:
Apply all migrations: admin, auth, contenttypes, django_celery_results, flows, frontend, sessions, viewflow
Running migrations:
No migrations to apply.
Traceback (most recent call last):
File "C:\Program Files\JetBrains\PyCharm 2017.2.3\helpers\pydev\pydevd.py", line 1683, in 
main()
File "C:\Program Files\JetBrains\PyCharm 2017.2.3\helpers\pydev\pydevd.py", line 1677, in main
globals = debugger.run(setup['file'], None, None, is_module)
File "C:\Program Files\JetBrains\PyCharm 2017.2.3\helpers\pydev\pydevd.py", line 1087, in run
pydev_imports.execfile(file, globals, locals) # execute the script
File "C:\Program Files\JetBrains\PyCharm 2017.2.3\helpers\pydev_pydev_imps_pydev_execfile.py", line 18, in execfile
exec(compile(contents+"\n", file, 'exec'), glob, loc)
File "C:/Users/alexk/development/projects/python/fifa_mongo/manage.py", line 22, in 
execute_from_command_line(sys.argv)
File "C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\django\core\management_init_.py", line 364, in execute_from_command_line
utility.execute()
File "C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\django\core\management_init_.py", line 356, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File "C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
self.execute(*args, **cmd_options)
File "C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\django\core\management\base.py", line 330, in execute
output = self.handle(*args, **options)
File "C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\django\core\management\commands\migrate.py", line 227, in handle
self.verbosity, self.interactive, connection.alias, apps=post_migrate_apps, plan=plan,
File "C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\django\core\management\sql.py", line 53, in emit_post_migrate_signal
**kwargs
File "C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\django\dispatch\dispatcher.py", line 193, in send
for receiver in self._live_receivers(sender)
File "C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\django\dispatch\dispatcher.py", line 193, in 
for receiver in self._live_receivers(sender)
File "C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\material\frontend\apps.py", line 165, in update_modules
if stale_modules.exists():
File "C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\django\db\models\query.py", line 670, in exists
return self.query.has_results(using=self.db)
File "C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\django\db\models\sql\query.py", line 517, in has_results
return compiler.has_results()
File "C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\django\db\models\sql\compiler.py", line 853, in has_results
return bool(self.execute_sql(SINGLE))
File "C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\django\db\models\sql\compiler.py", line 894, in execute_sql
raise original_exception
File "C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\django\db\models\sql\compiler.py", line 884, in execute_sql
cursor.execute(sql, params)
File "C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\django\db\backends\utils.py", line 80, in execute
return super(CursorDebugWrapper, self).execute(sql, params)
File "C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\django\db\backends\utils.py", line 65, in execute
return self.cursor.execute(sql, params)
File "c:\users\alexk\development\projects\python\djongo\djongo\cursor.py", line 45, in execute
self.parse = Parse(self.client_conn, self.db_conn, sql, params)
File "c:\users\alexk\development\projects\python\djongo\djongo\sql2mongo.py", line 119, in init
self._parse()
File "c:\users\alexk\development\projects\python\djongo\djongo\sql2mongo.py", line 144, in _parse
return handler(self, statement)
File "c:\users\alexk\development\projects\python\djongo\djongo\sql2mongo.py", line 367, in _find
params=self._params
File "c:\users\alexk\development\projects\python\djongo\djongo\sql2mongo.py", line 889, in init
op.evaluate()
File "c:\users\alexk\development\projects\python\djongo\djongo\sql2mongo.py", line 995, in evaluate
op.evaluate()
File "c:\users\alexk\development\projects\python\djongo\djongo\sql2mongo.py", line 787, in evaluate
self.rhs.negate()
File "c:\users\alexk\development\projects\python\djongo\djongo\sql2mongo.py", line 1000, in negate
op.negate()
File "c:\users\alexk\development\projects\python\djongo\djongo\sql2mongo.py", line 747, in negate
raise SQLDecodeError('Negating IN/NOT IN not supported')
djongo.sql2mongo.SQLDecodeError: Negating IN/NOT IN not supported

**Comment by ayakut** [comment]
Hi guys,

Temporary I've solved the issue as follows:

```python: djongo/sql2mongo.py
...
class _InNotInOp(_Op):
    ...
    def negate(self):
        **# raise SQLDecodeError('Negating IN/NOT IN not supported')
        pass**
   ...
...
class InOp(_InNotInOp):
   ...
    def to_mongo(self):
        op = '$in'
        **if isinstance(self.token.parent, Token) and isinstance(self.token.parent, TokenList):
            for related_token in self.token.parent.tokens:
                if related_token is self:
                    break
                elif related_token.match(tokens.Keyword, 'NOT'):
                    op = '$nin'
                    break**
        return {self._field: {op: self._in}}
```

**Comment by nesdis** [comment]
SELECT "frontend_module"."id", "frontend_module"."label", "frontend_module"."installed" FROM "frontend_module" WHERE NOT ("frontend_module"."label" IN (viewflow_frontend))

Is this syntax being generated by Django? because as far as I know Django always gives queries in NOT IN format.. Is this a raw query you are making?

**Comment by ayakut** [comment]
Hi @nesdis ,

No, the SQL is not a raw query.
I suppose it had been generated by the [ViewFlow app](https://github.com/viewflow/viewflow)

**Comment by nesdis** [comment]
So I have made a change for this. You can clone a copy to check if it works

**Comment by ayakut** [comment]
Hi @nesdis ,

Thanks for the update and for the fix.
I've cloned this version and will check it.

**Comment by ayakut** [comment]
Hi @nesdis ,

I would like to update you, that your fix works for me.
Thank you!

**Comment by esiebomajeremiah** [comment]
@nesdis  this issue is closed but is there support for this yet? 
cause I still get **Negating IN/NOT IN not supported** when trying to use exclude or nagated Q objects
