### ISSUE TITLE
DictField/ListField with null=True raises an error

### ISSUE THREAD

**Issue by javinp** [nesdis/djongo#261]
Having a DictField/ListField with null=True it's not posible to create/update the model no setting the value.

The error looks to be in method get_db_prep_value of DictField and ListField, checking if the type of the value is correct.

```
def get_db_prep_value(self, value, connection, prepared=False):
        
        if not isinstance(value, dict):
            raise ValueError(
                f'Value: {value} must be of type dict'
            )
```

I think you should check also **not self.null** or maybe no invoke this method if the field supports null values.

#### Python script

```python
class TestModel(models.Model):
    test_dict = DictField(null=True)


from .... import TestModel
test = TestModel.objects.create()

```

#### Traceback
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/javi/.virtualenv/apiantest/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/javi/.virtualenv/apiantest/lib/python3.7/site-packages/django/db/models/query.py", line 422, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/javi/.virtualenv/apiantest/lib/python3.7/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/javi/.virtualenv/apiantest/lib/python3.7/site-packages/django/db/models/base.py", line 779, in save_base
    force_update, using, update_fields,
  File "/Users/javi/.virtualenv/apiantest/lib/python3.7/site-packages/django/db/models/base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Users/javi/.virtualenv/apiantest/lib/python3.7/site-packages/django/db/models/base.py", line 908, in _do_insert
    using=using, raw=raw)
  File "/Users/javi/.virtualenv/apiantest/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/javi/.virtualenv/apiantest/lib/python3.7/site-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/javi/.virtualenv/apiantest/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1334, in execute_sql
    for sql, params in self.as_sql():
  File "/Users/javi/.virtualenv/apiantest/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1278, in as_sql
    for obj in self.query.objs
  File "/Users/javi/.virtualenv/apiantest/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1278, in <listcomp>
    for obj in self.query.objs
  File "/Users/javi/.virtualenv/apiantest/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1277, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/Users/javi/.virtualenv/apiantest/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1218, in prepare_value
    value = field.get_db_prep_save(value, connection=self.connection)
  File "/Users/javi/.virtualenv/apiantest/lib/python3.7/site-packages/django/db/models/fields/__init__.py", line 789, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
  File "/Users/javi/Downloads/djongo-master/djongo/models/fields.py", line 128, in get_db_prep_value
    f'Value: {value} must be of type dict'
ValueError: Value: None must be of type dict

**Comment by ahmed-shariff** [comment]
I am also getting same error.

**Comment by cunningdolt** [comment]
I am also having the same error.
@ahmed-shariff  The workaround isn't working for me, can you help ?

**Comment by ahmed-shariff** [comment]
@cunningdolt  I will do what I can :D
Using `DictField` with `DictField(null=True, default={})` works for me. If you can provide more information, you might be able to get better feedback.

**Comment by cunningdolt** [comment]
@ahmed-shariff  Thanks, it worked.
I was passing only `default={}` parameter. I also find one more workaround, by converting the dictionary object into a JSON string and storing it in a `TextField` , by this I was also able to edit it through Django Admin.
