### ISSUE TITLE
Error 'unsupported type in filter' when insert on MongoDB 4.0

### ISSUE THREAD

**Issue by aleluc13** [nesdis/djongo#273]
First of all, we want to thank Djongo team for this amazing work. We are using Djongo for a couple weeks and works as expected with MongoDB 3.6, but recently our test environment was upgraded to version 4.0 and then we got this error `unsupported type in filter` when insert a document.

### Some relevant versions
Python: 3.6.6
Django: 2.0.6
Djongo: 1.2.32
MongoDB: 4.0.9
pymongo: 3.7.1
sqlparse: 0.2.4

### Exception
```
Exception Type: SQLDecodeError

FAILED SQL: INSERT INTO "imonline_imonline" ("aui", "t", "fore", "gps", "conn", "c") VALUES (%(0)s, %(1)s, %(2)s, %(3)s, %(4)s, %(5)s) Pymongo error: {'ok': 0, 'errmsg': 'unsupported type in filter', 'code': 8000, 'codeName': 'AtlasError'} Version: 1.2.32

/usr/local/lib/python3.6/dist-packages/djongo/sql2mongo/query.py in parse, line 818
```

### Digging into error
After some debugging we found something that could help to this issue:

The message error `unsupported type in filter` comes from function `collection_names` at `pymongo/database.py#712` 
```python
def collection_names(self, include_system_collections=True, session=None):
    ...
    warnings.warn("collection_names is deprecated. Use list_collection_names instead.", DeprecationWarning, stacklevel=2)
->  kws = {} if include_system_collections else _SYSTEM_FILTER
    return [result["name"]
                for result in self.list_collections(session=session, nameOnly=True, **kws)]
    ...
```
Also it's important no mention that this function it's marked as deprecated.

When use `_SYSTEM_FILTER` it's fails and throw the error mentioned, so temporally we change `include_system_collections` to True in `CachedCollections` class on `djongo/base.py#29`, like this:
```python
class CachedCollections(set):
    ...
    def __contains__(self, item):
        ...
        self.update(self.db.collection_names(include_system_collections=True))
        ...
```

This change worked for us, but there is something we can contribute to improve this solution and support version 4.0?

What about to call directly the `list_collection_names` function, like the warning says?

There is more information that we can provide to help?

**Comment by ahmed-shariff** [comment]
I am also running into the same exact problem. @aleluc13 thank you for the temporary fix.

my output log looks like this:
```
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 87, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/usr/lib/python3.7/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/lib/python3.7/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/usr/lib/python3.7/site-packages/django/db/migrations/loader.py", line 212, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/usr/lib/python3.7/site-packages/django/db/migrations/recorder.py", line 73, in applied_migrations
    if self.has_table():
  File "/usr/lib/python3.7/site-packages/django/db/migrations/recorder.py", line 56, in has_table
    return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
  File "/usr/lib/python3.7/site-packages/django/db/backends/base/introspection.py", line 48, in table_names
    return get_names(cursor)
  File "/usr/lib/python3.7/site-packages/django/db/backends/base/introspection.py", line 43, in get_names
    return sorted(ti.name for ti in self.get_table_list(cursor)
  File "/usr/lib/python3.7/site-packages/djongo/introspection.py", line 46, in get_table_list
    for c in cursor.db_conn.collection_names(False)
  File "/usr/lib/python3.7/site-packages/pymongo/database.py", line 787, in collection_names
    nameOnly=True, **kws)]
  File "/usr/lib/python3.7/site-packages/pymongo/database.py", line 725, in list_collections
    **kwargs)
  File "/usr/lib/python3.7/site-packages/pymongo/database.py", line 675, in _list_collections
    session=tmp_session)["cursor"]
  File "/usr/lib/python3.7/site-packages/pymongo/database.py", line 555, in _command
    client=self.__client)
  File "/usr/lib/python3.7/site-packages/pymongo/pool.py", line 584, in command
    user_fields=user_fields)
  File "/usr/lib/python3.7/site-packages/pymongo/network.py", line 158, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/usr/lib/python3.7/site-packages/pymongo/helpers.py", line 155, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: unsupported type in filter
```

**Comment by aleluc13** [comment]
@ahmed-shariff I'm glad this works for you (temporary)

Did you find anything else?

**Comment by ahmed-shariff** [comment]
#272 seems to provide a fix. Will have to check if that works tomorrow. Also it's pointed out that there is another place where the same `collection_names` is used.

btw, I was running into the problem when interfacing mongodb atlas. Didn't have any problems with running it on my pc with mongodb 4.0.9 ([from AUR](https://aur.archlinux.org/packages/mongodb-bin))
