### ISSUE TITLE
IndexError on test database instantiation

### ISSUE THREAD

**Issue by artemnesterenko** [nesdis/djongo#274]
When I run tests against an empty test database I get:
```python
Creating test database for alias 'mongo'...
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/djongo/sql2mongo/query.py", line 806, in parse
    return handler(self, statement)
  File "/usr/local/lib/python3.7/site-packages/djongo/sql2mongo/query.py", line 869, in _create
    type_code = props[1]
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 17, in <module>
    main()
  File "manage.py", line 13, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/test.py", line 23, in run_from_argv
    super().run_from_argv(argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/test.py", line 53, in handle
    failures = test_runner.run_tests(test_labels)
  File "/usr/local/lib/python3.7/site-packages/django/test/runner.py", line 629, in run_tests
    old_config = self.setup_databases(aliases=databases)
  File "/usr/local/lib/python3.7/site-packages/django/test/runner.py", line 554, in setup_databases
    self.parallel, **kwargs
  File "/usr/local/lib/python3.7/site-packages/django/test/utils.py", line 174, in setup_databases
    serialize=connection.settings_dict.get('TEST', {}).get('SERIALIZE', True),
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/creation.py", line 72, in create_test_db
    run_syncdb=True,
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 148, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 234, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/operations/models.py", line 92, in database_forwards
    schema_editor.create_model(model)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 307, in create_model
    self.execute(sql, params or None)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 137, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/usr/local/lib/python3.7/site-packages/djongo/cursor.py", line 53, in execute
    params)
  File "/usr/local/lib/python3.7/site-packages/djongo/sql2mongo/query.py", line 743, in __init__
    self.parse()
  File "/usr/local/lib/python3.7/site-packages/djongo/sql2mongo/query.py", line 826, in parse
    raise exe from e
djongo.sql2mongo.SQLDecodeError: FAILED SQL: CREATE TABLE "daily_activity_statistic" ()
Version: 1.2.32
```

**Comment by artemnesterenko** [comment]
As it turned out, the exception is caused by a model consisting only of embedded fields. As shown above, the generated SQL for such a model is `CREATE TABLE "table_name" ()`. There are no fields in the SQL, but djongo assumes that they always are when it's trying to write to the `__schema__` table. See https://github.com/nesdis/djongo/blob/master/djongo/sql2mongo/query.py#L881
As a temporary hacky solution, you can add any not-embedded field to the model or try to subclass the EmbeddedModelField to make it presented in the generated SQL.
