### ISSUE TITLE
MLAB Connection Refused

### ISSUE THREAD

**Issue by thecortex** [nesdis/djongo#28]
#### One line description of the issue

Issue when trying to connect to a database on mlab

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/qamar-ud-din/.virtualenvs/HackerDeals-KUN3UhSm/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/qamar-ud-din/.virtualenvs/HackerDeals-KUN3UhSm/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/qamar-ud-din/.virtualenvs/HackerDeals-KUN3UhSm/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/qamar-ud-din/.virtualenvs/HackerDeals-KUN3UhSm/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/qamar-ud-din/.virtualenvs/HackerDeals-KUN3UhSm/lib/python3.6/site-packages/django/core/management/commands/makemigrations.py", line 110, in handle
    loader.check_consistent_history(connection)
  File "/home/qamar-ud-din/.virtualenvs/HackerDeals-KUN3UhSm/lib/python3.6/site-packages/django/db/migrations/loader.py", line 282, in check_consistent_history
    applied = recorder.applied_migrations()
  File "/home/qamar-ud-din/.virtualenvs/HackerDeals-KUN3UhSm/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 65, in applied_migrations
    self.ensure_schema()
  File "/home/qamar-ud-din/.virtualenvs/HackerDeals-KUN3UhSm/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 52, in ensure_schema
    if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):
  File "/home/qamar-ud-din/.virtualenvs/HackerDeals-KUN3UhSm/lib/python3.6/site-packages/django/db/backends/base/introspection.py", line 55, in table_names
    return get_names(cursor)
  File "/home/qamar-ud-din/.virtualenvs/HackerDeals-KUN3UhSm/lib/python3.6/site-packages/django/db/backends/base/introspection.py", line 50, in get_names
    return sorted(ti.name for ti in self.get_table_list(cursor)
  File "/home/qamar-ud-din/.virtualenvs/HackerDeals-KUN3UhSm/lib/python3.6/site-packages/djongo/introspection.py", line 9, in get_table_list
    return [TableInfo(c,'t') for c in cursor.db_conn.collection_names(False)]
  File "/home/qamar-ud-din/.virtualenvs/HackerDeals-KUN3UhSm/lib/python3.6/site-packages/pymongo/database.py", line 555, in collection_names
    results = self._list_collections(sock_info, slave_okay)
  File "/home/qamar-ud-din/.virtualenvs/HackerDeals-KUN3UhSm/lib/python3.6/site-packages/pymongo/database.py", line 527, in _list_collections
    cursor = self._command(sock_info, cmd, slave_okay)["cursor"]
  File "/home/qamar-ud-din/.virtualenvs/HackerDeals-KUN3UhSm/lib/python3.6/site-packages/pymongo/database.py", line 428, in _command
    parse_write_concern_error=parse_write_concern_error)
  File "/home/qamar-ud-din/.virtualenvs/HackerDeals-KUN3UhSm/lib/python3.6/site-packages/pymongo/pool.py", line 477, in command
    collation=collation)
  File "/home/qamar-ud-din/.virtualenvs/HackerDeals-KUN3UhSm/lib/python3.6/site-packages/pymongo/network.py", line 116, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/home/qamar-ud-din/.virtualenvs/HackerDeals-KUN3UhSm/lib/python3.6/site-packages/pymongo/helpers.py", line 210, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: not authorized on hacker-deals to execute command { listCollections: 1, cursor: {} }

#### Python script

<The complete python script used to produce the issue.>

```python
<copy and paste code here>

```

#### Traceback
<The complete stack trace of the error.>

**Comment by nesdis** [comment]
this looks more like authentication issue. can you trying accessing MongoDB using pure pymongo and see if it works?

**Comment by petersobhi** [comment]
I have the same problem.
@thecortex have you solved it yet?
