### ISSUE TITLE
'Expected value to be type list' error with ArrayModelField

### ISSUE THREAD

**Issue by KuroNoDev** [nesdis/djongo#286]
This happens on POST method

models:

```python
from djongo import models

class Language(models.Model):
  name = models.CharField(max_length=100)
  image = models.CharField(max_length=100)

  class Meta:
    abstract = True

class Casino(models.Model):
  name = models.CharField(max_length=100)
  languages = models.ArrayModelField(
    model_container = Language
  )
  objects = models.DjongoManager()
```

serializer
```python
from rest_framework import serializers

from .models import Casino

class CasinoSerializer(serializers.ModelSerializer):
  languages = serializers.SerializerMethodField()

  class Meta:
    model = Casino
    fields = ('name', 'languages')

  def get_languages(self, obj):
    languages_list = []
    for item in obj.languages:
      embedded_dict = item.__dict__
      for key in list(embedded_dict.keys()):
        if key.startswith('_'):
          embedded_dict.pop(key)
      languages_list.append(embedded_dict)
    return languages_list
```

#### Traceback

```
[26/Jun/2019 15:25:58] "POST /api/casinos/ HTTP/1.1" 500 18811
Internal Server Error: /api/casinos/
Traceback (most recent call last):
  File "C:\Users\kuro\.virtualenvs\geotarget-server-zAaMnySW\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\kuro\.virtualenvs\geotarget-server-zAaMnySW\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\kuro\.virtualenvs\geotarget-server-zAaMnySW\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\kuro\.virtualenvs\geotarget-server-zAaMnySW\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\kuro\.virtualenvs\geotarget-server-zAaMnySW\lib\site-packages\rest_framework\viewsets.py", line 116, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\kuro\.virtualenvs\geotarget-server-zAaMnySW\lib\site-packages\rest_framework\views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\kuro\.virtualenvs\geotarget-server-zAaMnySW\lib\site-packages\rest_framework\views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\kuro\.virtualenvs\geotarget-server-zAaMnySW\lib\site-packages\rest_framework\views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\kuro\.virtualenvs\geotarget-server-zAaMnySW\lib\site-packages\rest_framework\mixins.py", line 21, in create
    self.perform_create(serializer)
  File "C:\Users\kuro\.virtualenvs\geotarget-server-zAaMnySW\lib\site-packages\rest_framework\mixins.py", line 26, in perform_create
    serializer.save()
  File "C:\Users\kuro\.virtualenvs\geotarget-server-zAaMnySW\lib\site-packages\rest_framework\serializers.py", line 214, in save
    self.instance = self.create(validated_data)
  File "C:\Users\kuro\.virtualenvs\geotarget-server-zAaMnySW\lib\site-packages\rest_framework\serializers.py", line 943, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "C:\Users\kuro\.virtualenvs\geotarget-server-zAaMnySW\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\kuro\.virtualenvs\geotarget-server-zAaMnySW\lib\site-packages\django\db\models\query.py", line 422, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\kuro\.virtualenvs\geotarget-server-zAaMnySW\lib\site-packages\django\db\models\base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Users\kuro\.virtualenvs\geotarget-server-zAaMnySW\lib\site-packages\django\db\models\base.py", line 779, in save_base
    force_update, using, update_fields,
  File "C:\Users\kuro\.virtualenvs\geotarget-server-zAaMnySW\lib\site-packages\django\db\models\base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk,
raw)
  File "C:\Users\kuro\.virtualenvs\geotarget-server-zAaMnySW\lib\site-packages\django\db\models\base.py", line 908, in _do_insert
    using=using, raw=raw)
  File "C:\Users\kuro\.virtualenvs\geotarget-server-zAaMnySW\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\kuro\.virtualenvs\geotarget-server-zAaMnySW\lib\site-packages\django\db\models\query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "C:\Users\kuro\.virtualenvs\geotarget-server-zAaMnySW\lib\site-packages\django\db\models\sql\compiler.py", line 1334, in execute_sql
    for sql, params in self.as_sql():
  File "C:\Users\kuro\.virtualenvs\geotarget-server-zAaMnySW\lib\site-packages\django\db\models\sql\compiler.py", line 1278, in as_sql
    for obj in self.query.objs
  File "C:\Users\kuro\.virtualenvs\geotarget-server-zAaMnySW\lib\site-packages\django\db\models\sql\compiler.py", line 1278, in <listcomp>
    for obj in self.query.objs
  File "C:\Users\kuro\.virtualenvs\geotarget-server-zAaMnySW\lib\site-packages\django\db\models\sql\compiler.py", line 1277, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]  File "C:\Users\kuro\.virtualenvs\geotarget-server-zAaMnySW\lib\site-packages\django\db\models\sql\compiler.py", line 1218, in prepare_value    value = field.get_db_prep_save(value, connection=self.connection)
  File "C:\Users\kuro\.virtualenvs\geotarget-server-zAaMnySW\lib\site-packages\django\db\models\fields\__init__.py", line 789, in get_db_prep_save    return self.get_db_prep_value(value, connection=connection, prepared=False)
  File "C:\Users\kuro\.virtualenvs\geotarget-server-zAaMnySW\lib\site-packages\djongo\models\fields.py",line 203, in get_db_prep_value
    'Expected value to be type list,'ValueError: Expected value to be type list,Got type <class 'NoneType'> instead
[26/Jun/2019 15:26:03] "POST /api/casinos/ HTTP/1.1" 500 18811
```

**Comment by SomeoneInParticular** [comment]
Your code currently supports the serializer interpreting already created instances, while the error you are getting is because the serializer does not know how to build those instances from that serialized data (database -> representation vs. representation -> database).

Sadly, this is not a simple fix; there are semi-feasible solutions:
1. You could create custom create/update functions for your serializer (see [DRF's writable nested serializer documentation](https://www.django-rest-framework.org/api-guide/relations/#writable-nested-serializers) for info on how one might go about doing that). This gives you a lot of control on how to work with serialized instances, but if you have a lot of serializers this could get quite tedious or lead to a lot of duplicated code.
2. You could build a custom field which can handle your desired model (see [DRF's custom fields documentation](https://www.django-rest-framework.org/api-guide/fields/#custom-fields) for info on how to do that); this can get quite cumbersome if you have lots of models which would need be serialized in this way.
3. You can also use my package, `rest-meets-djongo`, to automate it somewhat. You'll likely still need to add some custom functionality (namely fields and/or custom create/update functions), however, and its implementation has slightly more overhead than DRF's ModelSerializer. I also only recently completed its core functionality, so it is quite likely to have bugs/quirks I haven't yet caught and fixed. (You could also just rip out the code I used to automatically generate serializers if you want as well; [Open-source code here](https://gitlab.com/SomeoneInParticular/rest_meets_djongo))
