### ISSUE TITLE
Authentication Credential Support is missing 

### ISSUE THREAD

**Issue by rsrivastava76** [nesdis/djongo#30]
#### DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'NAME': XXXXXXXXX,
        'HOST': XXXXXXXXX,
        'PORT': XXXXXXXXX,
        'USER': XXXXXXXXX,
        'PASSWORD': XXXXXXXXX,
    }
}

```

#### Traceback
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x109c0ba60>
Traceback (most recent call last):
  File "/Users/rsrivastava/anaconda/lib/python3.6/site-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/Users/rsrivastava/anaconda/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 128, in inner_run
    self.check_migrations()
  File "/Users/rsrivastava/anaconda/lib/python3.6/site-packages/django/core/management/base.py", line 422, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/Users/rsrivastava/anaconda/lib/python3.6/site-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/Users/rsrivastava/anaconda/lib/python3.6/site-packages/django/db/migrations/loader.py", line 52, in __init__
    self.build_graph()
  File "/Users/rsrivastava/anaconda/lib/python3.6/site-packages/django/db/migrations/loader.py", line 209, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/Users/rsrivastava/anaconda/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 65, in applied_migrations
    self.ensure_schema()
  File "/Users/rsrivastava/anaconda/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 52, in ensure_schema
    if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):
  File "/Users/rsrivastava/anaconda/lib/python3.6/site-packages/django/db/backends/base/introspection.py", line 55, in table_names
    return get_names(cursor)
  File "/Users/rsrivastava/anaconda/lib/python3.6/site-packages/django/db/backends/base/introspection.py", line 50, in get_names
    return sorted(ti.name for ti in self.get_table_list(cursor)
  File "/Users/rsrivastava/anaconda/lib/python3.6/site-packages/djongo/introspection.py", line 9, in get_table_list
    return [TableInfo(c,'t') for c in cursor.db_conn.collection_names(False)]
  File "/Users/rsrivastava/anaconda/lib/python3.6/site-packages/pymongo/database.py", line 555, in collection_names
    results = self._list_collections(sock_info, slave_okay)
  File "/Users/rsrivastava/anaconda/lib/python3.6/site-packages/pymongo/database.py", line 527, in _list_collections
    cursor = self._command(sock_info, cmd, slave_okay)["cursor"]
  File "/Users/rsrivastava/anaconda/lib/python3.6/site-packages/pymongo/database.py", line 428, in _command
    parse_write_concern_error=parse_write_concern_error)
  File "/Users/rsrivastava/anaconda/lib/python3.6/site-packages/pymongo/pool.py", line 477, in command
    collation=collation)
  File "/Users/rsrivastava/anaconda/lib/python3.6/site-packages/pymongo/network.py", line 116, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/Users/rsrivastava/anaconda/lib/python3.6/site-packages/pymongo/helpers.py", line 210, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: not authorized on testDevDB to execute command { listCollections: 1, cursor: {} }

**Comment by nesdis** [comment]
duplicate #31
