### ISSUE TITLE
ArrayModelField change throws error while migrating

### ISSUE THREAD

**Issue by Vichoko** [nesdis/djongo#302]
#### One line description of the issue
Migrate a migration that contains a change in a ArrayModelField property, throw fatal error.

#### Python script

```python
from djongo import models 

class AnyAbstractModel(models.Model):
    name = models.TextField()

    class Meta:
        abstract = True

class MyModel(models.Model):
     my_list = models.ArrayModelField(model_container=AnyAbstractModel)
```

Call python `manage.py makemigrations` and `python manage.py migrate`.
Now introduce a change in the field, and call `manage.py makemigrations` and `python manage.py migrate` again.

For example, i tried this both examples:
```
# ...
class MyModel(models.Model):
     my_list = models.ArrayModelField(model_container=AnyAbstractModel, default=[])
```
or

```
# ...
class MyModel(models.Model):
     my_list = models.ArrayModelField(model_container=AnyAbstractModel, null=True)
```

#### Traceback
web_1          | Tracking file by folder pattern:  migrations
web_1          | Operations to perform:
web_1          |   Apply all migrations: admin, auth, contenttypes, sessions, transcription, wordvectors
web_1          | Running migrations:
web_1          |   Applying wordvectors.0005_auto_20190803_0318...Traceback (most recent call last):
web_1          |   File "/opt/.pycharm_helpers/pycharm/django_manage.py", line 52, in <module>
web_1          |     run_command()
web_1          |   File "/opt/.pycharm_helpers/pycharm/django_manage.py", line 46, in run_command
web_1          |     run_module(manage_file, None, '__main__', True)
web_1          |   File "/usr/local/lib/python3.6/runpy.py", line 205, in run_module
web_1          |     return _run_module_code(code, init_globals, run_name, mod_spec)
web_1          |   File "/usr/local/lib/python3.6/runpy.py", line 96, in _run_module_code
web_1          |     mod_name, mod_spec, pkg_name, script_name)
web_1          |   File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
web_1          |     exec(code, run_globals)
web_1          |   File "/opt/project/manage.py", line 20, in <module>
web_1          |     execute_from_command_line(sys.argv)
web_1          |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
web_1          |     utility.execute()
web_1          |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
web_1          |     self.fetch_command(subcommand).run_from_argv(self.argv)
web_1          |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
web_1          |     self.execute(*args, **cmd_options)
web_1          |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
web_1          |     output = self.handle(*args, **options)
web_1          |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
web_1          |     res = handle_func(*args, **kwargs)
web_1          |   File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 203, in handle
web_1          |     fake_initial=fake_initial,
web_1          |   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
web_1          |     state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
web_1          |   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
web_1          |     state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
web_1          |   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
web_1          |     state = migration.apply(state, schema_editor)
web_1          |   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/migration.py", line 124, in apply
web_1          |     operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
web_1          |   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/operations/fields.py", line 216, in database_forwards
web_1          |     schema_editor.alter_field(from_model, from_field, to_field)
web_1          |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 502, in alter_field
web_1          |     (old_field, new_field),
web_1          | ValueError: Cannot alter field my_app.MyModel.my_list into my_app.MyModel.my_list- they do not properly define db_type (are you using a badly-written custom field?)

**Comment by SantoshBHegde** [comment]
Having same issue...

**Comment by saurabh-m523** [comment]
I'm also facing the same issue. Has anyone found any solution?

**Comment by westbrookj** [comment]
This issue is still a problem. Has there been any progress or has a solution been found?

**Comment by yunussahinio** [comment]
I solved this problem like that:
`    survey = models.EmbeddedModelField(model_container=Survey, null=True)`
to
`    survey = models.EmbeddedModelField(model_container=Survey, null=True, default=None)`

**Comment by phillipuniverse** [comment]
Same issue here, looks like the `default=None` didn't fix it on my end.

Did some digging, the problem is that in Django, we try to get the data type from the connection here: https://github.com/django/django/blob/e3e48b00127c09eafe6439d980a82fc5c591b673/django/db/models/fields/__init__.py#L664

The `get_internal_type()` on an `EmbeddedField` returns a String `EmbeddedField`.

The `connection` in this case refers to the `djongo/base.py`, and it gets the `data_types` field which is responsible for mapping field types to their representations:

https://github.com/nesdis/djongo/blob/3ff03d0015d9957cec2d2aca8e39f93a26dd607c/djongo/base.py#L49-L79

`EmbeddedField` does not exist here so it returns none, which fails Django's core validation and the above exception.

There is not really any workaround I have found except to delete the field from the migration and re-add it with the correct configuration. Example:

```
class Migration(migrations.Migration):

    dependencies = [ ]

    operations = [
        migrations.RemoveField(model_name='mymodel', name='property'),
        migrations.AddField(
            model_name='mymodel',
            name='property',
            field=EmbeddedField(
                model_container=CustomEmbeddedContainer(),
                blank=True,
                default=None
            ),
        ),
    ]
```

My original model had this as a `DictField` and I was trying to convert it to a proper `EmbeddedField`.
