### ISSUE TITLE
djongo.sql2mongo.SQLDecodeError while updating / reading rows

### ISSUE THREAD

**Issue by pratibhajagnere** [nesdis/djongo#304]
#### One line description of the issue
I am getting below error, in create and update APIs

`djongo.sql2mongo.SQLDecodeError: FAILED SQL: UPDATE `

Read API giving `matching query does not exist.` on Foreign key field `Batch` whereas when I check in DB it is there.

Setup:
Django==2.1
pymongo==3.8.0
sqlparse==0.2.4

#### Python script

#getting IP is serializer from API payload.

product = Product.model.get(macid='0C:F0:B4:24:69:3A')
product.set_ip(IP)

```python
class Product(models.Model):
   
    batch_number = models.IntegerField(unique=True)

class Product(models.Model):
   
    batch = ForeignKey(Batch, on_delete=CASCADE)
    serial_number = models.CharField(max_length=255, unique=True)
    macid = models.CharField(max_length=100, unique=True)
    product_name= models.CharField(max_length=100)
    product_status = models.CharField(max_length=100, default='Unallocated')
    device_ip = models.GenericIPAddressField(default="10.0.0.1")
    white_label = models.CharField(max_length=100, default='')
    hardware_version = models.CharField(max_length=100, default='Unknown')
    last_online = models.DateTimeField(auto_now=True)
    modified_date = models.DateTimeField(auto_now=True)
    created_date = models.DateTimeField(auto_now_add=True)

    def set_ip(self, ip):
        self.device_ip = ip
        self.save()

```

#### Traceback
<The complete stack trace of the error.>
Internal Server Error: /productstatus 
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 819, in parse
    return handler(self, statement)
  File "/usr/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 939, in _update
    self._query = UpdateQuery(self.db, self.connection_properties, sm, self._params)
  File "/usr/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 312, in __init__
    super().__init__(*args)
  File "/usr/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 74, in __init__
    self.parse()
  File "/usr/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 331, in parse
    c = self.where = WhereConverter(self, tok_id)
  File "/usr/lib/python3.6/site-packages/djongo/sql2mongo/converters.py", line 24, in __init__
    self.parse()
  File "/usr/lib/python3.6/site-packages/djongo/sql2mongo/converters.py", line 148, in parse
    params=self.query.params
  File "/usr/lib/python3.6/site-packages/djongo/sql2mongo/operators.py", line 362, in __init__
    op = ParenthesisOp(0, sqlparse('(' + self.token.value[6:] + ')')[0][0], self.query)
  File "/usr/lib/python3.6/site-packages/djongo/sql2mongo/operators.py", line 446, in __init__
    op = CmpOp(0, tok, self.query)
  File "/usr/lib/python3.6/site-packages/djongo/sql2mongo/operators.py", line 514, in __init__
    self._constant = self.params[index] if index is not None else None
IndexError: tuple index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/centos/backend_server/routers/views.py", line 37, in post
    user = serializer.is_valid(raise_exception=True)
  File "/usr/lib/python3.6/site-packages/rest_framework/serializers.py", line 236, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/usr/lib/python3.6/site-packages/rest_framework/serializers.py", line 437, in run_validation
    value = self.validate(value)
  File "/home/backend/products/serializers.py", line 86, in validate
    product.set_ip(ip)
  File "/home/backend/products/models.py", line 27, in set_ip
    self.save()
  File "/usr/lib/python3.6/site-packages/django/db/models/base.py", line 717, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/lib/python3.6/site-packages/django/db/models/base.py", line 747, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/lib/python3.6/site-packages/django/db/models/base.py", line 811, in _save_table
    forced_update)
  File "/usr/lib/python3.6/site-packages/django/db/models/base.py", line 860, in _do_update
    return filtered._update(values) > 0
  File "/usr/lib/python3.6/site-packages/django/db/models/query.py", line 709, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/usr/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1379, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/usr/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1061, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python3.6/site-packages/djongo/cursor.py", line 53, in execute
    params)
  File "/usr/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 754, in __init__
    self.parse()
  File "/usr/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 841, in parse
    raise exe from e
djongo.sql2mongo.SQLDecodeError: FAILED SQL: UPDATE "products_product" SET "serial_number" = %(0)s, "product_name" = %(1)s, "macid" = %(2)s, "product_status" = %(3)s, "device_ip" = %(4)s, "white_label" = %(5)s, "hardware_version" = %(6)s, "last_online" = %(7)s, "modified_date" = %(8)s, "created_date" = %(9)s WHERE "products_product"."id" = %(10)s
Params: ('210D84003C0EF9725B1C86B4AA9FA7A2', 'deviceName1', '0C:F0:B4:24:69:3A', 'Active', '60.49.95.217', 'LABEL', 'V1', datetime.datetime(2019, 8, 6, 6, 13, 10, 693744), datetime.datetime(2019, 8, 6, 6, 13, 10, 693750), datetime.datetime(2019, 7, 30, 16, 46, 24, 115000), 111)
Version: 1.2.33
[06/Aug/2019 06:13:11] "POST /productstatus HTTP/1.0" 500 21044

**Comment by yogeshchandrark** [comment]
Hi,
I am facing the same error.

djongo 1.2.31
django 2.1.8
mongo 4.0.9

I am trying to run my Django API to Update some records, if i send four records out of four three will parse successfully but the fourth one fails(its random). its not consistent, but if any help to avoid this data loss will be much appreciated.

can anyone help me on this.

Regards,
Yogesh

**Comment by pratibhajagnere** [comment]
Can someone please help us on this. Due to this we are not able to use Djongo in our production

**Comment by iserranoe** [comment]
Same here:
- I combine djongo with django rest framework to build the apis. 
- With React I am requesting several "gets" to the api, one immediately after the other. 
- Usually, it works fine. However, sometimes I get this error at the fourth or fifth request; and, as @yogeshchandrark said, it is completely random...
