### ISSUE TITLE
django 2.2.4 not connected to mlab

### ISSUE THREAD

**Issue by turkdoktoru** [nesdis/djongo#310]
Hello there,

I'm using python3 and django 2.2.4. When migrate using djongo, it gives error like below. Can you help me ?

**pip list**
Package     Version
----------- -------
dataclasses 0.6    
Django      2.2.4  
djongo      1.2.33 
pip         19.0.3 
pymongo     3.9.0  
pytz        2019.2 
setuptools  40.8.0 
sqlparse    0.2.4  

djongo.sql2mongo.SQLDecodeError: FAILED SQL: CREATE TABLE "django_migrations" ("id" int32 NOT NULL PRIMARY KEY AUTOINCREMENT, "app" string NOT NULL, "name" string NOT NULL, "applied" date NOT NULL)
Params: None
Pymongo error: {'operationTime': Timestamp(1566124342, 5), 'ok': 0.0, 'errmsg': 'Transaction numbers are only allowed on storage engines that support document-level locking', 'code': 20, 'codeName': 'IllegalOperation', '$clusterTime': {'clusterTime': Timestamp(1566124342, 5), 'signature': {'hash': b'\xc1}F\xf6\x8e\xba\xf4\x89e\xcf\xbdl[\xdb\xfd\xfb\xef\xf5\xda\x84', 'keyId': 6725778597803458561}}}
Version: 1.2.33

**Detail error**

```python
<(venv) user@user:~/İndirilenler/hastatakip$ pip list
Package     Version
----------- -------
dataclasses 0.6    
Django      2.2.4  
djongo      1.2.33 
pip         19.0.3 
pymongo     3.9.0  
pytz        2019.2 
setuptools  40.8.0 
sqlparse    0.2.4  
(venv) user@user:~/İndirilenler/hastatakip$ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
Traceback (most recent call last):
  File "/home/user/İndirilenler/hastatakip/venv/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1385, in _retry_with_session
    return func(session, sock_info, retryable)
  File "/home/user/İndirilenler/hastatakip/venv/lib/python3.7/site-packages/pymongo/collection.py", line 852, in _update
    retryable_write=retryable_write)
  File "/home/user/İndirilenler/hastatakip/venv/lib/python3.7/site-packages/pymongo/collection.py", line 822, in _update
    retryable_write=retryable_write).copy()
  File "/home/user/İndirilenler/hastatakip/venv/lib/python3.7/site-packages/pymongo/pool.py", line 613, in command
    user_fields=user_fields)
  File "/home/user/İndirilenler/hastatakip/venv/lib/python3.7/site-packages/pymongo/network.py", line 167, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/home/user/İndirilenler/hastatakip/venv/lib/python3.7/site-packages/pymongo/helpers.py", line 159, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: Transaction numbers are only allowed on storage engines that support document-level locking

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/İndirilenler/hastatakip/venv/lib/python3.7/site-packages/djongo/sql2mongo/query.py", line 819, in parse
    return handler(self, statement)
  File "/home/user/İndirilenler/hastatakip/venv/lib/python3.7/site-packages/djongo/sql2mongo/query.py", line 917, in _create
    upsert=True
  File "/home/user/İndirilenler/hastatakip/venv/lib/python3.7/site-packages/pymongo/collection.py", line 1003, in update_one
    session=session),
  File "/home/user/İndirilenler/hastatakip/venv/lib/python3.7/site-packages/pymongo/collection.py", line 856, in _update_retryable
    _update, session)
  File "/home/user/İndirilenler/hastatakip/venv/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1492, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
  File "/home/user/İndirilenler/hastatakip/venv/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1426, in _retry_with_session
    raise OperationFailure(errmsg, exc.code, exc.details)
pymongo.errors.OperationFailure: This MongoDB deployment does not support retryable writes. Please add retryWrites=false to your connection string.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/user/İndirilenler/hastatakip/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/user/İndirilenler/hastatakip/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/user/İndirilenler/hastatakip/venv/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/user/İndirilenler/hastatakip/venv/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/user/İndirilenler/hastatakip/venv/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/user/İndirilenler/hastatakip/venv/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 234, in handle
    fake_initial=fake_initial,
  File "/home/user/İndirilenler/hastatakip/venv/lib/python3.7/site-packages/django/db/migrations/executor.py", line 91, in migrate
    self.recorder.ensure_schema()
  File "/home/user/İndirilenler/hastatakip/venv/lib/python3.7/site-packages/django/db/migrations/recorder.py", line 67, in ensure_schema
    editor.create_model(self.Migration)
  File "/home/user/İndirilenler/hastatakip/venv/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 307, in create_model
    self.execute(sql, params or None)
  File "/home/user/İndirilenler/hastatakip/venv/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 137, in execute
    cursor.execute(sql, params)
  File "/home/user/İndirilenler/hastatakip/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/home/user/İndirilenler/hastatakip/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/user/İndirilenler/hastatakip/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/user/İndirilenler/hastatakip/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/home/user/İndirilenler/hastatakip/venv/lib/python3.7/site-packages/djongo/cursor.py", line 53, in execute
    params)
  File "/home/user/İndirilenler/hastatakip/venv/lib/python3.7/site-packages/djongo/sql2mongo/query.py", line 754, in __init__
    self.parse()
  File "/home/user/İndirilenler/hastatakip/venv/lib/python3.7/site-packages/djongo/sql2mongo/query.py", line 832, in parse
    raise exe from e
djongo.sql2mongo.SQLDecodeError: FAILED SQL: CREATE TABLE "django_migrations" ("id" int32 NOT NULL PRIMARY KEY AUTOINCREMENT, "app" string NOT NULL, "name" string NOT NULL, "applied" date NOT NULL)
Params: None
Pymongo error: {'operationTime': Timestamp(1566124342, 5), 'ok': 0.0, 'errmsg': 'Transaction numbers are only allowed on storage engines that support document-level locking', 'code': 20, 'codeName': 'IllegalOperation', '$clusterTime': {'clusterTime': Timestamp(1566124342, 5), 'signature': {'hash': b'\xc1}F\xf6\x8e\xba\xf4\x89e\xcf\xbdl[\xdb\xfd\xfb\xef\xf5\xda\x84', 'keyId': 6725778597803458561}}}
Version: 1.2.33
>

```

**Comment by JavadiSaeid** [comment]
I have this problem, too, even with the other Django version
Django      2.2.2  
djongo      1.2.35  
sqlparse    0.2.4  
I didn't find any solution for it, djongo library is in trouble
