### ISSUE TITLE
Not compatible with Django 3.0

### ISSUE THREAD

**Issue by aisolution** [nesdis/djongo#354]
#### Djongo is not working with new version of Django

```python
py manage.py makemigrations polls
```

#### Traceback
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\db\utils.py", line 111, in load_backend
    return import_module('%s.base' % backend_name)
  File "C:\ProgramData\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\ProgramData\Anaconda3\lib\site-packages\djongo\base.py", line 15, in <module>
    from .operations import DatabaseOperations
  File "C:\ProgramData\Anaconda3\lib\site-packages\djongo\operations.py", line 4, in <module>
    from django.utils import six, timezone
ImportError: cannot import name 'six' from 'django.utils' (C:\ProgramData\Anaconda3\lib\site-packages\django\utils\__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\management\__init__.py", line 377, in execute
    django.setup()
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\apps\registry.py", line 114, in populate
    app_config.import_models()
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\apps\config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\ProgramData\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\contrib\auth\models.py", line 2, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\contrib\auth\base_user.py", line 47, in <module>
    class AbstractBaseUser(models.Model):
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\db\models\base.py", line 121, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\db\models\base.py", line 325, in add_to_class
    value.contribute_to_class(cls, name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\db\models\options.py", line 208, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\db\__init__.py", line 28, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\db\utils.py", line 207, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\db\utils.py", line 126, in load_backend
    ) from e_user
django.core.exceptions.ImproperlyConfigured: 'djongo' isn't an available database backend.
Try using 'django.db.backends.XXX', where XXX is one of:
    'mysql', 'oracle', 'postgresql', 'sqlite3'

**Comment by 4rch18** [comment]
Issue related to six fixed in the recent pull
> https://github.com/nesdis/djongo/pull/353 Switching from django.utils.six to six

But in my experience there are issues while using Django 3.0. For now Django 2.2 is working out better.

**Comment by harshilishere** [comment]
I tried installing djongo with pip install djongo but when i do that it automatically shifts my django version down to 2.2
Is there some way where I can use django 3.0 and still use mongodb? or some way with which i can use djongo with django 3.0??
