### ISSUE TITLE
SQLDecodeError is at /admin/auth/user/ 

### ISSUE THREAD

**Issue by jay20162016** [nesdis/djongo#371]
#### One line description of the issue
SQLDecodeError is raised at /admin/auth/user/ when filtering groups.

#### Python script

<The complete python script used to produce the issue.>

```bash
python manage.py runserver

```

#### Traceback
```
Environment:


Request Method: GET
Request URL: http://127.0.0.1:8000/admin/auth/user/?groups__id__exact=1

Django Version: 3.0.3
Python Version: 3.8.1
Installed Applications:
['game.apps.GameConfig',
 'user.apps.UserConfig',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/djongo/sql2mongo/query.py", line 824, in parse
    return handler(self, statement)
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/djongo/sql2mongo/query.py", line 963, in _select
    self._query = SelectQuery(self.db, self.connection_properties, sm, self._params)
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/djongo/sql2mongo/query.py", line 111, in __init__
    super().__init__(*args)
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/djongo/sql2mongo/query.py", line 72, in __init__
    self.parse()
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/djongo/sql2mongo/query.py", line 151, in parse
    raise SQLDecodeError

The above exception () was the direct cause of the following exception:
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/contrib/admin/options.py", line 607, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 231, in inner
    return view(request, *args, **kwargs)
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1678, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/contrib/admin/options.py", line 728, in get_changelist_instance
    return ChangeList(
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/contrib/admin/views/main.py", line 97, in __init__
    self.queryset = self.get_queryset(request)
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/contrib/admin/views/main.py", line 423, in get_queryset
    filters_use_distinct) = self.get_filters(request)
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/contrib/admin/views/main.py", line 149, in get_filters
    spec = field_list_filter_class(
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/contrib/admin/filters.py", line 159, in create
    return list_filter_class(field, request, params, model, model_admin, field_path=field_path)
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/contrib/admin/filters.py", line 170, in __init__
    self.lookup_choices = self.field_choices(field, request, model_admin)
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/contrib/admin/filters.py", line 207, in field_choices
    return field.get_choices(include_blank=False, ordering=ordering)
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 864, in get_choices
    return (blank_choice if include_blank else []) + [
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/db/models/query.py", line 276, in __iter__
    self._fetch_all()
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/db/models/query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/db/models/query.py", line 57, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1144, in execute_sql
    cursor.execute(sql, params)
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/djongo/cursor.py", line 48, in execute
    self.result = Result(
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/djongo/sql2mongo/query.py", line 753, in __init__
    self.parse()
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/djongo/sql2mongo/query.py", line 846, in parse
    raise exe from e

Exception Type: SQLDecodeError at /admin/auth/user/
Exception Value: FAILED SQL: SELECT "auth_group"."id", "auth_group"."name" FROM "auth_group" ORDER BY "auth_group"."name" ASC
Params: ()
Version: 1.3.1
```

Downgrading `sqlparse` and `djongo` does not work for me

**Comment by jay20162016** [comment]
Also, in /admin/
```
Environment:


Request Method: GET
Request URL: http://127.0.0.1:8000/admin/

Django Version: 3.0.3
Python Version: 3.8.1
Installed Applications:
['game.apps.GameConfig',
 'user.apps.UserConfig',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']


Template error:
In template /Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/contrib/admin/templates/admin/base.html, error at line 0
   FAILED SQL: SELECT "django_admin_log"."id", "django_admin_log"."action_time", "django_admin_log"."user_id", "django_admin_log"."content_type_id", "django_admin_log"."object_id", "django_admin_log"."object_repr", "django_admin_log"."action_flag", "django_admin_log"."change_message", "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined", "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_admin_log" INNER JOIN "auth_user" ON ("django_admin_log"."user_id" = "auth_user"."id") LEFT OUTER JOIN "django_content_type" ON ("django_admin_log"."content_type_id" = "django_content_type"."id") WHERE "django_admin_log"."user_id" = %(0)s ORDER BY "django_admin_log"."action_time" DESC LIMIT 10
Params: (1,)
Version: 1.3.1
   1 : {% load i18n static %}<!DOCTYPE html>
   2 : {% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}
   3 : <html lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
   4 : <head>
   5 : <title>{% block title %}{% endblock %}</title>
   6 : <link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static "admin/css/base.css" %}{% endblock %}">
   7 : {% block extrastyle %}{% endblock %}
   8 : {% if LANGUAGE_BIDI %}<link rel="stylesheet" type="text/css" href="{% block stylesheet_rtl %}{% static "admin/css/rtl.css" %}{% endblock %}">{% endif %}
   9 : {% block extrahead %}{% endblock %}
   10 : {% block responsive %}


Traceback (most recent call last):
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/djongo/sql2mongo/query.py", line 824, in parse
    return handler(self, statement)
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/djongo/sql2mongo/query.py", line 963, in _select
    self._query = SelectQuery(self.db, self.connection_properties, sm, self._params)
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/djongo/sql2mongo/query.py", line 111, in __init__
    super().__init__(*args)
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/djongo/sql2mongo/query.py", line 72, in __init__
    self.parse()
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/djongo/sql2mongo/query.py", line 151, in parse
    raise SQLDecodeError

The above exception () was the direct cause of the following exception:
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/core/handlers/base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/core/handlers/base.py", line 143, in _get_response
    response = response.render()
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/template/defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/template/defaulttags.py", line 166, in render
    len_values = len(values)
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/db/models/query.py", line 258, in __len__
    self._fetch_all()
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/db/models/query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/db/models/query.py", line 57, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1144, in execute_sql
    cursor.execute(sql, params)
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/djongo/cursor.py", line 48, in execute
    self.result = Result(
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/djongo/sql2mongo/query.py", line 753, in __init__
    self.parse()
  File "/Users/jayjay/anaconda3/envs/djongo/lib/python3.8/site-packages/djongo/sql2mongo/query.py", line 846, in parse
    raise exe from e

Exception Type: SQLDecodeError at /admin/
Exception Value: FAILED SQL: SELECT "django_admin_log"."id", "django_admin_log"."action_time", "django_admin_log"."user_id", "django_admin_log"."content_type_id", "django_admin_log"."object_id", "django_admin_log"."object_repr", "django_admin_log"."action_flag", "django_admin_log"."change_message", "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined", "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_admin_log" INNER JOIN "auth_user" ON ("django_admin_log"."user_id" = "auth_user"."id") LEFT OUTER JOIN "django_content_type" ON ("django_admin_log"."content_type_id" = "django_content_type"."id") WHERE "django_admin_log"."user_id" = %(0)s ORDER BY "django_admin_log"."action_time" DESC LIMIT 10
Params: (1,)
Version: 1.3.1
```

**Comment by jay20162016** [comment]
I have
```
python==3.8.1
sqlparse==0.3.1
pymongo==3.10.1
django==3.0.3
djongo==1.3.1
```

**Comment by mirza-arslan-baig** [comment]
I am facing the same issue.

Environment:


Request Method: GET
Request URL: http://localhost:8000/admin/auth/user/?groups__id__exact=1

Django Version: 2.2.5
Python Version: 3.7.5
Installed Applications:
['cisco_stc_portal',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'main.apps.MainConfig',
 'performance.apps.PerformanceConfig',
 'lacp.apps.LacpConfig',
 'syslogs.apps.SyslogsConfig',
 'login_required']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'login_required.middleware.LoginRequiredMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

**Comment by mirza-arslan-baig** [comment]
I have:
sqlparse: 0.2.4
pymongo: 3.9.0
Django Version: 2.2.5
Python Version: 3.7.5

**Comment by jay20162016** [comment]
With a few reinstalls of djongo, I now have:
```
certifi==2019.11.28
dataclasses==0.6
Django==2.2.10
django-jsoneditor==0.1.5
djongo==1.3.1
jsonfield==3.1.0
packaging==20.1
pymongo==3.10.1
pyparsing==2.4.6
python-dateutil==2.8.1
pytz==2019.3
six==1.14.0
sqlparse==0.2.4
```

**Comment by jay20162016** [comment]
with these new versions, it `/admin/` works but `/admin/auth/user/?groups__id__exact=1` doesn't

**Comment by jay20162016** [comment]
@mirza-arslan-baig what is the output of `pip freeze`?

**Comment by mirza-arslan-baig** [comment]
This is the output of pip freeze:

**Comment by jay20162016** [comment]
Just to satify dependencies, you probably want to upgrade `six`, but it's not the main problem.

**Comment by jay20162016** [comment]
I think the main problem is that djongo doesn't support subqueries.

**Comment by jay20162016** [comment]
Here's a temporary hack that I found:
Change line 753 in `djongo/sql2mongo/query.py` from this:
```python
        self.parse()
```
to this:
```python
        try:
            self.parse()
        except:
            if (self._sql.strip().endswith("subquery")):
                self._sql = self._sql.strip()[:-8]
```
