### ISSUE TITLE
Cannot use __contains or __startswith

### ISSUE THREAD

**Issue by tbobm** [nesdis/djongo#39]
#### One line description of the issue

I find myself unable to use string-based filtering using djongo, despite the example containing one.
Am I missing something ? Do you have an idea about what could be the origin of this issue ?

Thanks in advance.

#### Python script

```python
>>> from myapp.models import MyModel
>>> MyModel.objects.filter(name__contains='e')  # Default DB, SQL-based
<QuerySet [<MyModel: 1>, <MyModel: 2>, <MyModel: 3>]>
>>> MyModel.objects.using('mongo').filter(name__contains='e')  # MongoDB 3.4
```

#### Traceback
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/my_project/.venv/lib/python3.6/site-packages/django/db/models/query.py", line 248, in __repr__
    data = list(self[:REPR_OUTPUT_SIZE + 1])
  File "/my_project/.venv/lib/python3.6/site-packages/django/db/models/query.py", line 272, in __iter__
    self._fetch_all()
  File "/my_project/.venv/lib/python3.6/site-packages/django/db/models/query.py", line 1179, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/my_project/.venv/lib/python3.6/site-packages/django/db/models/query.py", line 54, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/my_project/.venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1064, in execute_sql
    cursor.execute(sql, params)
  File "/my_project/.venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/my_project/.venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/my_project/.venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/my_project/.venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/my_project/.venv/lib/python3.6/site-packages/djongo/cursor.py", line 44, in execute
    self.result = Result(self.client_conn, self.db_conn, sql, params)
  File "/my_project/.venv/lib/python3.6/site-packages/djongo/sql2mongo.py", line 725, in __init__
    self.parse()
  File "/my_project/.venv/lib/python3.6/site-packages/djongo/sql2mongo.py", line 775, in parse
    return handler(self, statement)
  File "/my_project/.venv/lib/python3.6/site-packages/djongo/sql2mongo.py", line 891, in _select
    self._query = SelectQuery(self, sm, self._params)
  File "/my_project/.venv/lib/python3.6/site-packages/djongo/sql2mongo.py", line 451, in __init__
    super().__init__(*args)
  File "/my_project/.venv/lib/python3.6/site-packages/djongo/sql2mongo.py", line 124, in __init__
    self.parse()
  File "/my_project/.venv/lib/python3.6/site-packages/djongo/sql2mongo.py", line 479, in parse
    c = self.where = WhereConverter(self, tok_id)
  File "/my_project/.venv/lib/python3.6/site-packages/djongo/sql2mongo.py", line 146, in __init__
    self.parse()
  File "/my_project/.venv/lib/python3.6/site-packages/djongo/sql2mongo.py", line 243, in parse
    params=self.query.params
  File "/my_project/.venv/lib/python3.6/site-packages/djongo/sql2mongo.py", line 1269, in __init__
    op = ParenthesisOp(0, sqlparse('(' + self.token.value[6:] + ')')[0][0], self.query)
  File "/my_project/.venv/lib/python3.6/site-packages/djongo/sql2mongo.py", line 1347, in __init__
    if op.lhs is None:
AttributeError: 'NoneType' object has no attribute 'lhs'
```

**Comment by nesdis** [comment]
The following operators are yet to be implemented:

        'iexact': 'LIKE %s',
        'contains': 'LIKE BINARY %s',
        'icontains': 'LIKE %s',
        'regex': 'REGEXP BINARY %s',
        'iregex': 'REGEXP %s',
        'startswith': 'LIKE BINARY %s',
        'endswith': 'LIKE BINARY %s',
        'istartswith': 'LIKE %s',
        'iendswith': 'LIKE %s',

**Comment by nesdis** [comment]
Duplicates #29
