### ISSUE TITLE
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet. djongo==1.3.2

### ISSUE THREAD

**Issue by labellson** [nesdis/djongo#400]
#### Description of the issue
Yesterday I updated `djongo` to version `1.3.2` and trying to run the development server with `python manage.py runserver` I got the following exception:

`django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.`

Everything runs fine with version `1.3.1`.

#### Reproducing the issue
I created a new project with a new app, then created a model, and trying to run `python manage.py makemigrations` I run into the same issue.

- **myapp/models.py**
```python
from djongo import models


class Blog(models.Model):
    name = models.CharField(max_length=100)
    tagline = models.TextField()

    class Meta:
        abstract = True


class Entry(models.Model):
    blog = models.EmbeddedField(
        model_container=Blog,
    )

    headline = models.CharField(max_length=255)

```

- Database configuration in **settings.py**
```python
DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'ENFORCE_SCHEMA': True,
        'LOGGING': {
            'version': 1,
            'loggers': {
                'djongo': {
                    'level': 'DEBUG',
                    'propagate': False,
                }
            }
        },
        'NAME': 'myproject',
        'CLIENT': {
            'host': '127.0.0.1',
            'port': 27017,
            'username': 'root',
            'password': '123456'
        }
    }
}
```
- **requeriments.txt**
```
asgiref==3.2.7
bson==0.5.8
dataclasses==0.6
Django==2.2.12
djongo==1.3.2
pymongo==3.10.1
python-dateutil==2.8.1
pytz==2019.3
six==1.14.0
sqlparse==0.2.4
```

#### Traceback
Running `python manage.py makemigrations`
```
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/labellson/.virtualenvs/myproject/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/labellson/.virtualenvs/myproject/lib/python3.8/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/home/labellson/.virtualenvs/myproject/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/labellson/.virtualenvs/myproject/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/labellson/.virtualenvs/myproject/lib/python3.8/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/labellson/Development/Tabichi/djongo/myproject/myapp/models.py", line 12, in <module>
    class Entry(models.Model):
  File "/home/labellson/Development/Tabichi/djongo/myproject/myapp/models.py", line 13, in Entry
    blog = models.EmbeddedField(
  File "/home/labellson/.virtualenvs/myproject/lib/python3.8/site-packages/djongo/models/fields.py", line 225, in __init__
    super().__init__(model_container, *args, **kwargs)
  File "/home/labellson/.virtualenvs/myproject/lib/python3.8/site-packages/djongo/models/fields.py", line 87, in __init__
    self._validate_container()
  File "/home/labellson/.virtualenvs/myproject/lib/python3.8/site-packages/djongo/models/fields.py", line 91, in _validate_container
    for field in self.model_container._meta.get_fields():
  File "/home/labellson/.virtualenvs/myproject/lib/python3.8/site-packages/django/db/models/options.py", line 734, in get_fields
    return self._get_fields(include_parents=include_parents, include_hidden=include_hidden)
  File "/home/labellson/.virtualenvs/myproject/lib/python3.8/site-packages/django/db/models/options.py", line 794, in _get_fields
    all_fields = self._relation_tree
  File "/home/labellson/.virtualenvs/myproject/lib/python3.8/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/labellson/.virtualenvs/myproject/lib/python3.8/site-packages/django/db/models/options.py", line 707, in _relation_tree
    return self._populate_directed_relation_graph()
  File "/home/labellson/.virtualenvs/myproject/lib/python3.8/site-packages/django/db/models/options.py", line 678, in _populate_directed_relation_graph
    all_models = self.apps.get_models(include_auto_created=True)
  File "/home/labellson/.virtualenvs/myproject/lib/python3.8/site-packages/django/apps/registry.py", line 178, in get_models
    self.check_models_ready()
  File "/home/labellson/.virtualenvs/myproject/lib/python3.8/site-packages/django/apps/registry.py", line 140, in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.
```

**Comment by mishrag** [comment]
Yeah, you're right.

I've highlighted the issue here: https://github.com/nesdis/djongo/pull/392#pullrequestreview-395041546

The fix is to change this line to
```python
for field in self.model_container._meta._get_fields(reverse=False):
```

**Comment by labellson** [comment]
Thanks, the fix works perfectly. Should I close this issue ticket??

**Comment by amandeep1991** [comment]
> Yeah, you're right.
> 
> I've highlighted the issue here: [#392 (review)](https://github.com/nesdis/djongo/pull/392#pullrequestreview-395041546)
> 
> The fix is to change this line to
> 
> ```python
> for field in self.model_container._meta._get_fields(reverse=False):
> ```

Hi @mishrag ,

I am facing an issue and it seems you can help me in this:

I have used some older version of djongo and now I want to use the replica-set changes. 

I built my entire application with 'models.ArrayModelField' which is not working with latest version and once I updated the djongo version to 1.3.2, I am also getting the same error.

`  File "C:\ML\code\prod\python\dqi-frontend\src\components\models\request_record.py", line 25, in RequestRecordEntity
    services = models.ArrayField(model_container=IntelligentServicesDetailsEntity, default=[])
  File "C:\ML\installed_tools\anaconda3\envs\dqi-qa\lib\site-packages\djongo-1.3.2-py3.6.egg\djongo\models\fields.py", line 250, in __init__
  File "C:\ML\installed_tools\anaconda3\envs\dqi-qa\lib\site-packages\djongo-1.3.2-py3.6.egg\djongo\models\fields.py", line 106, in __init__
  File "C:\ML\installed_tools\anaconda3\envs\dqi-qa\lib\site-packages\djongo-1.3.2-py3.6.egg\djongo\models\fields.py", line 110, in _validate_container
  File "C:\ML\installed_tools\anaconda3\envs\dqi-qa\lib\site-packages\django\db\models\options.py", line 734, in get_fields
    return self._get_fields(include_parents=include_parents, include_hidden=include_hidden)
  File "C:\ML\installed_tools\anaconda3\envs\dqi-qa\lib\site-packages\django\db\models\options.py", line 794, in _get_fields
    all_fields = self._relation_tree
  File "C:\ML\installed_tools\anaconda3\envs\dqi-qa\lib\site-packages\django\utils\functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\ML\installed_tools\anaconda3\envs\dqi-qa\lib\site-packages\django\db\models\options.py", line 707, in _relation_tree
    return self._populate_directed_relation_graph()
  File "C:\ML\installed_tools\anaconda3\envs\dqi-qa\lib\site-packages\django\db\models\options.py", line 678, in _populate_directed_relation_graph
    all_models = self.apps.get_models(include_auto_created=True)
  File "C:\ML\installed_tools\anaconda3\envs\dqi-qa\lib\site-packages\django\apps\registry.py", line 178, in get_models
    self.check_models_ready()
  File "C:\ML\installed_tools\anaconda3\envs\dqi-qa\lib\site-packages\django\apps\registry.py", line 140, in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.

Process finished with exit code 1
`

Could you please suggest what can I do here.

Thanks,
Aman

**Comment by mishrag** [comment]
Hi @amandeep1991 

> I built my entire application with 'models.ArrayModelField' which is not working with latest version and once I updated the djongo version to 1.3.2, I am also getting the same error.

ArrayModelField has been renamed to ArrayField. You'll have to refactor your code.

As for the second issue, there's a small bug in the latest release. You can modify the code to work with the latest release:

Change line 91 in djongo/models/fields.py to:

```python
for field in self.model_container._meta._get_fields(reverse=False):
```

**Comment by mishrag** [comment]
@labellson Yes, please close the issue if the problem was resolved. I have raised PR https://github.com/nesdis/djongo/pull/401 to address the issue. 

cc @nesdis

**Comment by mishrag** [comment]
@amandeep1991 quick heads-up -- upgrading to 1.3.2 and moving to `ArrayField` will require significant changes to your code base.

**Comment by amandeep1991** [comment]
> @amandeep1991 quick heads-up -- upgrading to 1.3.2 and moving to `ArrayField` will require significant changes to your code base.

Hi Gaurav,

Yeah thanks, I also found the same. I am now figuring out a temporary fix.

Thanks,
Aman

**Comment by shiv-u** [comment]
@mishrag  after making changes as you suggested I am getting following error 
TypeError: get_fields() got an unexpected keyword argument 'reverse'
while running python manage.py makemigrations.

**Comment by mishrag** [comment]
It's _get_fields not get_fields
