### ISSUE TITLE
Models not ready when using embeddedModel

### ISSUE THREAD

**Issue by Jagl257** [nesdis/djongo#417]
#### Model not ready when using djongo

The problem is in app/models.py, I have tried by defining the embedded documents and forms in another python document but it still gives the same error.

#### Python script

```python
   0 from djongo import models                                  
   1 from django import forms                                 
   2 
   3 class Blog(models.Model):
   4     name = models.CharField(max_length=100)
   5     tagline = models.TextField()
   6 
   7     class Meta:
   8         abstract = True
   9 
  10 class BlogForm(forms.ModelForm):
  11     class Meta:
  12         model = Blog
  13         fields = ('name', 'tagline')
  14 
  15 class Author(models.Model):
  16     name = models.CharField(max_length=200)
  17     email = models.EmailField()
  18 
  19     class Meta:
  20         abstract = True
  21 
  22 class AuthorForm(forms.ModelForm):
  23     class Meta:
  24         model = Author 
  25         fields = ('name', 'email')
  26 
  27 class Entry(models.Model):
  28     blog = models.EmbeddedField(
  29         model_container=Blog,
  30         model_form_class=BlogForm
  31     )
  32     name = models.CharField(max_length = 225)
  33     headline = models.CharField(max_length=255)    
  34     authors = models.ArrayField(
  35         model_container=Author,
  36         model_form_class=AuthorForm
  37     )


```

#### Traceback
```shell
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/jagl/.virtualenvs/django-getting-started/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/jagl/.virtualenvs/django-getting-started/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/home/jagl/.virtualenvs/django-getting-started/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/jagl/.virtualenvs/django-getting-started/lib/python3.6/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/jagl/.virtualenvs/django-getting-started/lib/python3.6/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/jagl/Documents/Learning/Programming/Django/django-getting-started/meeting_planner/reports/models.py", line 10, in <module>
    class BlogForm(forms.ModelForm):
NameError: name 'forms' is not defined
(django-getting-started) ➜  meeting_planner git:(master) ✗ python manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/jagl/.virtualenvs/django-getting-started/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/jagl/.virtualenvs/django-getting-started/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/home/jagl/.virtualenvs/django-getting-started/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/jagl/.virtualenvs/django-getting-started/lib/python3.6/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/jagl/.virtualenvs/django-getting-started/lib/python3.6/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/jagl/Documents/Learning/Programming/Django/django-getting-started/meeting_planner/reports/models.py", line 28, in <module>
    class Entry(models.Model):
  File "/home/jagl/Documents/Learning/Programming/Django/django-getting-started/meeting_planner/reports/models.py", line 31, in Entry
    model_form_class=BlogForm
  File "/home/jagl/.virtualenvs/django-getting-started/lib/python3.6/site-packages/djongo/models/fields.py", line 225, in __init__
    super().__init__(model_container, *args, **kwargs)
  File "/home/jagl/.virtualenvs/django-getting-started/lib/python3.6/site-packages/djongo/models/fields.py", line 87, in __init__
    self._validate_container()
  File "/home/jagl/.virtualenvs/django-getting-started/lib/python3.6/site-packages/djongo/models/fields.py", line 91, in _validate_container
    for field in self.model_container._meta.get_fields():
  File "/home/jagl/.virtualenvs/django-getting-started/lib/python3.6/site-packages/django/db/models/options.py", line 734, in get_fields
    return self._get_fields(include_parents=include_parents, include_hidden=include_hidden)
  File "/home/jagl/.virtualenvs/django-getting-started/lib/python3.6/site-packages/django/db/models/options.py", line 794, in _get_fields
    all_fields = self._relation_tree
  File "/home/jagl/.virtualenvs/django-getting-started/lib/python3.6/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/jagl/.virtualenvs/django-getting-started/lib/python3.6/site-packages/django/db/models/options.py", line 707, in _relation_tree
    return self._populate_directed_relation_graph()
  File "/home/jagl/.virtualenvs/django-getting-started/lib/python3.6/site-packages/django/db/models/options.py", line 678, in _populate_directed_relation_graph
    all_models = self.apps.get_models(include_auto_created=True)
  File "/home/jagl/.virtualenvs/django-getting-started/lib/python3.6/site-packages/django/apps/registry.py", line 178, in get_models
    self.check_models_ready()
  File "/home/jagl/.virtualenvs/django-getting-started/lib/python3.6/site-packages/django/apps/registry.py", line 140, in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.

```

**Comment by Jagl257** [comment]
@nesdis

**Comment by devbihari** [comment]
Hey @Jagl257 
In this block
```python
class Blog(models.Model):
     name = models.CharField(max_length=100)
     tagline = models.TextField()

     class Meta:
         abstract = True
class BlogForm(forms.ModelForm):
     class Meta:
         model = Blog
         fields = ('name', 'tagline')
```
```Blog``` should not be abstract. Make sure you update all other classes as well.

_CORRECT_
```python
class Blog(models.Model):
     name = models.CharField(max_length=100)
     tagline = models.TextField()

class BlogForm(forms.ModelForm):
     class Meta:
         model = Blog
         fields = ('name', 'tagline')
```

The documentation is outdated.

I solved a similar issue [here](https://github.com/nesdis/djongo/issues/422#issuecomment-637762041)

**Comment by Jagl257** [comment]
HI @devbihari I hava alredy removed the abstract class but the error is still there.
