### ISSUE TITLE
*.objects.filter() results not compatible with set() / TypeError: unhashable type: 'list'

### ISSUE THREAD

**Issue by techdragon** [nesdis/djongo#42]
#### Running Migrate a second time causes errors within django.contrib.auth.

Creating a model works fine initially and the first migration works ok, creating a schema entry, etc.
```shell
(djongo-experiment)bash-3.2$ ./manage.py makemigrations mongo_example
Migrations for 'mongo_example':
  mongo_example/migrations/0001_initial.py
    - Create model Message
(djongo-experiment)bash-3.2$ ./manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, mongo_example, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying mongo_example.0001_initial... OK
  Applying sessions.0001_initial... OK
```

However if/when I want to add another model to an app. I try running `makemigrations` & `migrate` a second time in order to perform the necessary steps, it fails. 

#### Traceback
```pytb
(djongo-experiment)bash-3.2$ ./manage.py makemigrations mongo_example
Migrations for 'mongo_example':
  mongo_example/migrations/0002_contactlog.py
    - Create model ContactLog
(djongo-experiment)bash-3.2$ ./manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, mongo_example, sessions
Running migrations:
  Applying mongo_example.0002_contactlog... OK
Traceback (most recent call last):
  File "./manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/techdragon/scratch-projects/djongo-experiment/.venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/Users/techdragon/scratch-projects/djongo-experiment/.venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/techdragon/scratch-projects/djongo-experiment/.venv/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/techdragon/scratch-projects/djongo-experiment/.venv/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/Users/techdragon/scratch-projects/djongo-experiment/.venv/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 223, in handle
    self.verbosity, self.interactive, connection.alias, apps=post_migrate_apps, plan=plan,
  File "/Users/techdragon/scratch-projects/djongo-experiment/.venv/lib/python3.6/site-packages/django/core/management/sql.py", line 51, in emit_post_migrate_signal
    **kwargs
  File "/Users/techdragon/scratch-projects/djongo-experiment/.venv/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 178, in send
    for receiver in self._live_receivers(sender)
  File "/Users/techdragon/scratch-projects/djongo-experiment/.venv/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 178, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/Users/techdragon/scratch-projects/djongo-experiment/.venv/lib/python3.6/site-packages/django/contrib/auth/management/__init__.py", line 71, in create_permissions
    "content_type", "codename"
TypeError: unhashable type: 'list'
```

The migration actually completes. Because re-running the code produces this, containing "No migrations to apply."
```pytb
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, mongo_example, sessions
Running migrations:
  No migrations to apply.
Traceback (most recent call last):
  File "./manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/techdragon/scratch-projects/djongo-experiment/.venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/Users/techdragon/scratch-projects/djongo-experiment/.venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/techdragon/scratch-projects/djongo-experiment/.venv/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/techdragon/scratch-projects/djongo-experiment/.venv/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/Users/techdragon/scratch-projects/djongo-experiment/.venv/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 223, in handle
    self.verbosity, self.interactive, connection.alias, apps=post_migrate_apps, plan=plan,
  File "/Users/techdragon/scratch-projects/djongo-experiment/.venv/lib/python3.6/site-packages/django/core/management/sql.py", line 51, in emit_post_migrate_signal
    **kwargs
  File "/Users/techdragon/scratch-projects/djongo-experiment/.venv/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 178, in send
    for receiver in self._live_receivers(sender)
  File "/Users/techdragon/scratch-projects/djongo-experiment/.venv/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 178, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/Users/techdragon/scratch-projects/djongo-experiment/.venv/lib/python3.6/site-packages/django/contrib/auth/management/__init__.py", line 71, in create_permissions
    "content_type", "codename"
TypeError: unhashable type: 'list'
```

#### Extra Information

I debugged the error a bit inside PyCharm to try and see if this had an easy solution. I haven't found an obvious one yet, but I can clarify the code that causes the error is using `set()` on the result of a filter query. For some reason the resulting Queryset object (which is a Queryset object, not a List, according to checking its `type()` in my debugger) is unhashable and I haven't been able to work out the reason for this yet.

https://github.com/django/django/blob/7c81b28ebcaebbc2e5bbca9a73427d81166ce3dc/django/contrib/auth/management/__init__.py#L65-L72
```python
    # Find all the Permissions that have a content_type for a model we're
    # looking for.  We don't need to check for codenames since we already have
    # a list of the ones we're going to create.
    all_perms = set(Permission.objects.using(using).filter(
        content_type__in=ctypes,
    ).values_list(
        "content_type", "codename"
    ))
```

**Comment by nesdis** [comment]
I tried the same thing as u suggested on my machine. in the dummy/models.py created a new model BlogPost2

python manage.py makemigrations dummy

 Output:
 sql_command: SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"
Migrations for 'dummy':
  dummy\migrations\0002_blogpost2.py
    - Create model BlogPost2

 python manage.py migrate
 
<lot of debug info>
.
.
.

OK

I dont face any issue

**Comment by techdragon** [comment]
@nesdis I'll try to narrow down the error, and produce a concrete example. It may be a little tricky to reproduce since it could possibly be an edge case due to the fact I'm testing Djongo's interoperability with an existing MongoDB database with its own existing collections full of documents. I'm using the model Meta options in my second model, using `managed = False` and `db_table = 'contactlog'`.

**Comment by nesdis** [comment]
Hello @techdragon have you tried cloning the [tests](https://github.com/nesdis/djongo/tree/master/tests) folder and reproducing your error. The test folder contains a dummy app which use both contrib and auth modules.

Finally, calling a makemigrations followed by migrate, results in generating a new SQL query of CREATE TABLE. So im not sure what your error is.

If you can reproduce it using the tests folder and clearly mention the modifications you made to it to the dummy app reproduce your error I can help you.

**Comment by techdragon** [comment]
@nesdis I'll try and find some time to build a proper test case/example for this. However it will likely need slightly more complex setup for replication. Are you opposed to the use of [PyTest](https://docs.pytest.org/en/latest/)? Using PyTest's fixtures and plugins will simplify this kind of interoperability testing.

**Comment by nesdis** [comment]
I dont have much experience with pytest. I mainly use unittest. It would take me a while to set it up.

**Comment by techdragon** [comment]
@nesdis I'm happy to do the work adding/integrating PyTest myself when I get to writing this, I was just checking because its a bit presumptuous to make a PR which changes the test runner just to make my life easier. As I said before, I think PyTest will simplify the work to write this kind of test. But its your project the end of the day 😄

**Comment by nesdis** [comment]
Hello @techdragon I don't presume to be an expert at everything! Suggestions and improvements are ALWAYS encouraged! I am sure the power of the community will take this project to a different level altogether. 😄

You are right. At the moment I do not plan to migrate to pytest as it involves a lot more work. unittest does the job for djongo. When I meant using Pytest it was only for the error you are facing. If you can specify your environment (which uses pytest), I can try replicating the same locally to see if i can reproduce it.

**Comment by nesdis** [comment]
Hello @techdragon I have added a section on migrating to djongo using existing DB. Do you follow the steps written there and still face issues?

**Comment by nesdis** [comment]
@techdragon I hope your issue is now solved. Please open a new ticket in case you face an issue

**Comment by SubstructureDek** [comment]
I ran into this error while creating my own Django database connector so in case it's helpful for this project or for anyone else who comes across here - this error can occur if your database library's `cursor.fetchmany` implementation returns an unhashable type (such as a list) as its *inner* sequence. According to PEP 249, `fetchmany` is supposed to "return a sequence of sequences (e.g. a list of tuples)", so returning a list of tuples, a tuple of lists, a tuple of tuples, etc. all conform to the spec, but if the inner sequence is unhashable (such as if you return a list of lists), it causes Django to croak on this line since it tries to create a set of the inner sequence values.
