### ISSUE TITLE
Serializing models with an ArrayModelField

### ISSUE THREAD

**Issue by imochlo** [nesdis/djongo#421]
#### One line description of the issue
Trying to serialze models. New to django serializers. I read in SO this implementation for serializing with ArrayModelField but causes `ValueError: Cannot use ModelSerializer with Abstract Models`.
Is there a known implementation? Need it to eventually create an API. Thank you
 
#### Python script

<The complete python script used to produce the issue.>

**Models.py**

```python
<copy and paste code here>
class Child(models.Model):
    child_name = models.CharField(max_length=120)
    def __str__(self):
        return self.child_name

    class Meta:
        abstract=True

class ChildForm(forms.ModelForm):
    class Meta:
        model=Child
        fields=('child_name',)

class ChildSerializer(serializers.ModelSerializer):
    class Meta:
        model=Child
        fields=('child_name')

class Parent(models.Model):
    objects = models.DjongoManager()
    parent_name = models.CharField(max_length=120)
    child = models.ArrayField(
            model_container=Child,
            model_form_class=ChildForm
    )
    # child = models.EmbeddedField(
        # model_container=Child

class ParentSerializer(serializers.ModelSerializer):
    child = ChildSerializer(many=True, read_only=True)

    class Meta:
        model=Parent
        fields=('parent_name', 'child')

```
**Shell**
``` python
>>> from tracker_lab.models import Parent, Child, ParentSerializer
>>> c = Child(child_name='baby')
>>> p = Parent(parent_name='mama', child=
>>> p = Parent(parent_name='mama', child=[c])
>>> ParentSerializer(p)
```
#### Traceback
<The complete stack trace of the error.>
Traceback (most recent call last):
  File "/home/sam/anaconda3/envs/bkops/lib/python3.7/site-packages/werkzeug/local.py", line 72, in __getattr__
    return self.__storage__[self.__ident_func__()][name]
KeyError: 139817126328128

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sam/anaconda3/envs/bkops/lib/python3.7/site-packages/werkzeug/debug/console.py", line 87, in displayhook
    stream = _local.stream
  File "/home/sam/anaconda3/envs/bkops/lib/python3.7/site-packages/werkzeug/local.py", line 74, in __getattr__
    raise AttributeError(name)
AttributeError: stream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/sam/anaconda3/envs/bkops/lib/python3.7/site-packages/werkzeug/debug/console.py", line 89, in displayhook
    return _displayhook(obj)
  File "/home/sam/.local/lib/python3.7/site-packages/rest_framework/serializers.py", line 537, in __repr__
    return representation.serializer_repr(self, indent=1)
  File "/home/sam/.local/lib/python3.7/site-packages/rest_framework/utils/representation.py", line 84, in serializer_repr
    ret += list_repr(field, indent + 1)
  File "/home/sam/.local/lib/python3.7/site-packages/rest_framework/utils/representation.py", line 99, in list_repr
    if hasattr(child, 'fields'):
  File "/home/sam/anaconda3/envs/bkops/lib/python3.7/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/sam/.local/lib/python3.7/site-packages/rest_framework/serializers.py", line 363, in fields
    for key, value in self.get_fields().items():
  File "/home/sam/.local/lib/python3.7/site-packages/rest_framework/serializers.py", line 1025, in get_fields
    'Cannot use ModelSerializer with Abstract Models.'
ValueError: Cannot use ModelSerializer with Abstract Models.
>

**Comment by devbihari** [comment]
The issue is quite clear ```ValueError: Cannot use ModelSerializer with Abstract Models```
You need to remove 
```python
class Meta:
    abstract=True
```
from 

```python
class Child(models.Model):
    child_name = models.CharField(max_length=120)
    def __str__(self):
        return self.child_name

    class Meta:
        abstract=True
```

A similar issue has been solved [here](https://github.com/nesdis/djongo/issues/422#issuecomment-637762041)

Hope this helps

A.

**Comment by azmathmoosa** [comment]
Is there any proper solution for this?  Can't set abstract to False for EmbeddedField and ArrayField.  Fails to serve the purpose.

**Comment by suraj-rsys** [comment]
You might have already found the solution, but here is what worked for me. as it says "Cannot use ModelSerializer with Abstract Models" just try by inheriting "serializers.Serializer" instead of "serializers.ModelSerializer"
ie: 
YourSerializer(serializers.Serializer):
    # your logic....
