### ISSUE TITLE
AttributeError: module 'djongo.models' has no attribute 'ArrayModelField'

### ISSUE THREAD

**Issue by devbihari** [nesdis/djongo#422]
AttributeError: module 'djongo.models' has no attribute 'ArrayModelField'
#### requirement.txt
```
Django==2.0
Djongo==1.3.1
sqlparse==0.2.4
```
#### Python script
```python
from djongo import models
from django import forms

class Orders(models.Model):
    id = models.CharField(max_length=255)

    class Meta:
        abstract = True

class OrdersForm(forms.ModelForm):
    class Meta:
        model = Orders
        fields = (
            'id',
        )

# Create your models here.
class Customer(models.Model):
    username = models.CharField(max_length=20,null=False, blank=False)
    phone = models.CharField(max_length=10, primary_key=True)
    table = models.CharField(max_length=3, null=False, blank=False)
    orders = models.ArrayModelField(
        model_container=Orders, 
        model_form_class=OrdersForm)
    fav = models.ArrayModelField(
        model_container=Orders, 
        model_form_class=OrdersForm)
    history = models.ArrayModelField(    
        model_container=Orders, 
        model_form_class=OrdersForm)

    objects = models.DjongoManager()
    
    def __str__(self):
        return self.phone

```

#### Traceback
```shell
Traceback (most recent call last):
  File "C:\Users\Amit\anaconda3\lib\site-packages\django\utils\autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Amit\anaconda3\lib\site-packages\django\core\management\commands\runserver.py", line 112, in inner_run
    autoreload.raise_last_exception()
  File "C:\Users\Amit\anaconda3\lib\site-packages\django\utils\autoreload.py", line 248, in raise_last_exception
    raise _exception[1]
  File "C:\Users\Amit\anaconda3\lib\site-packages\django\core\management\__init__.py", line 327, in execute
    autoreload.check_errors(django.setup)()
  File "C:\Users\Amit\anaconda3\lib\site-packages\django\utils\autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Amit\anaconda3\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\Amit\anaconda3\lib\site-packages\django\apps\registry.py", line 112, in populate
    app_config.import_models()
  File "C:\Users\Amit\anaconda3\lib\site-packages\django\apps\config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Users\Amit\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Amit\Documents\BoozimbaApp\django\boozy\app\models.py", line 18, in <module>
    class Customer(models.Model):
  File "C:\Users\Amit\Documents\BoozimbaApp\django\boozy\app\models.py", line 22, in Customer
    orders = models.ArrayModelField(
AttributeError: module 'djongo.models' has no attribute 'ArrayModelField'
```

Any help is appreciated. When I use the latest versions of Django and Djongo I get a message about incompatibility. 

A.

**Comment by devbihari** [comment]
I fixed this issue. 
The Djongo module is working fine. However, the documentation is incorrect. 
I'll explain how to fix this issue so that no-one else wastes time because of inaccurate docs.

- #### ArrayModelField has be changed to _ArrayField_
- #### The class being passed to ```django.form``` should not be abstract.
Example
_INCORRECT_
```python
class Orders(models.Model):
    id = models.CharField(max_length=255)

    class Meta:
        abstract = True

class OrdersForm(forms.ModelForm):
    class Meta:
        model = Orders
        fields = (
            'id',
        )
```
_CORRECT_
```python
class Orders(models.Model):
    id = models.CharField(max_length=255)

class OrdersForm(forms.ModelForm):
    class Meta:
        model = Orders
        fields = (
            'id',
        )
```

These two changes will resolve the issues and you will be able to insert/delete from the database without any issues

**Comment by Invincible166** [comment]
I am getting this error in the code. 

AttributeError: module 'djongo.models' has no attribute 'ArrayField'. If I change it to ArrayModelField then I get a different error "isinstance() arg 2 must be a type or tuple of types"

`from appconf import AppConf
from djongo import models
from django import forms

# Create your models here.
class Words(models.Model):
    duration = models.DurationField() # The duration (in 100-nanosecond units) of the recognized speech in the audio stream. 
    offset = models.TimeField() # Time in nanoseconds at which recognized speech begins in the audio stream

    class Meta:
        abstract = True

class Transcript(models.Model):
    display_transcript = models.TextField()
    itn_transcript = models.TextField()
    confidence = models.ArrayModelField(model_container=models.IntegerField())
    locale = models.CharField(max_length=5)
    sampling_rate = models.IntegerField()
    audio_format = models.CharField(max_length=10)
    service_provider = models.CharField(max_length=100)
    locale_used = models.CharField(max_length=5)
    words = models.ArrayModelField(model_container=Words)# ArrayField(model_container=Words)
    raw_response = models.TextField()
    error_code = models.SmallIntegerField()
    error_message = models.TextField(blank=True)
    processed_on = models.DateTimeField()
    updated_on = models.DateTimeField()
    time_to_process = models.DurationField() # Time to process the transcription request    
    user = models.CharField(max_length=50)
    
    class Meta:
        abstract = True

class Transcription(models.Model):
    request_id = models.CharField(max_length=100)
    question_id = models.BigIntegerField()
    source = models.CharField(max_length=20, choices=[('AMCAT','AMCAT'),('ADHOC','ADHOC')], default='AMCAT')
    transcript = models.EmbeddedModelField(model_container=Transcript)

    objects = models.DjongoManager()`

Any help would be appreciated.

**Comment by AmoriAdefolahan** [comment]
Good morning, I am Emmanuel by name, i want to ask some few question about this i am currently designing a project and this happened to me 


Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\Adefolahan\AppData\Local\Programs\Python\Python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "C:\Users\Adefolahan\AppData\Local\Programs\Python\Python39\lib\threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Adefolahan\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Adefolahan\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\commands\runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "C:\Users\Adefolahan\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\base.py", line 485, in check
    all_issues = checks.run_checks(
  File "C:\Users\Adefolahan\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\checks\registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "C:\Users\Adefolahan\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\checks\urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "C:\Users\Adefolahan\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\checks\urls.py", line 24, in check_resolver
    return check_method()
  File "C:\Users\Adefolahan\AppData\Local\Programs\Python\Python39\lib\site-packages\django\urls\resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "C:\Users\Adefolahan\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Adefolahan\AppData\Local\Programs\Python\Python39\lib\site-packages\django\urls\resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Users\Adefolahan\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Adefolahan\AppData\Local\Programs\Python\Python39\lib\site-packages\django\urls\resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Users\Adefolahan\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\Adefolahan\OneDrive\Documents\LENUX\managmentstudio\managmentstudio\urls.py", line 22, in <module>
    path('', include("Lenux.urls")),
  File "C:\Users\Adefolahan\AppData\Local\Programs\Python\Python39\lib\site-packages\django\urls\conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "C:\Users\Adefolahan\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\Adefolahan\OneDrive\Documents\LENUX\managmentstudio\Lenux\urls.py", line 2, in <module>
    from . import views
  File "C:\Users\Adefolahan\OneDrive\Documents\LENUX\managmentstudio\Lenux\views.py", line 3, in <module>
    from . forms import CreateUserForm,LoginForm
  File "C:\Users\Adefolahan\OneDrive\Documents\LENUX\managmentstudio\Lenux\forms.py", line 26, in <module>
    class ShiftForm(forms.ModelForm):
  File "C:\Users\Adefolahan\AppData\Local\Programs\Python\Python39\lib\site-packages\django\forms\models.py", line 300, in __new__
    fields = fields_for_model(
  File "C:\Users\Adefolahan\AppData\Local\Programs\Python\Python39\lib\site-packages\django\forms\models.py", line 182, in fields_for_model
    opts = model._meta
AttributeError: module 'djongo.models' has no attribute '_meta'

**Comment by AmoriAdefolahan** [comment]
`from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User 

from django import forms

from .models import  models



from django.forms.widgets import PasswordInput, TextInput


class CreateUserForm(UserCreationForm):
    class Meta:

        model = User
        fields = ['username','email','password1', 'password2' ]


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=TextInput())
    password = forms.CharField(widget=PasswordInput())



class ShiftForm(forms.ModelForm):
    class Meta:
        model = models
        fields = '__all__'  

`

**Comment by AmoriAdefolahan** [comment]
this is the code above and I am currently designing the project and I got the error above, if you look at our code looks similar to your code, i do not know if I can get help on this
