### ISSUE TITLE
"Cannot force an update in save() with no primary key" Even After Migration

### ISSUE THREAD

**Issue by RenFinkle** [nesdis/djongo#425]
#### One line description of the issue
When trying to log in to the django admin panel I get "Cannot force an update in save() with no primary key."

#### Python script

Relevant code:

```python
DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'NAME': '[REDACTED]',
        'CLIENT': {
           'host': '[REDACTED]',
        }
    }
}

```

#### Traceback
```
Environment:


Request Method: POST
Request URL: http://127.0.0.1:8000/admin/login/?next=/admin/

Django Version: 3.0.4
Python Version: 3.7.6
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "C:\Users\hp\anaconda3\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\hp\anaconda3\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\hp\anaconda3\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hp\anaconda3\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\hp\anaconda3\lib\site-packages\django\contrib\admin\sites.py", line 407, in login
    return LoginView.as_view(**defaults)(request)
  File "C:\Users\hp\anaconda3\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\hp\anaconda3\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\hp\anaconda3\lib\site-packages\django\views\decorators\debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "C:\Users\hp\anaconda3\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\hp\anaconda3\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\hp\anaconda3\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\hp\anaconda3\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\hp\anaconda3\lib\site-packages\django\contrib\auth\views.py", line 63, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "C:\Users\hp\anaconda3\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\hp\anaconda3\lib\site-packages\django\views\generic\edit.py", line 141, in post
    if form.is_valid():
  File "C:\Users\hp\anaconda3\lib\site-packages\django\forms\forms.py", line 180, in is_valid
    return self.is_bound and not self.errors
  File "C:\Users\hp\anaconda3\lib\site-packages\django\forms\forms.py", line 175, in errors
    self.full_clean()
  File "C:\Users\hp\anaconda3\lib\site-packages\django\forms\forms.py", line 377, in full_clean
    self._clean_form()
  File "C:\Users\hp\anaconda3\lib\site-packages\django\forms\forms.py", line 404, in _clean_form
    cleaned_data = self.clean()
  File "C:\Users\hp\anaconda3\lib\site-packages\django\contrib\auth\forms.py", line 214, in clean
    self.user_cache = authenticate(self.request, username=username, password=password)
  File "C:\Users\hp\anaconda3\lib\site-packages\django\contrib\auth\__init__.py", line 72, in authenticate
    user = backend.authenticate(request, **credentials)
  File "C:\Users\hp\anaconda3\lib\site-packages\django\contrib\auth\backends.py", line 52, in authenticate
    if user.check_password(password) and self.user_can_authenticate(user):
  File "C:\Users\hp\anaconda3\lib\site-packages\django\contrib\auth\base_user.py", line 111, in check_password
    return check_password(raw_password, self.password, setter)
  File "C:\Users\hp\anaconda3\lib\site-packages\django\contrib\auth\hashers.py", line 60, in check_password
    setter(password)
  File "C:\Users\hp\anaconda3\lib\site-packages\django\contrib\auth\base_user.py", line 110, in setter
    self.save(update_fields=["password"])
  File "C:\Users\hp\anaconda3\lib\site-packages\django\contrib\auth\base_user.py", line 66, in save
    super().save(*args, **kwargs)
  File "C:\Users\hp\anaconda3\lib\site-packages\django\db\models\base.py", line 746, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Users\hp\anaconda3\lib\site-packages\django\db\models\base.py", line 784, in save_base
    force_update, using, update_fields,
  File "C:\Users\hp\anaconda3\lib\site-packages\django\db\models\base.py", line 847, in _save_table
    raise ValueError("Cannot force an update in save() with no primary key.")

Exception Type: ValueError at /admin/login/
Exception Value: Cannot force an update in save() with no primary key.
```

**Comment by RenFinkle** [comment]
Resolved by following: https://github.com/nesdis/djongo/issues/3#issuecomment-638643543
