### ISSUE TITLE
Support for custom User models

### ISSUE THREAD

**Issue by ghadjigeorghiou** [nesdis/djongo#427]
I am trying to create my own custom user model instead of using the one provided by Django. However, I still want to use the validation methods and support provided. My understanding from the Djongo documentation is that to create a model we should import models from djongo and use class CustomUser(models.Model). However, to use the validation methods provided in the Django documentation is recommended to extend either the AbstractBaseUser or the AbstractUser classes. Are these classes provided by Djongo too? I couldn't find them in the documentation. If they are not provided, if I import them from django.contrib.auth.models is that consistent with Djongo?

Thanks,
George

**Comment by pikotrek** [comment]
You can freely use standard Django AbstractBaseUser: https://stackoverflow.com/questions/52020493/django-user-authentication-with-custom-model-and-mongo-db

**Comment by adarshsavalagi1** [comment]
no its causing an issue

Traceback (most recent call last):
  File "C:\Users\adars\OneDrive\Desktop\Envision\envision\manage.py", line 22, in <module>
    main()
  File "C:\Users\adars\OneDrive\Desktop\Envision\envision\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\adars\OneDrive\Desktop\Envision\envision\venv\Lib\site-packages\django\core\management\__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "C:\Users\adars\OneDrive\Desktop\Envision\envision\venv\Lib\site-packages\django\core\management\__init__.py", line 420, in execute
    django.setup()
  File "C:\Users\adars\OneDrive\Desktop\Envision\envision\venv\Lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\adars\OneDrive\Desktop\Envision\envision\venv\Lib\site-packages\django\apps\registry.py", line 116, in populate
    app_config.import_models()
  File "C:\Users\adars\OneDrive\Desktop\Envision\envision\venv\Lib\site-packages\django\apps\config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\adars\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\adars\OneDrive\Desktop\Envision\envision\core\models.py", line 28, in <module>
    class Department(models.Model):
  File "C:\Users\adars\OneDrive\Desktop\Envision\envision\core\models.py", line 30, in Department
    login = models.EmbeddedField(model_container=CustomUser)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\adars\OneDrive\Desktop\Envision\envision\venv\Lib\site-packages\djongo\models\fields.py", line 273, in __init__
    super().__init__(model_container, *args, **kwargs)
  File "C:\Users\adars\OneDrive\Desktop\Envision\envision\venv\Lib\site-packages\djongo\models\fields.py", line 112, in __init__
    self._validate_container()
  File "C:\Users\adars\OneDrive\Desktop\Envision\envision\venv\Lib\site-packages\djongo\models\fields.py", line 120, in _validate_container
    raise ValidationError(
django.core.exceptions.ValidationError: ['Field "core.CustomUser.groups" of model container:"<class \'core.models.CustomUser\'>" cannot be of type "<class \'django.db.models.fields.related.ManyToManyField\'>"']
