### ISSUE TITLE
Failed SQL

### ISSUE THREAD

**Issue by RenFinkle** [nesdis/djongo#432]
#### One line description of the issue
Migration with [pinax-messages](https://github.com/pinax/pinax-messages) fails due to SQL error.

#### Python script

<The complete python script used to produce the issue.>
No script created, just installed pinax-messages 3.0.0., added pinax.messages to INSTALLED_APPS and ran: python manage.py makemigrations and then python manage.py migrate

#### Traceback
```
Traceback (most recent call last):
  File "C:\Users\hp\anaconda3\lib\site-packages\djongo\sql2mongo\query.py", line 842, in parse
    return handler(self, statement)
  File "C:\Users\hp\anaconda3\lib\site-packages\djongo\sql2mongo\query.py", line 868, in _alter
    query = AlterQuery(self.db, self.connection_properties, sm, self._params)
  File "C:\Users\hp\anaconda3\lib\site-packages\djongo\sql2mongo\query.py", line 424, in __init__
    super().__init__(*args)
  File "C:\Users\hp\anaconda3\lib\site-packages\djongo\sql2mongo\query.py", line 83, in __init__
    super().__init__(*args)
  File "C:\Users\hp\anaconda3\lib\site-packages\djongo\sql2mongo\query.py", line 61, in __init__
    self.parse()
  File "C:\Users\hp\anaconda3\lib\site-packages\djongo\sql2mongo\query.py", line 434, in parse
    self._add(statement)
  File "C:\Users\hp\anaconda3\lib\site-packages\djongo\sql2mongo\query.py", line 594, in _add
    raise SQLDecodeError
djongo.exceptions.SQLDecodeError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\hp\anaconda3\lib\site-packages\djongo\cursor.py", line 56, in execute
    params)
  File "C:\Users\hp\anaconda3\lib\site-packages\djongo\sql2mongo\query.py", line 769, in __init__
    self._query = self.parse()
  File "C:\Users\hp\anaconda3\lib\site-packages\djongo\sql2mongo\query.py", line 864, in parse
    raise exe from e
djongo.exceptions.SQLDecodeError: FAILED SQL: ALTER TABLE "pinax_messages_message" ADD COLUMN "thread_id" int NOT NULL
Params: []
Version: 1.3.2

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\hp\anaconda3\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\hp\anaconda3\lib\site-packages\djongo\cursor.py", line 59, in execute
    raise db_exe from e
djongo.database.DatabaseError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\hp\anaconda3\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Users\hp\anaconda3\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\hp\anaconda3\lib\site-packages\django\core\management\base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\hp\anaconda3\lib\site-packages\django\core\management\base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "C:\Users\hp\anaconda3\lib\site-packages\django\core\management\base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "C:\Users\hp\anaconda3\lib\site-packages\django\core\management\commands\migrate.py", line 233, in handle
    fake_initial=fake_initial,
  File "C:\Users\hp\anaconda3\lib\site-packages\django\db\migrations\executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "C:\Users\hp\anaconda3\lib\site-packages\django\db\migrations\executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "C:\Users\hp\anaconda3\lib\site-packages\django\db\migrations\executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "C:\Users\hp\anaconda3\lib\site-packages\django\db\migrations\migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "C:\Users\hp\anaconda3\lib\site-packages\django\db\migrations\operations\fields.py", line 112, in database_forwards
    field,
  File "C:\Users\hp\anaconda3\lib\site-packages\django\db\backends\base\schema.py", line 480, in add_field
    self.execute(sql, params)
  File "C:\Users\hp\anaconda3\lib\site-packages\django\db\backends\base\schema.py", line 142, in execute
    cursor.execute(sql, params)
  File "C:\Users\hp\anaconda3\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "C:\Users\hp\anaconda3\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\hp\anaconda3\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\hp\anaconda3\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\hp\anaconda3\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\hp\anaconda3\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\hp\anaconda3\lib\site-packages\djongo\cursor.py", line 59, in execute
    raise db_exe from e
django.db.utils.DatabaseError
```

**Comment by khoa698** [comment]
I am facing the same issue where "ALTER TABLE" commands throws an error, has anyone found a fix to this issue?
