### ISSUE TITLE
Not implemented alter command

### ISSUE THREAD

**Issue by NOBLEGG** [nesdis/djongo#433]
#### One line description of the issue
I changed archetype from TextField to BooleanField. makemigrations worked well, but migration failed.

#### Python script

<The complete python script used to produce the issue.>

```python
# migration file
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('api', '0005_opinion_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='recommend_card',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opinion',
            name='recommend_relic',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opinion',
            name='title',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='opinion',
            name='archetype',
            field=models.BooleanField(default=False),
        ),
    ]

# models.py before
class Opinion(models.Model):
    archetype = models.TextField()

# models.py after
class Opinion(models.Model):
    archetype = models.BooleanField(default=False)
    title = models.CharField(max_length=50)
    recommend_card = models.TextField()
    recommend_relic = models.TextField()

```

#### Traceback
Traceback (most recent call last):
  File "C:\Users\bornn\Anaconda3\envs\RPS\lib\site-packages\djongo\sql2mongo\query.py", line 842, in parse
    return handler(self, statement)
  File "C:\Users\bornn\Anaconda3\envs\RPS\lib\site-packages\djongo\sql2mongo\query.py", line 868, in _alter
    query = AlterQuery(self.db, self.connection_properties, sm, self._params)
  File "C:\Users\bornn\Anaconda3\envs\RPS\lib\site-packages\djongo\sql2mongo\query.py", line 424, in __init__
    super().__init__(*args)
  File "C:\Users\bornn\Anaconda3\envs\RPS\lib\site-packages\djongo\sql2mongo\query.py", line 83, in __init__
    super().__init__(*args)
  File "C:\Users\bornn\Anaconda3\envs\RPS\lib\site-packages\djongo\sql2mongo\query.py", line 61, in __init__
    self.parse()
  File "C:\Users\bornn\Anaconda3\envs\RPS\lib\site-packages\djongo\sql2mongo\query.py", line 440, in parse
    self._alter(statement)
  File "C:\Users\bornn\Anaconda3\envs\RPS\lib\site-packages\djongo\sql2mongo\query.py", line 499, in _alter
    raise SQLDecodeError(f'Unknown token: {tok}')
djongo.exceptions.SQLDecodeError: Unknown token: TYPE

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\bornn\Anaconda3\envs\RPS\lib\site-packages\djongo\cursor.py", line 51, in execute
    self.result = Query(
  File "C:\Users\bornn\Anaconda3\envs\RPS\lib\site-packages\djongo\sql2mongo\query.py", line 769, in __init__
    self._query = self.parse()
  File "C:\Users\bornn\Anaconda3\envs\RPS\lib\site-packages\djongo\sql2mongo\query.py", line 864, in parse
    raise exe from e
djongo.exceptions.SQLDecodeError: FAILED SQL: ALTER TABLE "api_opinion" ALTER COLUMN "archetype" TYPE bool
Params: []
Version: 1.3.2

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\bornn\Anaconda3\envs\RPS\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\bornn\Anaconda3\envs\RPS\lib\site-packages\djongo\cursor.py", line 59, in execute
    raise db_exe from e
djongo.database.DatabaseError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\bornn\Anaconda3\envs\RPS\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "C:\Users\bornn\Anaconda3\envs\RPS\lib\site-packages\django\core\management\__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\bornn\Anaconda3\envs\RPS\lib\site-packages\django\core\management\base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\bornn\Anaconda3\envs\RPS\lib\site-packages\django\core\management\base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "C:\Users\bornn\Anaconda3\envs\RPS\lib\site-packages\django\core\management\base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "C:\Users\bornn\Anaconda3\envs\RPS\lib\site-packages\django\core\management\commands\migrate.py", line 232, in handle
    post_migrate_state = executor.migrate(
  File "C:\Users\bornn\Anaconda3\envs\RPS\lib\site-packages\django\db\migrations\executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "C:\Users\bornn\Anaconda3\envs\RPS\lib\site-packages\django\db\migrations\executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "C:\Users\bornn\Anaconda3\envs\RPS\lib\site-packages\django\db\migrations\executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "C:\Users\bornn\Anaconda3\envs\RPS\lib\site-packages\django\db\migrations\migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "C:\Users\bornn\Anaconda3\envs\RPS\lib\site-packages\django\db\migrations\operations\fields.py", line 249, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "C:\Users\bornn\Anaconda3\envs\RPS\lib\site-packages\django\db\backends\base\schema.py", line 534, in alter_field
    self._alter_field(model, old_field, new_field, old_type, new_type,
  File "C:\Users\bornn\Anaconda3\envs\RPS\lib\site-packages\django\db\backends\base\schema.py", line 680, in _alter_field
    self.execute(
  File "C:\Users\bornn\Anaconda3\envs\RPS\lib\site-packages\django\db\backends\base\schema.py", line 137, in execute
    cursor.execute(sql, params)
  File "C:\Users\bornn\Anaconda3\envs\RPS\lib\site-packages\django\db\backends\utils.py", line 99, in execute
    return super().execute(sql, params)
  File "C:\Users\bornn\Anaconda3\envs\RPS\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\bornn\Anaconda3\envs\RPS\lib\site-packages\django\db\backends\utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\bornn\Anaconda3\envs\RPS\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\bornn\Anaconda3\envs\RPS\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\bornn\Anaconda3\envs\RPS\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\bornn\Anaconda3\envs\RPS\lib\site-packages\djongo\cursor.py", line 59, in execute
    raise db_exe from e
django.db.utils.DatabaseError

**Comment by TomaszKolek** [comment]
I think you can simply skip any alter migration (probably you need to remove them manually)
As mongodb is schemaless you do not need to do alter operation.

**Comment by NOBLEGG** [comment]
@TomaszKolek Yes, eventually I just deleted a field and recreated it instead of altering it.
