### ISSUE TITLE
djongo.exceptions.SQLDecodeError with Django Celery Beat migrate

### ISSUE THREAD

**Issue by shubham-rath** [nesdis/djongo#444]
#### One line description of the issue
Facing djongo.exceptions.SQLDecodeError when trying to migrate for django_celery_beat
Django==2.2.5
django-celery-beat==1.1.0
djongo==1.3.3

#### Python script
python manage.py migrate (No makemigrations, as only Django Tables need to be created)

#### Traceback
$ python manage.py migrate                                                                                                      
Running in dev mode
Storing access token locally
Access token stored locally
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, django_celery_beat, sessions
Running migrations:
This version of djongo does not support "NULL, NOT NULL column validation check" fully. Visit https://www.patreon.com/nesdis
  Applying contenttypes.0001_initial...This version of djongo does not support "schema validation using CONSTRAINT" fully. Visit https://www.patreon.com/nesdis
 OK
  Applying auth.0001_initial...This version of djongo does not support "schema validation using KEY" fully. Visit https://www.patreon.com/nesdis
This version of djongo does not support "schema validation using REFERENCES" fully. Visit https://www.patreon.com/nesdis
 OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name...This version of djongo does not support "COLUMN DROP NOT NULL " fully. Visit https://www.patreon.com/nesdis
This version of djongo does not support "DROP CASCADE" fully. Visit https://www.patreon.com/nesdis
 OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying django_celery_beat.0001_initial... OK
Not implemented alter command for SQL ALTER TABLE "django_celery_beat_periodictask" ADD COLUMN "solar_id" int NULL
  Applying django_celery_beat.0002_auto_20161118_0346...Traceback (most recent call last):
  File "/Users/mmt8475/PycharmProjects/canon/venv/lib/python3.7/site-packages/djongo/cursor.py", line 56, in execute
    params)
  File "/Users/mmt8475/PycharmProjects/canon/venv/lib/python3.7/site-packages/djongo/sql2mongo/query.py", line 783, in __init__
    self._query = self.parse()
  File "/Users/mmt8475/PycharmProjects/canon/venv/lib/python3.7/site-packages/djongo/sql2mongo/query.py", line 875, in parse
    raise e
  File "/Users/mmt8475/PycharmProjects/canon/venv/lib/python3.7/site-packages/djongo/sql2mongo/query.py", line 856, in parse
    return handler(self, statement)
  File "/Users/mmt8475/PycharmProjects/canon/venv/lib/python3.7/site-packages/djongo/sql2mongo/query.py", line 888, in _alter
    query = AlterQuery(self.db, self.connection_properties, sm, self._params)
  File "/Users/mmt8475/PycharmProjects/canon/venv/lib/python3.7/site-packages/djongo/sql2mongo/query.py", line 425, in __init__
    super().__init__(*args)
  File "/Users/mmt8475/PycharmProjects/canon/venv/lib/python3.7/site-packages/djongo/sql2mongo/query.py", line 84, in __init__
    super().__init__(*args)
  File "/Users/mmt8475/PycharmProjects/canon/venv/lib/python3.7/site-packages/djongo/sql2mongo/query.py", line 62, in __init__
    self.parse()
  File "/Users/mmt8475/PycharmProjects/canon/venv/lib/python3.7/site-packages/djongo/sql2mongo/query.py", line 435, in parse
    self._add(statement)
  File "/Users/mmt8475/PycharmProjects/canon/venv/lib/python3.7/site-packages/djongo/sql2mongo/query.py", line 599, in _add
    err_sub_sql=statement)
djongo.exceptions.SQLDecodeError: 
        Keyword: int
        Sub SQL: ALTER TABLE "django_celery_beat_periodictask" ADD COLUMN "solar_id" int NULL
        FAILED SQL: ('ALTER TABLE "django_celery_beat_periodictask" ADD COLUMN "solar_id" int NULL',)
        Params: ([],)
        Version: 1.3.3
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/Users/mmt8475/PycharmProjects/canon/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/mmt8475/PycharmProjects/canon/venv/lib/python3.7/site-packages/djongo/cursor.py", line 59, in execute
    raise db_exe from e
djongo.database.DatabaseError
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/Users/mmt8475/PycharmProjects/canon/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Users/mmt8475/PycharmProjects/canon/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/mmt8475/PycharmProjects/canon/venv/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/mmt8475/PycharmProjects/canon/venv/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/Users/mmt8475/PycharmProjects/canon/venv/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/Users/mmt8475/PycharmProjects/canon/venv/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 234, in handle
    fake_initial=fake_initial,
  File "/Users/mmt8475/PycharmProjects/canon/venv/lib/python3.7/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/Users/mmt8475/PycharmProjects/canon/venv/lib/python3.7/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/Users/mmt8475/PycharmProjects/canon/venv/lib/python3.7/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/Users/mmt8475/PycharmProjects/canon/venv/lib/python3.7/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/Users/mmt8475/PycharmProjects/canon/venv/lib/python3.7/site-packages/django/db/migrations/operations/fields.py", line 112, in database_forwards
    field,
  File "/Users/mmt8475/PycharmProjects/canon/venv/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 447, in add_field
    self.execute(sql, params)
  File "/Users/mmt8475/PycharmProjects/canon/venv/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 137, in execute
    cursor.execute(sql, params)
  File "/Users/mmt8475/PycharmProjects/canon/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/Users/mmt8475/PycharmProjects/canon/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/mmt8475/PycharmProjects/canon/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/mmt8475/PycharmProjects/canon/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/mmt8475/PycharmProjects/canon/venv/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/mmt8475/PycharmProjects/canon/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/mmt8475/PycharmProjects/canon/venv/lib/python3.7/site-packages/djongo/cursor.py", line 59, in execute
    raise db_exe from e
django.db.utils.DatabaseError

**Comment by shubham-rath** [comment]
Fixed it by downgrading `Djongo==1.3.1`
