### ISSUE TITLE
Error on filtering EmbeddedField django.core.exceptions.ValidationError

### ISSUE THREAD

**Issue by emanuelebosetti** [nesdis/djongo#470]
#### One line description of the issue
Error on try to filter on Embedded object with Django 3.0.5 and djongo=1.3.3
I've this model:
#### Python script

<The complete python script used to produce the issue.>

```python
class Company(models.Model):
    idrs = models.CharField(max_length=100)
    codicli = models.CharField(max_length=100)

    class Meta:
        abstract = True


class Survey(models.Model):
    _id = models.ObjectIdField()
    company = models.EmbeddedField(
        model_container=Company
    )
    create_timestamp = models.DateTimeField(auto_now=True)
    type = models.CharField(choices=SURVEY_TYPE, max_length=3)

```
When I try to filter on an EmbeddedField field like this:
```python
class CustomerSurveyViewSet(SurveyViewSet):

    def get_queryset(self):
        qs = super().get_queryset().filter(company={'codicli': self.kwargs['codicli']})
        return qs
```
i get this exception:
#### Traceback
Traceback (most recent call last):
  File "C:\Users\bosettie\PycharmProjects\survey_importer\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\bosettie\PycharmProjects\survey_importer\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\bosettie\PycharmProjects\survey_importer\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\bosettie\PycharmProjects\survey_importer\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\bosettie\PycharmProjects\survey_importer\venv\lib\site-packages\rest_framework\viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\bosettie\PycharmProjects\survey_importer\venv\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\bosettie\PycharmProjects\survey_importer\venv\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\bosettie\PycharmProjects\survey_importer\venv\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "C:\Users\bosettie\PycharmProjects\survey_importer\venv\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\bosettie\PycharmProjects\survey_importer\venv\lib\site-packages\rest_framework\mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "C:\Users\bosettie\PycharmProjects\survey_importer\src\survey_receiver\views.py", line 45, in get_queryset
    qs = super().get_queryset().filter(company={'codicli': self.kwargs['codicli']})
  File "C:\Users\bosettie\PycharmProjects\survey_importer\venv\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Users\bosettie\PycharmProjects\survey_importer\venv\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "C:\Users\bosettie\PycharmProjects\survey_importer\venv\lib\site-packages\django\db\models\sql\query.py", line 1350, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\bosettie\PycharmProjects\survey_importer\venv\lib\site-packages\django\db\models\sql\query.py", line 1381, in _add_q
    check_filterable=check_filterable,
  File "C:\Users\bosettie\PycharmProjects\survey_importer\venv\lib\site-packages\django\db\models\sql\query.py", line 1311, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Users\bosettie\PycharmProjects\survey_importer\venv\lib\site-packages\django\db\models\sql\query.py", line 1165, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "C:\Users\bosettie\PycharmProjects\survey_importer\venv\lib\site-packages\django\db\models\lookups.py", line 22, in __init__
    self.rhs = self.get_prep_lookup()
  File "C:\Users\bosettie\PycharmProjects\survey_importer\venv\lib\site-packages\django\db\models\lookups.py", line 72, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "C:\Users\bosettie\PycharmProjects\survey_importer\venv\lib\site-packages\djongo\models\fields.py", line 223, in get_prep_value
    value)
  File "C:\Users\bosettie\PycharmProjects\survey_importer\venv\lib\site-packages\djongo\models\fields.py", line 154, in _value_thru_fields
    raise ValidationError(str(e))
django.core.exceptions.ValidationError: ['{\'idrs\': [\'Value for field "survey_receiver.Company.idrs" not supplied\']}']

**Comment by cadeljones** [comment]
It seems you need to pass all the fields of your embedded model in the filter in order to resolve the error.

I am also running into this issue and wondering why its not working as expected.

**Comment by rgilkey** [comment]
@cadeljones This appears is fixed in the `master` branch, there just hasn't been a PyPI release in a bit.  You can install the module from there as an interim solution or via a pinned ref in pipenv/pip:

```
djongo = {git="https://github.com/nesdis/djongo.git", ref="5c2ab70b614ef4fbeac58e3a92f838b1b8c4c5df"}
```
