### ISSUE TITLE
Can not create Embedded field or Array field entry from Admin

### ISSUE THREAD

**Issue by Akash3194** [nesdis/djongo#472]
#### With the version 1.3.3 of djongo. I Have created models as it is written in documentations. It is working well from shell but then I tried it from the django Admin panel and I filled entries, when i clicked on save button, an error pop's up which says. None object has not attribute 'attname'. 
Django admin was working perfect with Djongo 1.3.1.

#### Python script

<The complete python script used to produce the issue.>

```python
from djongo import models


class Blog(models.Model):
    name = models.CharField(max_length=100)
    tagline = models.TextField()

    class Meta:
        abstract = True


class MetaData(models.Model):
    pub_date = models.DateField()
    mod_date = models.DateField()
    n_pingbacks = models.IntegerField()
    rating = models.IntegerField()

    class Meta:
        abstract = True


class Author(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField()

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class Hentry(models.Model):
    blog = models.EmbeddedField(
        model_container=Blog,
    )
    meta_data = models.EmbeddedField(
        model_container=MetaData,
    )

    headline = models.CharField(max_length=255)
    body_text = models.TextField()

    authors = models.ArrayField(
        model_container=Author,
    )
    n_comments = models.IntegerField()

    def __str__(self):
        return self.headline

```

#### Traceback
Traceback (most recent call last):
  File "C:\Users\Akash\PycharmProjects\mongo\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Akash\PycharmProjects\mongo\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Akash\PycharmProjects\mongo\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Akash\PycharmProjects\mongo\venv\lib\site-packages\django\contrib\admin\options.py", line 606, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\Akash\PycharmProjects\mongo\venv\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Akash\PycharmProjects\mongo\venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Akash\PycharmProjects\mongo\venv\lib\site-packages\django\contrib\admin\sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\Akash\PycharmProjects\mongo\venv\lib\site-packages\django\contrib\admin\options.py", line 1645, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "C:\Users\Akash\PycharmProjects\mongo\venv\lib\site-packages\django\utils\decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\Akash\PycharmProjects\mongo\venv\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Akash\PycharmProjects\mongo\venv\lib\site-packages\django\contrib\admin\options.py", line 1529, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\Akash\PycharmProjects\mongo\venv\lib\site-packages\django\contrib\admin\options.py", line 1565, in _changeform_view
    form_validated = form.is_valid()
  File "C:\Users\Akash\PycharmProjects\mongo\venv\lib\site-packages\django\forms\forms.py", line 185, in is_valid
    return self.is_bound and not self.errors
  File "C:\Users\Akash\PycharmProjects\mongo\venv\lib\site-packages\django\forms\forms.py", line 180, in errors
    self.full_clean()
  File "C:\Users\Akash\PycharmProjects\mongo\venv\lib\site-packages\django\forms\forms.py", line 383, in full_clean
    self._post_clean()
  File "C:\Users\Akash\PycharmProjects\mongo\venv\lib\site-packages\django\forms\models.py", line 403, in _post_clean
    self.instance.full_clean(exclude=exclude, validate_unique=False)
  File "C:\Users\Akash\PycharmProjects\mongo\venv\lib\site-packages\django\db\models\base.py", line 1184, in full_clean
    self.clean_fields(exclude=exclude)
  File "C:\Users\Akash\PycharmProjects\mongo\venv\lib\site-packages\django\db\models\base.py", line 1226, in clean_fields
    setattr(self, f.attname, f.clean(raw_value, self))
  File "C:\Users\Akash\PycharmProjects\mongo\venv\lib\site-packages\django\db\models\fields\__init__.py", line 629, in clean
    value = self.to_python(value)
  File "C:\Users\Akash\PycharmProjects\mongo\venv\lib\site-packages\djongo\models\fields.py", line 242, in to_python
    f'Value: {value} must be an instance of {self.base_type}')
  File "C:\Users\Akash\PycharmProjects\mongo\venv\lib\site-packages\django\db\models\base.py", line 522, in __str__
    return '%s object (%s)' % (self.__class__.__name__, self.pk)
  File "C:\Users\Akash\PycharmProjects\mongo\venv\lib\site-packages\django\db\models\base.py", line 572, in _get_pk_val
    return getattr(self, meta.pk.attname)
AttributeError: 'NoneType' object has no attribute 'attname'

**Comment by A-Kamaee** [comment]
I have same problem.

**Comment by jasja1** [comment]
+1, I will wait bug fixes in the new version

**Comment by AlanKokoiev** [comment]
+1

**Comment by azmathmoosa** [comment]
+ 1

**Comment by hossy13** [comment]
File "/home/hossy/Documents/projects/noteabi/venv/lib/python3.8/site-packages/django/forms/models.py", line 309, in __init__
    object_data = model_to_dict(instance, opts.fields, opts.exclude)
  File "/home/hossy/Documents/projects/noteabi/venv/lib/python3.8/site-packages/django/forms/models.py", line 86, in model_to_dict
    opts = instance._meta
AttributeError: 'dict' object has no attribute '_meta'

i have this error too

**Comment by paramjeet01** [comment]
add this to your code in your class
def __str__(self):
        return self.name

**Comment by KGuzikowski** [comment]
> add this to your code in your class
> def **str**(self):
> return self.name

Which class?
