### ISSUE TITLE
Error migration with django_celery_results package

### ISSUE THREAD

**Issue by aceaceace30** [nesdis/djongo#482]
Im having issues when i try to use the django_celery_result(1.2.1) package  on migration here is the error log:

`djongo.exceptions.SQLDecodeError: FAILED SQL: UPDATE "django_celery_results_taskresult" SET "date_created" = "django_celery_results_taskresult"."date_done"`

Here is the complete traceback:

`Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\Ababao\Projects\valens\pwc-benchmarking\venv\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Users\Ababao\Projects\valens\pwc-benchmarking\venv\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\Ababao\Projects\valens\pwc-benchmarking\venv\lib\site-packages\django\core\management\base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\Ababao\Projects\valens\pwc-benchmarking\venv\lib\site-packages\django\core\management\base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "C:\Users\Ababao\Projects\valens\pwc-benchmarking\venv\lib\site-packages\django\core\management\base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "C:\Users\Ababao\Projects\valens\pwc-benchmarking\venv\lib\site-packages\django\core\management\commands\migrate.py", line 233, in handle
    fake_initial=fake_initial,
  File "C:\Users\Ababao\Projects\valens\pwc-benchmarking\venv\lib\site-packages\django\db\migrations\executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "C:\Users\Ababao\Projects\valens\pwc-benchmarking\venv\lib\site-packages\django\db\migrations\executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "C:\Users\Ababao\Projects\valens\pwc-benchmarking\venv\lib\site-packages\django\db\migrations\executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "C:\Users\Ababao\Projects\valens\pwc-benchmarking\venv\lib\site-packages\django\db\migrations\migration.py", line 121, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "C:\Users\Ababao\Projects\valens\pwc-benchmarking\venv\lib\site-packages\django\db\migrations\operations\special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "C:\Users\Ababao\Projects\valens\pwc-benchmarking\venv\lib\site-packages\django_celery_results\migrations\0006_taskresult_date_created.py", line 17, in copy_date_done_to_date_created
    date_created=models.F('date_done')
  File "C:\Users\Ababao\Projects\valens\pwc-benchmarking\venv\lib\site-packages\django\db\models\query.py", line 752, in update
    rows = query.get_compiler(self.db).execute_sql(CURSOR)
  File "C:\Users\Ababao\Projects\valens\pwc-benchmarking\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1499, in execute_sql
    cursor = super().execute_sql(result_type)
  File "C:\Users\Ababao\Projects\valens\pwc-benchmarking\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1151, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Ababao\Projects\valens\pwc-benchmarking\venv\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "C:\Users\Ababao\Projects\valens\pwc-benchmarking\venv\lib\site-packages\sentry_sdk\integrations\django\__init__.py", line 489, in execute
    return real_execute(self, sql, params)
  File "C:\Users\Ababao\Projects\valens\pwc-benchmarking\venv\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\Ababao\Projects\valens\pwc-benchmarking\venv\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Ababao\Projects\valens\pwc-benchmarking\venv\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Ababao\Projects\valens\pwc-benchmarking\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Ababao\Projects\valens\pwc-benchmarking\venv\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Ababao\Projects\valens\pwc-benchmarking\venv\lib\site-packages\djongo\cursor.py", line 59, in execute
    raise db_exe from e
django.db.utils.DatabaseError
`

**Comment by aceaceace30** [comment]
I hope this could be noticed and addressed, Thank you.

**Comment by aceaceace30** [comment]
> Did you ever solve this issue?

@YM2132 sadly, no.

**Comment by lightflyer** [comment]
try this command:
python manage.py migrate --fake
this is worked for me, hope it is useful for u
