### ISSUE TITLE
Raises SQL decode error for parenthesis having expression.

### ISSUE THREAD

**Issue by shaikhAbuzar** [nesdis/djongo#500]
#### One line description of the issue
The Failed Query contains an expression in the parenthesis like ("field_1" * "field_2") because of this it throws value error for the following [line]( https://meet.google.com/linkredirect?authuser=0&dest=https%3A%2F%2Fgithub.com%2Fnesdis%2Fdjongo%2Fblob%2Fb31d88278b94bf18b59a08e688a6d9490b8467f5%2Fdjongo%2Fsql2mongo%2Fsql_tokens.py%23L39)
#### Python script

<The complete python script used to produce the issue.>

```python
entries = CostTable.objects.filter(sheet_no=cost_sheet).using('central_db')
external_data = entries.filter(is_external=True).values('tower').annotate(var=ExpressionWrapper(F('rate_1') * F('unit_1'), output_field=FloatField()))
```

#### Traceback
Internal Server Error: /dashboard/costing/18/
Traceback (most recent call last):
  File "C:\Users\Shaikh Abuzar\Envs\django\lib\site-packages\djongo\sql2mongo\query.py", line 856, in parse
    return handler(self, statement)
  File "C:\Users\Shaikh Abuzar\Envs\django\lib\site-packages\djongo\sql2mongo\query.py", line 932, in _select
    return SelectQuery(self.db, self.connection_properties, sm, self._params)
  File "C:\Users\Shaikh Abuzar\Envs\django\lib\site-packages\djongo\sql2mongo\query.py", line 116, in __init__
    super().__init__(*args)
  File "C:\Users\Shaikh Abuzar\Envs\django\lib\site-packages\djongo\sql2mongo\query.py", line 62, in __init__
    self.parse()
  File "C:\Users\Shaikh Abuzar\Envs\django\lib\site-packages\djongo\sql2mongo\query.py", line 123, in parse
    self.selected_columns = ColumnSelectConverter(self, statement)
  File "C:\Users\Shaikh Abuzar\Envs\django\lib\site-packages\djongo\sql2mongo\converters.py", line 44, in __init__
    super().__init__(query, statement)
  File "C:\Users\Shaikh Abuzar\Envs\django\lib\site-packages\djongo\sql2mongo\converters.py", line 27, in __init__
    self.parse()
  File "C:\Users\Shaikh Abuzar\Envs\django\lib\site-packages\djongo\sql2mongo\converters.py", line 53, in parse
    for sql_token in SQLToken.tokens2sql(tok, self.query):
  File "C:\Users\Shaikh Abuzar\Envs\django\lib\site-packages\djongo\sql2mongo\sql_tokens.py", line 54, in tokens2sql
    yield from SQLToken.tokens2sql(tok, query)
  File "C:\Users\Shaikh Abuzar\Envs\django\lib\site-packages\djongo\sql2mongo\sql_tokens.py", line 39, in tokens2sql
    int(token[0][1].value)
ValueError: invalid literal for int() with base 10: '"dashboard_costtable"."rate_1" * "dashboard_costtable"."unit_1"'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Shaikh Abuzar\Envs\django\lib\site-packages\djongo\cursor.py", line 56, in execute
    params)
  File "C:\Users\Shaikh Abuzar\Envs\django\lib\site-packages\djongo\sql2mongo\query.py", line 783, in __init__
    self._query = self.parse()
  File "C:\Users\Shaikh Abuzar\Envs\django\lib\site-packages\djongo\sql2mongo\query.py", line 884, in parse
    raise exe from e
djongo.exceptions.SQLDecodeError:

        Keyword: None
        Sub SQL: None
        FAILED SQL: SELECT "dashboard_costtable"."tower", ("dashboard_costtable"."rate_1" * "dashboard_costtable"."unit_1") AS "var" FROM "dashboard_costtable" WHERE ("dashboard_costtable"."sheet_no_id" = %(0)s AND "dashboard_costtable"."is_external" = %(1)s)
        Params: (4, True)
        Version: 1.3.3

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Shaikh Abuzar\Envs\django\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Shaikh Abuzar\Envs\django\lib\site-packages\djongo\cursor.py", line 59, in execute
    raise db_exe from e
djongo.database.DatabaseError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Shaikh Abuzar\Envs\django\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Shaikh Abuzar\Envs\django\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Shaikh Abuzar\Envs\django\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Shaikh Abuzar\Envs\django\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\Shaikh Abuzar\Desktop\Projects\KasmaSoft\ITSM\itsm\dashboard\views.py", line 88, in costing_page
    pprint(list(external_data))
  File "C:\Users\Shaikh Abuzar\Envs\django\lib\site-packages\django\db\models\query.py", line 276, in __iter__
    self._fetch_all()
  File "C:\Users\Shaikh Abuzar\Envs\django\lib\site-packages\django\db\models\query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\Shaikh Abuzar\Envs\django\lib\site-packages\django\db\models\query.py", line 115, in __iter__
    for row in compiler.results_iter(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size):
  File "C:\Users\Shaikh Abuzar\Envs\django\lib\site-packages\django\db\models\sql\compiler.py", line 1103, in results_iter
    results = self.execute_sql(MULTI, chunked_fetch=chunked_fetch, chunk_size=chunk_size)
  File "C:\Users\Shaikh Abuzar\Envs\django\lib\site-packages\django\db\models\sql\compiler.py", line 1151, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Shaikh Abuzar\Envs\django\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "C:\Users\Shaikh Abuzar\Envs\django\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\Shaikh Abuzar\Envs\django\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Shaikh Abuzar\Envs\django\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Shaikh Abuzar\Envs\django\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Shaikh Abuzar\Envs\django\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Shaikh Abuzar\Envs\django\lib\site-packages\djongo\cursor.py", line 59, in execute
    raise db_exe from e
django.db.utils.DatabaseError

**Comment by elliotsyoung** [comment]
Try changing your second line to:
`external_data = entries.filter(is_external__in=[True]).values('tower').annotate(var=ExpressionWrapper(F('rate_1') * F('unit_1'), output_field=FloatField()))`

I encountered a similar error in this thread:
https://github.com/nesdis/djongo/issues/465#issue-688376523
