### ISSUE TITLE
Problems using Django 3.x in initial migration

### ISSUE THREAD

**Issue by ChristianGeng** [nesdis/djongo#513]
#### One line description of the issue

Problems using Django 3.x in initial migration

#### 

When using Django major version 3 I get migration errors (makmigration works but migrate fails) on a fresh mongo db
installation (docker-compose clearing volume data):

```

Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, core, sessions
Running migrations:
[DEBUG-DJANGO] 2021-01-14 15:13:58,219 django.db.backends.schema  schema in              execute() line 133: CREATE TABLE "core_user" ("id" int NOT NULL PRIMARY KEY AUTOINCREMENT, "password" string NOT NULL, "last_login" date NULL, "is_superuser" bool NOT NULL, "keycloak_id" string NOT NULL UNIQUE, "email" string NOT NULL UNIQUE, "is_active" bool NOT NULL, "is_staff" bool NOT NULL); (params None)
[DEBUG-DJANGO] 2021-01-14 15:13:58,223 django.db.backends  utils in            debug_sql() line 130: (0.003) QUERY = 'CREATE TABLE "core_user" ("id" int NOT NULL PRIMARY KEY AUTOINCREMENT, "password" string NOT NULL, "last_login" date NULL, "is_superuser" bool NOT NULL, "keycloak_id" string NOT NULL UNIQUE, "email" string NOT NULL UNIQUE, "is_active" bool NOT NULL, "is_staff" bool NOT NULL)' - PARAMS = (); args=None
  Applying core.0001_initial...Traceback (most recent call last):
  File "/home/christian/.venvs/backend-ZIt4lE0c/lib/python3.7/site-packages/djongo/sql2mongo/query.py", line 856, in parse
    return handler(self, statement)
  File "/home/christian/.venvs/backend-ZIt4lE0c/lib/python3.7/site-packages/djongo/sql2mongo/query.py", line 897, in _create
    query = CreateQuery(self.db, self.connection_properties, sm, self._params)
  File "/home/christian/.venvs/backend-ZIt4lE0c/lib/python3.7/site-packages/djongo/sql2mongo/query.py", line 645, in __init__
    super().__init__(*args)
  File "/home/christian/.venvs/backend-ZIt4lE0c/lib/python3.7/site-packages/djongo/sql2mongo/query.py", line 84, in __init__
    super().__init__(*args)
  File "/home/christian/.venvs/backend-ZIt4lE0c/lib/python3.7/site-packages/djongo/sql2mongo/query.py", line 62, in __init__
    self.parse()
  File "/home/christian/.venvs/backend-ZIt4lE0c/lib/python3.7/site-packages/djongo/sql2mongo/query.py", line 729, in parse
    self._create_table(statement)
  File "/home/christian/.venvs/backend-ZIt4lE0c/lib/python3.7/site-packages/djongo/sql2mongo/query.py", line 657, in _create_table
    self.db.create_collection(table)
  File "/home/christian/.venvs/backend-ZIt4lE0c/lib/python3.7/site-packages/pymongo/database.py", line 365, in create_collection
    raise CollectionInvalid("collection %s already exists" % name)
pymongo.errors.CollectionInvalid: collection core_user already exists

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/christian/.venvs/backend-ZIt4lE0c/lib/python3.7/site-packages/djongo/cursor.py", line 56, in execute
    params)
  File "/home/christian/.venvs/backend-ZIt4lE0c/lib/python3.7/site-packages/djongo/sql2mongo/query.py", line 783, in __init__
    self._query = self.parse()
  File "/home/christian/.venvs/backend-ZIt4lE0c/lib/python3.7/site-packages/djongo/sql2mongo/query.py", line 884, in parse
    raise exe from e
djongo.exceptions.SQLDecodeError:

	Keyword: None
	Sub SQL: None
	FAILED SQL: CREATE TABLE "core_user" ("id" int NOT NULL PRIMARY KEY AUTOINCREMENT, "password" string NOT NULL, "last_login" date NULL, "is_superuser" bool NOT NULL, "keycloak_id" string NOT NULL UNIQUE, "email" string NOT NULL UNIQUE, "is_active" bool NOT NULL, "is_staff" bool NOT NULL)
	Params: None
	Version: 1.3.3

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/christian/.venvs/backend-ZIt4lE0c/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql)
  File "/home/christian/.venvs/backend-ZIt4lE0c/lib/python3.7/site-packages/djongo/cursor.py", line 59, in execute
    raise db_exe from e
djongo.database.DatabaseError

The above exception was the direct cause of the following exception:
```

Once the initial migrations are successfully done, I can upgrade to a django 3 installation with a
pipenv that looks like that and everything works fine:

```

[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[packages]
django = "==3.0.5"
django-cors-headers = "==3.4.0"
djangorestframework = "*"
drf-yasg = {extras = ["validation"], version = "*"}
djongo = "*"
jsonfield = "*"
python-keycloak = "*"
numpy = "*"
qrcode = "*"
scipy = "*"
audiofile = "*"
python-magic = "*"
pymongo = "==3.7.2"
names = "*"
uwsgi = "*"
flake8 = "*"
pillow = "*"
requests-toolbelt = "*"
sqlparse = "==0.2.4"

[requires]
python_version = "3.7"

```

My question: How to set up a django virtual environment that uses Django 3.x for initial migration?

**Comment by MacKey-255** [comment]
https://www.djongomapper.com/integrating-django-with-mongodb/#setting-up-an-existing-mongodb-database-on-django

**Comment by ChristianGeng** [comment]
But my usecase would rather be to `Migrating an existing Django app to MongoDB`.  I have the django app and do not (yet) care about the data.
