### ISSUE TITLE
How do i fix Django Database error. I'm using MongoDB with Djongo.

### ISSUE THREAD

**Issue by sudip-chhantyal** [nesdis/djongo#517]
#### Everything was working fine until recently when i decided to add NewApp. Whenever i try to migrate it greets me with django.db.utils.DatabaseError .

I tried reseting the DataBase Manually as well as from Terminal but had no luck.

I think it's super simple but imm new to Django and MongoDB can't seem to figure out how to fix it, any help will be greatly appreciated

I am using Django==3.0.3 and Djongo==1.3.3

```
Operations to perform:
  Apply all migrations: account, admin, articles, auth, authtoken, comments, contenttypes, sessions, sites, socialaccount, users
Running migrations:
Not implemented alter command for SQL ALTER TABLE "articles_article" ADD COLUMN "author_id" int NOT NULL
  Applying articles.0002_article_author...Traceback (most recent call last):
  File "/Users/sudipchhantyal/opt/anaconda3/envs/restApi/lib/python3.8/site-packages/djongo/cursor.py", line 51, in execute
    self.result = Query(
  File "/Users/sudipchhantyal/opt/anaconda3/envs/restApi/lib/python3.8/site-packages/djongo/sql2mongo/query.py", line 783, in __init__
    self._query = self.parse()
  File "/Users/sudipchhantyal/opt/anaconda3/envs/restApi/lib/python3.8/site-packages/djongo/sql2mongo/query.py", line 875, in parse
    raise e
  File "/Users/sudipchhantyal/opt/anaconda3/envs/restApi/lib/python3.8/site-packages/djongo/sql2mongo/query.py", line 856, in parse
    return handler(self, statement)
  File "/Users/sudipchhantyal/opt/anaconda3/envs/restApi/lib/python3.8/site-packages/djongo/sql2mongo/query.py", line 888, in _alter
    query = AlterQuery(self.db, self.connection_properties, sm, self._params)
  File "/Users/sudipchhantyal/opt/anaconda3/envs/restApi/lib/python3.8/site-packages/djongo/sql2mongo/query.py", line 425, in __init__
    super().__init__(*args)
  File "/Users/sudipchhantyal/opt/anaconda3/envs/restApi/lib/python3.8/site-packages/djongo/sql2mongo/query.py", line 84, in __init__
    super().__init__(*args)
  File "/Users/sudipchhantyal/opt/anaconda3/envs/restApi/lib/python3.8/site-packages/djongo/sql2mongo/query.py", line 62, in __init__
    self.parse()
  File "/Users/sudipchhantyal/opt/anaconda3/envs/restApi/lib/python3.8/site-packages/djongo/sql2mongo/query.py", line 435, in parse
    self._add(statement)
  File "/Users/sudipchhantyal/opt/anaconda3/envs/restApi/lib/python3.8/site-packages/djongo/sql2mongo/query.py", line 598, in _add
    raise SQLDecodeError(err_key=tok.value,
djongo.exceptions.SQLDecodeError: 

	Keyword: int
	Sub SQL: ALTER TABLE "articles_article" ADD COLUMN "author_id" int NOT NULL
	FAILED SQL: ('ALTER TABLE "articles_article" ADD COLUMN "author_id" int NOT NULL',)
	Params: ([],)
	Version: 1.3.3

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/sudipchhantyal/opt/anaconda3/envs/restApi/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/sudipchhantyal/opt/anaconda3/envs/restApi/lib/python3.8/site-packages/djongo/cursor.py", line 59, in execute
    raise db_exe from e
djongo.database.DatabaseError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/Users/sudipchhantyal/opt/anaconda3/envs/restApi/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Users/sudipchhantyal/opt/anaconda3/envs/restApi/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/sudipchhantyal/opt/anaconda3/envs/restApi/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/sudipchhantyal/opt/anaconda3/envs/restApi/lib/python3.8/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/Users/sudipchhantyal/opt/anaconda3/envs/restApi/lib/python3.8/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/Users/sudipchhantyal/opt/anaconda3/envs/restApi/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 231, in handle
    post_migrate_state = executor.migrate(
  File "/Users/sudipchhantyal/opt/anaconda3/envs/restApi/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/Users/sudipchhantyal/opt/anaconda3/envs/restApi/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/Users/sudipchhantyal/opt/anaconda3/envs/restApi/lib/python3.8/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/Users/sudipchhantyal/opt/anaconda3/envs/restApi/lib/python3.8/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/Users/sudipchhantyal/opt/anaconda3/envs/restApi/lib/python3.8/site-packages/django/db/migrations/operations/fields.py", line 110, in database_forwards
    schema_editor.add_field(
  File "/Users/sudipchhantyal/opt/anaconda3/envs/restApi/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 480, in add_field
    self.execute(sql, params)
  File "/Users/sudipchhantyal/opt/anaconda3/envs/restApi/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 142, in execute
    cursor.execute(sql, params)
  File "/Users/sudipchhantyal/opt/anaconda3/envs/restApi/lib/python3.8/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/Users/sudipchhantyal/opt/anaconda3/envs/restApi/lib/python3.8/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/sudipchhantyal/opt/anaconda3/envs/restApi/lib/python3.8/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/sudipchhantyal/opt/anaconda3/envs/restApi/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/sudipchhantyal/opt/anaconda3/envs/restApi/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/sudipchhantyal/opt/anaconda3/envs/restApi/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/sudipchhantyal/opt/anaconda3/envs/restApi/lib/python3.8/site-packages/djongo/cursor.py", line 59, in execute
    raise db_exe from e
django.db.utils.DatabaseError

```

**Comment by cuongdaovan** [comment]
I have the same error

**Comment by jollypolly123** [comment]
Same error but different cause

**Comment by sudip-chhantyal** [comment]
@cuongdaovan I don't if its a right solution but i was able to fix it by faking migration.

**Comment by habibor144369** [comment]
same problem to my pc, anyone can help me

**Comment by habibor144369** [comment]
I solve this problem, just now. Delete the all migrations file. Then new make migrations and migrate, i hope solve this problem,  i get the result.

**Comment by nurettin** [comment]
The solution to this problem is to use the master branch which doesn't check for column type names anymore.

**Comment by AsifMahsud** [comment]
I'm facing the same problem. Has anyone solved this issue?

**Comment by abdessamad-traibiz** [comment]
the same problem bro

**Comment by logist-technologies** [comment]
> The solution to this problem is to use the master branch which doesn't check for column type names anymore.

How to do this can you elaborate??

**Comment by nurettin** [comment]
> > The solution to this problem is to use the master branch which doesn't check for column type names anymore.
> 
> How to do this can you elaborate??

```
pip install --install-option="--extras-require=json" git+ssh://git@github.org/nesdis/djongo.git@master
```

**Comment by Sajeyks** [comment]
Try this https://stackoverflow.com/a/68174994/12601926

**Comment by rdooda** [comment]
> Try [this](https://stackoverflow.com/a/68174994/12601926). worked for me

this is not work to me 
because i'm not using mobels

**Comment by rdooda** [comment]
> > > The solution to this problem is to use the master branch which doesn't check for column type names anymore.
> > 
> > 
> > How to do this can you elaborate??
> 
> ```
> pip install --install-option="--extras-require=json" git+https://github.com/nesdis/djongo.git@master
> ```

i dont know how to use
please tell me process

**Comment by krishnajhapate** [comment]
> I solve this problem, just now. Delete the all migrations file. Then new make migrations and migrate, i hope solve this problem, i get the result.

This really solves my Problem

**Comment by wrodusa2006** [comment]
Hi, Iam Wald.
The same problem and I dia a little troubleshooting and I found that removing the import of djongo and djongo-mongo-version-fix from PyCharm IDE and install again it solve the problem for a while. The situatioin is that to work I must keep import djongo and import  djongo-mongo-version-fix

**Comment by wrodusa2006** [comment]
looks like there is a bug in the drive djongo

**Comment by BOVAGE** [comment]
> looks like there is a bug in the drive djongo

seems so

**Comment by anshupal11** [comment]
I delete migration files and apply migrate and makemigrations command and I get the problem solved.

**Comment by ForeverNoob69** [comment]
i still have this problem & didn't find any solution. can anyone please help me with it??? i tried sqparse installing & all in the above

**Comment by admlds13** [comment]
> > The solution to this problem is to use the master branch which doesn't check for column type names anymore.
> 
> How to do this can you elaborate??

Delete all the migration files from the project and delete the database as well and redo the makemiigrations and migrate, problem solved

**Comment by admlds13** [comment]
> i still have this problem & didn't find any solution. can anyone please help me with it??? i tried sqparse installing & all in the above

Delete all the migration files from the project and delete the database as well and redo the makemiigrations and migrate, problem solved

**Comment by admlds13** [comment]
> i still have this problem & didn't find any solution. can anyone please help me with it??? i tried sqparse installing & all in the above

Delete all the migration files from the project and delete the database as well and redo the makemiigrations and migrate, problem solved

**Comment by iOMJaiswal** [comment]
> > > The solution to this problem is to use the master branch which doesn't check for column type names anymore.
> > 
> > 
> > How to do this can you elaborate??
> 
> ```
> pip install --install-option="--extras-require=json" git+https://github.com/nesdis/djongo.git@master
> ```

command is not working can you please tell how to use it
