### ISSUE TITLE
djongo (1.2.17) installed via pip cannot detect sql2mongo 

### ISSUE THREAD

**Issue by IshibashiKazuya** [nesdis/djongo#58]
I got error during `python manage.py makemigrations` on Django Project .
-------------
  File "/Users/MyAccountName/.pyenv/versions/3.6.4rc1/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 23, in <module>
    from sql2mongo import SQLDecodeError, SQLToken
ModuleNotFoundError: No module named 'sql2mongo'
------------

I've try following, but did not change.
$ pip uninstall djongo
$ pip install --no-cache-dir djongo

So, What should I do ?

[Each Verions ]
Django: 1.2.17
Django: 2.0.1
MongoDB: 3.6.2
Python: 3.6.4

thanks

**Comment by nesdis** [comment]
i messed up with the paths please try with pip install -U djongo

**Comment by nesdis** [comment]
I think this should be solved. closing this.

**Comment by IshibashiKazuya** [comment]
@nesdis 
Thank you for your update. but not working

Please confirm it

I've try following:

( Upgrade Djongo)
$ pip uninstall djongo
$ pip install --no-cache-dir djongo
$ pip list | grep djongo
djongo (1.2.18)

( Creste TEST-DB on MongoDB)
$ mongo
> use admin
switched to db admin
> db.auth('admin-user', 'admin-pass')
1
> use test-project-db
switched to db test-project-db

> db.createUser({
    user: "test-project-user",
    pwd: "test-project-pass",
    roles: [{
        role: "readWrite", db: "test-project-db"
    }]
})

Successfully added user: {
	"user" : "test-project-user",
	"roles" : [
		{
			"role" : "readWrite",
			"db" : "test-project-db"
		}
	]
}
> exit

( mongo connection test )
$ python
---
import pymongo
host = 'localhost'
port = 27017
db = 'test-project-db'
user = 'test-project-user'
pwd = 'test-project-pass'
client = pymongo.MongoClient(host, port)
client[db].authenticate(user, pwd)
col = client[db]['test-collection']
col.insert({'test': 'testtest'})
for cur in col.find():
  print(cur)
---

( Create Django Project )
$ cd /tmp
$ django-admin startproject TestProject
$ cd TestProject
$ vim ./TestProject/settings.py
---
INSTALLED_APPS = [ 
  ...
  'djongo',
]

DATABASES = { 
    'default': {
        'ENGINE': 'djongo',
        'NAME': 'test-project-db',
        'HOST': 'localhost',
        'PORT': 27017,
        'USER': 'test-project-user',
        'PASSWORD': 'test-project-pass',
        'AUTH_SOURCE': 'test-project-db',
        'AUTH_MECHANISM': 'SCRAM-SHA-1',
    }   
}
---

( Make Migrations )
$ python ./manage.py makemigrations
Traceback (most recent call last):
  File "/Users/MyAccountName/.pyenv/versions/3.6.4rc1/lib/python3.6/site-packages/django/db/utils.py", line 110, in load_backend
    return import_module('%s.base' % backend_name)
  File "/Users/MyAccountName/.pyenv/versions/3.6.4rc1/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/MyAccountName/.pyenv/versions/3.6.4rc1/lib/python3.6/site-packages/djongo/base.py", line 14, in <module>
    from .cursor import Cursor
  File "/Users/MyAccountName/.pyenv/versions/3.6.4rc1/lib/python3.6/site-packages/djongo/cursor.py", line 2, in <module>
    from .sql2mongo.query import Result
  File "/Users/MyAccountName/.pyenv/versions/3.6.4rc1/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 23, in <module>
    from sql2mongo import SQLDecodeError, SQLToken
ModuleNotFoundError: No module named 'sql2mongo'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/MyAccountName/.pyenv/versions/3.6.4rc1/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/Users/MyAccountName/.pyenv/versions/3.6.4rc1/lib/python3.6/site-packages/django/core/management/__init__.py", line 347, in execute
    django.setup()
  File "/Users/MyAccountName/.pyenv/versions/3.6.4rc1/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/MyAccountName/.pyenv/versions/3.6.4rc1/lib/python3.6/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/Users/MyAccountName/.pyenv/versions/3.6.4rc1/lib/python3.6/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/Users/MyAccountName/.pyenv/versions/3.6.4rc1/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/MyAccountName/.pyenv/versions/3.6.4rc1/lib/python3.6/site-packages/django/contrib/auth/models.py", line 2, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/Users/MyAccountName/.pyenv/versions/3.6.4rc1/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 47, in <module>
    class AbstractBaseUser(models.Model):
  File "/Users/MyAccountName/.pyenv/versions/3.6.4rc1/lib/python3.6/site-packages/django/db/models/base.py", line 114, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/Users/MyAccountName/.pyenv/versions/3.6.4rc1/lib/python3.6/site-packages/django/db/models/base.py", line 315, in add_to_class
    value.contribute_to_class(cls, name)
  File "/Users/MyAccountName/.pyenv/versions/3.6.4rc1/lib/python3.6/site-packages/django/db/models/options.py", line 205, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/Users/MyAccountName/.pyenv/versions/3.6.4rc1/lib/python3.6/site-packages/django/db/__init__.py", line 33, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/Users/MyAccountName/.pyenv/versions/3.6.4rc1/lib/python3.6/site-packages/django/db/utils.py", line 202, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/Users/MyAccountName/.pyenv/versions/3.6.4rc1/lib/python3.6/site-packages/django/db/utils.py", line 125, in load_backend
    ) from e_user
django.core.exceptions.ImproperlyConfigured: 'djongo' isn't an available database backend.
Try using 'django.db.backends.XXX', where XXX is one of:
    'mysql', 'oracle', 'postgresql', 'sqlite3'


[Each Verions ]
MacOS High Sierra ( 10.13.3 ) [ MacBook : Retina, 12-inch, 2017 : Corei5 : MEM 8GB ]
pip 9.0.1
Django: 1.2.18
Django: 2.0.1
MongoDB: 3.6.2
Python: 3.6.4
