### ISSUE TITLE
Migration error namespace name generated from index name is too long

### ISSUE THREAD

**Issue by new69** [nesdis/djongo#595]
#### One line description of the issue
Get erro when run django migration on AWS DocumentDB. I saw that aws accept 67 characters, but when I tried, the index is to long, the amazon put all together on database and it's pass the limit: `django_content_type$django_content_type_app_label_model_76bd3d3b_uniq`.
Can I change this migration or index name on djongo config?

#### Python script

<The complete python script used to produce the issue.>

```python
<copy and paste code here>
python manage.py migrate
```

#### Traceback
<The complete stack trace of the error.>
```shell
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  Applying contenttypes.0001_initial...This version of djongo does not support "schema validation using CONSTRAINT" fully. Visit https://nesdis.github.io/djongo/support/
Traceback (most recent call last):
  File "/home/ec2-user/ms-events/lib64/python3.7/site-packages/djongo/sql2mongo/query.py", line 857, in parse
    return handler(self, statement)
  File "/home/ec2-user/ms-events/lib64/python3.7/site-packages/djongo/sql2mongo/query.py", line 894, in _alter
    query.execute()
  File "/home/ec2-user/ms-events/lib64/python3.7/site-packages/djongo/sql2mongo/query.py", line 637, in _unique
    name=self._iden_name)
  File "/home/ec2-user/ms-events/lib64/python3.7/site-packages/pymongo/collection.py", line 2100, in create_index
    return self.__create_indexes([index], session, **cmd_options)[0]
  File "/home/ec2-user/ms-events/lib64/python3.7/site-packages/pymongo/collection.py", line 1994, in __create_indexes
    session=session)
  File "/home/ec2-user/ms-events/lib64/python3.7/site-packages/pymongo/collection.py", line 253, in _command
    user_fields=user_fields)
  File "/home/ec2-user/ms-events/lib64/python3.7/site-packages/pymongo/pool.py", line 721, in command
    exhaust_allowed=exhaust_allowed)
  File "/home/ec2-user/ms-events/lib64/python3.7/site-packages/pymongo/network.py", line 160, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/home/ec2-user/ms-events/lib64/python3.7/site-packages/pymongo/helpers.py", line 167, in _check_command_response
    raise OperationFailure(errmsg, code, response, max_wire_version)
pymongo.errors.OperationFailure: namespace name generated from index name is too long, full error: {'ok': 0.0, 'code': 67, 'errmsg': 'namespace name generated from index name is too long', 'operationTime': Timestamp(1643660773, 1)}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ec2-user/ms-events/lib64/python3.7/site-packages/djongo/cursor.py", line 56, in execute
    params)
  File "/home/ec2-user/ms-events/lib64/python3.7/site-packages/djongo/sql2mongo/query.py", line 784, in __init__
    self._query = self.parse()
  File "/home/ec2-user/ms-events/lib64/python3.7/site-packages/djongo/sql2mongo/query.py", line 869, in parse
    raise exe from e
djongo.exceptions.SQLDecodeError:

	Keyword: None
	Sub SQL: None
	FAILED SQL: ALTER TABLE "django_content_type" ADD CONSTRAINT "django_content_type_app_label_model_76bd3d3b_uniq" UNIQUE ("app_label", "model")
	Params: ()
	Version: 1.3.6

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ec2-user/ms-events/lib64/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ec2-user/ms-events/lib64/python3.7/site-packages/djongo/cursor.py", line 59, in execute
    raise db_exe from e
djongo.database.DatabaseError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/ec2-user/ms-events/lib64/python3.7/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/ec2-user/ms-events/lib64/python3.7/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ec2-user/ms-events/lib64/python3.7/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ec2-user/ms-events/lib64/python3.7/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/ec2-user/ms-events/lib64/python3.7/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/ec2-user/ms-events/lib64/python3.7/site-packages/django/core/management/commands/migrate.py", line 246, in handle
    fake_initial=fake_initial,
  File "/home/ec2-user/ms-events/lib64/python3.7/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/ec2-user/ms-events/lib64/python3.7/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/ec2-user/ms-events/lib64/python3.7/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/ec2-user/ms-events/lib64/python3.7/site-packages/django/db/migrations/migration.py", line 126, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/ec2-user/ms-events/lib64/python3.7/site-packages/django/db/migrations/operations/models.py", line 531, in database_forwards
    getattr(new_model._meta, self.option_name, set()),
  File "/home/ec2-user/ms-events/lib64/python3.7/site-packages/django/db/backends/base/schema.py", line 419, in alter_unique_together
    self.execute(self._create_unique_sql(model, columns))
  File "/home/ec2-user/ms-events/lib64/python3.7/site-packages/django/db/backends/base/schema.py", line 145, in execute
    cursor.execute(sql, params)
  File "/home/ec2-user/ms-events/lib64/python3.7/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/ec2-user/ms-events/lib64/python3.7/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/ec2-user/ms-events/lib64/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ec2-user/ms-events/lib64/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/ec2-user/ms-events/lib64/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ec2-user/ms-events/lib64/python3.7/site-packages/djongo/cursor.py", line 59, in execute
    raise db_exe from e
django.db.utils.DatabaseError
```

**Comment by minmul117** [comment]
@new69 Did you solve this problem? I'm trying to solve this problem...

**Comment by legolas-golom** [comment]
Faced  exact same issue just removed these     
'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
to make it work . But need a better solution or fix to solve them permanently.

**Comment by minmul117** [comment]
Okay, I created django migration files in the mongoDB docker container, and copied all created collections in DocumentDB, then migrate it again. It solved problem.
