### ISSUE TITLE
Admin empty table IndexError

### ISSUE THREAD

**Issue by greatxam** [nesdis/djongo#60]
#### List index out of range for tables with no records
I got IndexError exception when I browse to tables with no data in admin site.

I also tried in shell but it works.
```$ python3 manage.py shell```

#### Python script
<The complete python script used to produce the issue.>

```python
from django.contrib.auth.models import Group
g = Group.objects.all()
print(g)
<QuerySet []>
```

#### Traceback
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.9-py3.6.egg/django/db/models/sql/compiler.py in apply_converters, line 830

Environment:

Request Method: GET
Request URL: http://127.0.0.1:8000/admin/auth/group/

Django Version: 1.11.9
Python Version: 3.6.4
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'djongo',
 'evostream']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Traceback:

File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.9-py3.6.egg/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.9-py3.6.egg/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.9-py3.6.egg/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.9-py3.6.egg/django/contrib/admin/options.py" in wrapper
  551.                 return self.admin_site.admin_view(view)(*args, **kwargs)

File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.9-py3.6.egg/django/utils/decorators.py" in _wrapped_view
  149.                     response = view_func(request, *args, **kwargs)

File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.9-py3.6.egg/django/views/decorators/cache.py" in _wrapped_view_func
  57.         response = view_func(request, *args, **kwargs)

File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.9-py3.6.egg/django/contrib/admin/sites.py" in inner
  224.             return view(request, *args, **kwargs)

File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.9-py3.6.egg/django/utils/decorators.py" in _wrapper
  67.             return bound_func(*args, **kwargs)

File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.9-py3.6.egg/django/utils/decorators.py" in _wrapped_view
  149.                     response = view_func(request, *args, **kwargs)

File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.9-py3.6.egg/django/utils/decorators.py" in bound_func
  63.                 return func.__get__(self, type(self))(*args2, **kwargs2)

File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.9-py3.6.egg/django/contrib/admin/options.py" in changelist_view
  1542.                 self.list_max_show_all, self.list_editable, self,

File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.9-py3.6.egg/django/contrib/admin/views/main.py" in __init__
  79.         self.get_results(request)

File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.9-py3.6.egg/django/contrib/admin/views/main.py" in get_results
  177.         result_count = paginator.count

File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.9-py3.6.egg/django/utils/functional.py" in __get__
  35.         res = instance.__dict__[self.name] = self.func(instance)

File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.9-py3.6.egg/django/core/paginator.py" in count
  79.             return self.object_list.count()

File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.9-py3.6.egg/django/db/models/query.py" in count
  364.         return self.query.get_count(using=self.db)

File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.9-py3.6.egg/django/db/models/sql/query.py" in get_count
  499.         number = obj.get_aggregation(using, ['__count'])['__count']

File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.9-py3.6.egg/django/db/models/sql/query.py" in get_aggregation
  485.         result = compiler.apply_converters(result, converters)

File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.9-py3.6.egg/django/db/models/sql/compiler.py" in apply_converters
  830.             value = row[pos]

Exception Type: IndexError at /admin/auth/group/
Exception Value: list index out of range

**Comment by nesdis** [comment]
Hi @greatxam which version of djongo do you use. Also, have you run migrations on your project **after** you switched to MongoDB?

**Comment by greatxam** [comment]
I'm using 1.0. Yes, I do run the migrations. It's also a fresh install.

**Comment by nesdis** [comment]
The latest version of djongo is 1.2.19. I just tried accessing groups from
admin. It works for me. In your mongodb do you have auth_user and
auth_user_groups collection (empty) created?

**Comment by greatxam** [comment]
Yes, I do have. I'd run createsuperuser. I'll try 1.2.19.

**Comment by greatxam** [comment]
I got another error when using 1.2.19.

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.9-py3.6.egg/django/db/utils.py", line 115, in load_backend
    return import_module('%s.base' % backend_name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Volumes/PROJECT/wylog/CITA/cita/djongo/base.py", line 14, in <module>
    from .cursor import Cursor
  File "/Volumes/PROJECT/wylog/CITA/cita/djongo/cursor.py", line 2, in <module>
    from .sql2mongo.query import Result
  File "/Volumes/PROJECT/wylog/CITA/cita/djongo/sql2mongo/query.py", line 6, in <module>
    from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.9-py3.6.egg/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.9-py3.6.egg/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.9-py3.6.egg/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.9-py3.6.egg/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.9-py3.6.egg/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.9-py3.6.egg/django/contrib/auth/models.py", line 4, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.9-py3.6.egg/django/contrib/auth/base_user.py", line 52, in <module>
    class AbstractBaseUser(models.Model):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.9-py3.6.egg/django/db/models/base.py", line 124, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.9-py3.6.egg/django/db/models/base.py", line 325, in add_to_class
    value.contribute_to_class(cls, name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.9-py3.6.egg/django/db/models/options.py", line 214, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.9-py3.6.egg/django/db/__init__.py", line 33, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.9-py3.6.egg/django/db/utils.py", line 211, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Django-1.11.9-py3.6.egg/django/db/utils.py", line 134, in load_backend
    raise ImproperlyConfigured(error_msg)
django.core.exceptions.ImproperlyConfigured: 'djongo' isn't an available database backend.
Try using 'django.db.backends.XXX', where XXX is one of:
    'mysql', 'oracle', 'postgresql', 'sqlite3'
Error was: No module named 'dataclasses'
```

**Comment by nesdis** [comment]
How did you install djongo? Via pip? If you see the setup.py file.
Dataclasses is a required module that must get installed automatically.

In any case please try pip install Dataclasses.

**Comment by greatxam** [comment]
Oh! I forgot to install the **Dataclassess** module.

The **IndexError** in admin is resolve on **1.2.19**
However, I got another error, I'll create new issue for this one.

Thank you very much @nesdis!
