### ISSUE TITLE
TypeError when using EmbeddedModelField

### ISSUE THREAD

**Issue by ferlnand** [nesdis/djongo#62]
#### Using EmbeddedModelField produces TypeError: Object must be of type Model

I'm having troubles using the EmbeddedModelField. Can someone maybe point me in the right direction? I'm pretty sure I'm just missing out a small detail...

thx!

Versions used:
django: 2.0.1
djongo: 1.2.19
python: 3.6.3

#### Python script

<The complete python script used to produce the issue.>

```python
from djongo import models

class GeneralCharacterInfo(models.Model):
    character_name  = models.CharField(max_length=50)
    player_name     = models.CharField(max_length=50)
    
    class Meta:
        abstract = True

class Character(models.Model):
    test_field = models.CharField(max_length=100)
    general_info = models.EmbeddedModelField(model_container=GeneralCharacterInfo)

```
Error occurs when trying to create the object:
```python
character = Character.objects.create()
```

#### Traceback
Traceback (most recent call last):
  File "C:\Users\ferdi\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Users\ferdi\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\ferdi\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ferdi\workspace\rpgtools\starsheet\views.py", line 65, in characterDetail
    character = Character.objects.create()
  File "C:\Users\ferdi\AppData\Local\Programs\Python\Python36\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\ferdi\AppData\Local\Programs\Python\Python36\lib\site-packages\django\db\models\query.py", line 417, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\ferdi\AppData\Local\Programs\Python\Python36\lib\site-packages\django\db\models\base.py", line 729, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Users\ferdi\AppData\Local\Programs\Python\Python36\lib\site-packages\django\db\models\base.py", line 759, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "C:\Users\ferdi\AppData\Local\Programs\Python\Python36\lib\site-packages\django\db\models\base.py", line 842, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "C:\Users\ferdi\AppData\Local\Programs\Python\Python36\lib\site-packages\django\db\models\base.py", line 880, in _do_insert
    using=using, raw=raw)
  File "C:\Users\ferdi\AppData\Local\Programs\Python\Python36\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\ferdi\AppData\Local\Programs\Python\Python36\lib\site-packages\django\db\models\query.py", line 1125, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "C:\Users\ferdi\AppData\Local\Programs\Python\Python36\lib\site-packages\django\db\models\sql\compiler.py", line 1280, in execute_sql
    for sql, params in self.as_sql():
  File "C:\Users\ferdi\AppData\Local\Programs\Python\Python36\lib\site-packages\django\db\models\sql\compiler.py", line 1233, in as_sql
    for obj in self.query.objs
  File "C:\Users\ferdi\AppData\Local\Programs\Python\Python36\lib\site-packages\django\db\models\sql\compiler.py", line 1233, in <listcomp>
    for obj in self.query.objs
  File "C:\Users\ferdi\AppData\Local\Programs\Python\Python36\lib\site-packages\django\db\models\sql\compiler.py", line 1232, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "C:\Users\ferdi\AppData\Local\Programs\Python\Python36\lib\site-packages\django\db\models\sql\compiler.py", line 1172, in prepare_value
    value = field.get_db_prep_save(value, connection=self.connection)
  File "C:\Users\ferdi\AppData\Local\Programs\Python\Python36\lib\site-packages\django\db\models\fields\__init__.py", line 767, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
  File "C:\Users\ferdi\AppData\Local\Programs\Python\Python36\lib\site-packages\djongo\models.py", line 380, in get_db_prep_value
    raise TypeError('Object must be of type Model, but is ' + str(type(value)))
TypeError: Object must be of type Model, but is <class 'NoneType'>

**Comment by ferlnand** [comment]
Ok, got it. Problem is that EmbeddedModelField has to be instantiated manually before saving. My assumption was that this instantiation is done automatically, like other fields (e.g. I don't need to instantiate test_field). This would be a nice-to-have?

If it helps someone, here's my solution for this:

either only create the object, instantiate the EmbeddedModelField and then save:
```python
character = Character()
character.general_info = GeneralCharacterInfo()
character.save()
```
or setting the default for general_info:
```python
class Character(models.Model):
    test_field = models.CharField(max_length=100)
    general_info = models.EmbeddedModelField(model_container=GeneralCharacterInfo,default=GeneralCharacterInfo())
```

Anyway: thanks for this package! :)

**Comment by nesdis** [comment]
@ferlnand That's right, the Model requires that the embedded fields be instantiate from the start. Will make a note of this on trying to instantiate the embedded model lazily.

**Comment by ferlnand** [comment]
@nesdis thanks for the confirmation! 

Another thing: when saving the object to the database, the embedded field gets typed to a ModelSubterfuge. I don't know how to handle this model. So basically an object becomes unusable for me as soon as I save it (Model.objects.create() or Model.save()). 
That's why I am currently saving the model and then load it from db, so the embedded field gets typed as a ModelField.

That's no big deal, but I think also a nice-to-have. Or do I miss something?

**Comment by nesdis** [comment]
@ferlnand There was an issue in the code. can you please try 

pip install git+https://github.com/nesdis/djongo

and get the latest commit and check if it is working

**Comment by ferlnand** [comment]
Nice! Now the type of Embedded Field is not changed to ModelSubterfuge when being saved. 

I probably have some other topics, but I will collect them and open a separate issue for those

thx for your help!

**Comment by softmarshmallow** [comment]
AttributeError: 'NoneType' object has no attribute 'attname'
