### ISSUE TITLE
namespace name generated from index name is too long

### ISSUE THREAD

**Issue by KrombopulosMichael** [nesdis/djongo#63]
#### namespace name generated from index name is too long

I tried to reinitialize one of my projects with djongo. Unfortunately, there was an error during the migration.

#### Traceback
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying bntq_common.0001_initial...Traceback (most recent call last):
  File "/Users/michael/.local/share/virtualenvs/backend-nyAsbErb/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 475,in parse
    return handler(self, statement)
  File "/Users/michael/.local/share/virtualenvs/backend-nyAsbErb/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 531,in _alter
    self.db[table].create_index(index, unique=True, name=constraint_name)
  File "/Users/michael/.local/share/virtualenvs/backend-nyAsbErb/lib/python3.6/site-packages/pymongo/collection.py", line 1753, increate_index
    self.__create_index(keys, kwargs, session, **cmd_options)
  File "/Users/michael/.local/share/virtualenvs/backend-nyAsbErb/lib/python3.6/site-packages/pymongo/collection.py", line 1655, in__create_index
    session=session)
  File "/Users/michael/.local/share/virtualenvs/backend-nyAsbErb/lib/python3.6/site-packages/pymongo/collection.py", line 244, in _command
    retryable_write=retryable_write)
  File "/Users/michael/.local/share/virtualenvs/backend-nyAsbErb/lib/python3.6/site-packages/pymongo/pool.py", line 496, in command
    collation=collation)
  File "/Users/michael/.local/share/virtualenvs/backend-nyAsbErb/lib/python3.6/site-packages/pymongo/network.py", line 125, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/Users/michael/.local/share/virtualenvs/backend-nyAsbErb/lib/python3.6/site-packages/pymongo/helpers.py", line 146, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: namespace name generated from index name "bntq-db.bntq_common_pharmaceuticalsubstance_atc_code.$bntq_common_pharmaceuticalsubstance_atc_code_pharmaceuticalsubstance_id_atc_code_id_6d0b7e4b_uniq" is too long (127 byte max)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/michael/.local/share/virtualenvs/backend-nyAsbErb/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/Users/michael/.local/share/virtualenvs/backend-nyAsbErb/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/michael/.local/share/virtualenvs/backend-nyAsbErb/lib/python3.6/site-packages/django/core/management/base.py", line288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/michael/.local/share/virtualenvs/backend-nyAsbErb/lib/python3.6/site-packages/django/core/management/base.py", line335, in execute
    output = self.handle(*args, **options)
  File "/Users/michael/.local/share/virtualenvs/backend-nyAsbErb/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 200, in handle
    fake_initial=fake_initial,
  File "/Users/michael/.local/share/virtualenvs/backend-nyAsbErb/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/Users/michael/.local/share/virtualenvs/backend-nyAsbErb/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/Users/michael/.local/share/virtualenvs/backend-nyAsbErb/lib/python3.6/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/Users/michael/.local/share/virtualenvs/backend-nyAsbErb/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 90, in __exit__
    self.execute(sql)
  File "/Users/michael/.local/share/virtualenvs/backend-nyAsbErb/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 117, in execute
    cursor.execute(sql, params)
  File "/Users/michael/.local/share/virtualenvs/backend-nyAsbErb/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/Users/michael/.local/share/virtualenvs/backend-nyAsbErb/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/michael/.local/share/virtualenvs/backend-nyAsbErb/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/michael/.local/share/virtualenvs/backend-nyAsbErb/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/michael/.local/share/virtualenvs/backend-nyAsbErb/lib/python3.6/site-packages/djongo/cursor.py", line 44, in execute
    self.result = Result(self.client_conn, self.db_conn, sql, params)
  File "/Users/michael/.local/share/virtualenvs/backend-nyAsbErb/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 415,in __init__
    self.parse()
  File "/Users/michael/.local/share/virtualenvs/backend-nyAsbErb/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 484,in parse
    raise exe from e
djongo.sql2mongo.SQLDecodeError: FAILED SQL: ALTER TABLE "bntq_common_pharmaceuticalsubstance_atc_code" ADD CONSTRAINT bntq_common_pharmaceuticalsubstance_atc_code_pharmaceuticalsubstance_id_atc_code_id_6d0b7e4b_uniq UNIQUE ("pharmaceuticalsubstance_id", "atc_code_id")
Pymongo error: {'ok': 0.0, 'errmsg': 'namespace name generated from index name "bntq-db.bntq_common_pharmaceuticalsubstance_atc_code.$bntq_common_pharmaceuticalsubstance_atc_code_pharmaceuticalsubstance_id_atc_code_id_6d0b7e4b_uniq" is too long (127 byte max)','code': 67, 'codeName': 'CannotCreateIndex'}
Version: 1.2.20

**Comment by nesdis** [comment]
It looks like the name of the collection is too long for MongoDB  

`bntq_common_pharmaceuticalsubstance_atc_code` 

Can you consider shortening it?

**Comment by KrombopulosMichael** [comment]
It's not a real problem for me, but I would consider it a bug. That's why I reported it.

**Comment by nesdis** [comment]
It's actually a limitation in MongoDB. Which doesn't accept long index names. There could be a workaround for this but it would have an impact on Django stability. 

So for the moment I will close this. The only solution I can think of is shortening the Model names.

**Comment by Dim25** [comment]
@CucumberKing the possible solution:
`db.collection.ensureIndex({"foo": 1, "bar": 1}, {name:"myIndex1"});`
As described [here](https://stackoverflow.com/questions/28441038/while-saving-a-collection-mongodb-is-creating-index-name-which-is-too-long-and-e).

Example for python (pymongo):
```
db.collection.ensure_index(
    [
        ("foo", 1),
        ("bar", 1),

    ], 
    name="myIndex1"
)
```
