### ISSUE TITLE
using mLab with djongo

### ISSUE THREAD

**Issue by petersobhi** [nesdis/djongo#65]
I use [mLab](https://mlab.com/) as my no-sql database for my project

in `settings.py`:
```
DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'NAME': 'db_name',
        'HOST': 'ds059546.mlab.com',
        'PORT': 59546,
        'USER': 'username',
        'PASSWORD': 'password',
    }
}
```

When I try to makemigrations or run the project I get that error:
```
System check identified 1 issue (0 silenced).
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fe73e5ff840>
Traceback (most recent call last):
  File "/home/peter/.virtualenvs/dokkanz/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/peter/.virtualenvs/dokkanz/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 124, in inner_run
    self.check_migrations()
  File "/home/peter/.virtualenvs/dokkanz/lib/python3.6/site-packages/django/core/management/base.py", line 427, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/home/peter/.virtualenvs/dokkanz/lib/python3.6/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/peter/.virtualenvs/dokkanz/lib/python3.6/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/home/peter/.virtualenvs/dokkanz/lib/python3.6/site-packages/django/db/migrations/loader.py", line 206, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/home/peter/.virtualenvs/dokkanz/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 61, in applied_migrations
    if self.has_table():
  File "/home/peter/.virtualenvs/dokkanz/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 44, in has_table
    return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
  File "/home/peter/.virtualenvs/dokkanz/lib/python3.6/site-packages/django/db/backends/base/introspection.py", line 56, in table_names
    return get_names(cursor)
  File "/home/peter/.virtualenvs/dokkanz/lib/python3.6/site-packages/django/db/backends/base/introspection.py", line 51, in get_names
    return sorted(ti.name for ti in self.get_table_list(cursor)
  File "/home/peter/.virtualenvs/dokkanz/lib/python3.6/site-packages/djongo/introspection.py", line 9, in get_table_list
    return [TableInfo(c,'t') for c in cursor.db_conn.collection_names(False)]
  File "/home/peter/.virtualenvs/dokkanz/lib/python3.6/site-packages/pymongo/database.py", line 617, in collection_names
    for result in self.list_collections(session=session, **kws)]
  File "/home/peter/.virtualenvs/dokkanz/lib/python3.6/site-packages/pymongo/database.py", line 586, in list_collections
    ReadPreference.PRIMARY) as (sock_info, slave_okay):
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/peter/.virtualenvs/dokkanz/lib/python3.6/site-packages/pymongo/mongo_client.py", line 980, in _socket_for_reads
    with self._get_socket(server) as sock_info:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/peter/.virtualenvs/dokkanz/lib/python3.6/site-packages/pymongo/mongo_client.py", line 944, in _get_socket
    with server.get_socket(self.__all_credentials) as sock_info:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/peter/.virtualenvs/dokkanz/lib/python3.6/site-packages/pymongo/server.py", line 138, in get_socket
    with self.pool.get_socket(all_credentials, checkout) as sock_info:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/peter/.virtualenvs/dokkanz/lib/python3.6/site-packages/pymongo/pool.py", line 893, in get_socket
    sock_info.check_auth(all_credentials)
  File "/home/peter/.virtualenvs/dokkanz/lib/python3.6/site-packages/pymongo/pool.py", line 588, in check_auth
    auth.authenticate(credentials, self)
  File "/home/peter/.virtualenvs/dokkanz/lib/python3.6/site-packages/pymongo/auth.py", line 486, in authenticate
    auth_func(credentials, sock_info)
  File "/home/peter/.virtualenvs/dokkanz/lib/python3.6/site-packages/pymongo/auth.py", line 466, in _authenticate_default
    return _authenticate_scram_sha1(credentials, sock_info)
  File "/home/peter/.virtualenvs/dokkanz/lib/python3.6/site-packages/pymongo/auth.py", line 209, in _authenticate_scram_sha1
    res = sock_info.command(source, cmd)
  File "/home/peter/.virtualenvs/dokkanz/lib/python3.6/site-packages/pymongo/pool.py", line 496, in command
    collation=collation)
  File "/home/peter/.virtualenvs/dokkanz/lib/python3.6/site-packages/pymongo/network.py", line 125, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/home/peter/.virtualenvs/dokkanz/lib/python3.6/site-packages/pymongo/helpers.py", line 146, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: Authentication failed.
t(all_credentials, checkout) as sock_info:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/peter/.virtualenvs/dokkanz/lib/python3.6/site-packages/pymongo/pool.py", line 893, in get_socket
    sock_info.check_auth(all_credentials)
  File "/home/peter/.virtualenvs/dokkanz/lib/python3.6/site-packages/pymongo/pool.py", line 588, in check_auth
    auth.authenticate(credentials, self)
  File "/home/peter/.virtualenvs/dokkanz/lib/python3.6/site-packages/pymongo/auth.py", line 486, in authenticate
    auth_func(credentials, sock_info)
  File "/home/peter/.virtualenvs/dokkanz/lib/python3.6/site-packages/pymongo/auth.py", line 466, in _authenticate_default
    return _authenticate_scram_sha1(credentials, sock_info)
  File "/home/peter/.virtualenvs/dokkanz/lib/python3.6/site-packages/pymongo/auth.py", line 209, in _authenticate_scram_sha1
    res = sock_info.command(source, cmd)
  File "/home/peter/.virtualenvs/dokkanz/lib/python3.6/site-packages/pymongo/pool.py", line 496, in command
    collation=collation)
  File "/home/peter/.virtualenvs/dokkanz/lib/python3.6/site-packages/pymongo/network.py", line 125, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/home/peter/.virtualenvs/dokkanz/lib/python3.6/site-packages/pymongo/helpers.py", line 146, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: Authentication failed.

```
How can I solve this?

**Comment by nesdis** [comment]
have you tried specifying the authsource value?

**Comment by Mdslino** [comment]
@nesdis is corret. I use mLabs, just specify AUTH_SOURCE as the same name as your db name and AUTH_MECHANISM as SCRAM-SHA-1 and you're good to go.

**Comment by petersobhi** [comment]
It worked. Thank you very much
