### ISSUE TITLE
DROP TABLE SQL.DecodeError

### ISSUE THREAD

**Issue by M1kEk1M** [nesdis/djongo#69]
#### One line description of the issue
When trying to apply migration with removing models it fails with djongo.sql2mongo.SQLDecodeError
#### Python script

<The complete python script used to produce the issue.>

```python
# Generated by Django 2.0.2 on 2018-02-19 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0003_auto_20180215_0320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localuser',
            name='groups',
        ),
        migrations.DeleteModel(
            name='LocalGroup',
        ),
    ]

```

#### Traceback
Traceback (most recent call last):
  File "/home/ubuntu/PycharmProjects/django2mongo/venv/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 476, in parse
    return handler(self, statement)
  File "/home/ubuntu/PycharmProjects/django2mongo/venv/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 597, in _drop
    raise SQLDecodeError('statement:{}'.format(sm))
djongo.sql2mongo.SQLDecodeError: statement:DROP TABLE "test1_group" CASCADE

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/PycharmProjects/django2mongo/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/PycharmProjects/django2mongo/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/PycharmProjects/django2mongo/venv/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/PycharmProjects/django2mongo/venv/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/PycharmProjects/django2mongo/venv/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 200, in handle
    fake_initial=fake_initial,
  File "/home/ubuntu/PycharmProjects/django2mongo/venv/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/ubuntu/PycharmProjects/django2mongo/venv/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/ubuntu/PycharmProjects/django2mongo/venv/lib/python3.6/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/ubuntu/PycharmProjects/django2mongo/venv/lib/python3.6/site-packages/django/db/migrations/migration.py", line 122, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/ubuntu/PycharmProjects/django2mongo/venv/lib/python3.6/site-packages/django/db/migrations/operations/models.py", line 246, in database_forwards
    schema_editor.delete_model(model)
  File "/home/ubuntu/PycharmProjects/django2mongo/venv/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 317, in delete_model
    "table": self.quote_name(model._meta.db_table),
  File "/home/ubuntu/PycharmProjects/django2mongo/venv/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 117, in execute
    cursor.execute(sql, params)
  File "/home/ubuntu/PycharmProjects/django2mongo/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/ubuntu/PycharmProjects/django2mongo/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/ubuntu/PycharmProjects/django2mongo/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/ubuntu/PycharmProjects/django2mongo/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ubuntu/PycharmProjects/django2mongo/venv/lib/python3.6/site-packages/djongo/cursor.py", line 44, in execute
    self.result = Result(self.client_conn, self.db_conn, sql, params)
  File "/home/ubuntu/PycharmProjects/django2mongo/venv/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 415, in __init__
    self.parse()
  File "/home/ubuntu/PycharmProjects/django2mongo/venv/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 493, in parse
    raise exe from e
djongo.sql2mongo.SQLDecodeError: FAILED SQL: DROP TABLE "test1_group" CASCADEVersion: 1.2.20

**Comment by nesdis** [comment]
Thanks @M1kEk1M for the fix! I have merged it!
