### ISSUE TITLE
Issue with offset 

### ISSUE THREAD

**Issue by M1kEk1M** [nesdis/djongo#77]
#### One line description of the issue
No support for sql offset 
#### Python script

<The complete python script used to produce the issue.>

```python
LocalUser.objects.all()[1]

```

#### Traceback
Traceback (most recent call last):
  File "/home/ubuntu/PycharmProjects/django2mongo/venv/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 484, in parse
    return handler(self, statement)
  File "/home/ubuntu/PycharmProjects/django2mongo/venv/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 624, in _select
    self._query = SelectQuery(self.db, sm, self._params)
  File "/home/ubuntu/PycharmProjects/django2mongo/venv/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 107, in __init__
    super().__init__(*args)
  File "/home/ubuntu/PycharmProjects/django2mongo/venv/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 79, in __init__
    self.parse()
  File "/home/ubuntu/PycharmProjects/django2mongo/venv/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 143, in parse
    raise SQLDecodeError
djongo.sql2mongo.SQLDecodeError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/ubuntu/PycharmProjects/django2mongo/venv/lib/python3.6/site-packages/django/db/models/query.py", line 306, in __getitem__
    qs._fetch_all()
  File "/home/ubuntu/PycharmProjects/django2mongo/venv/lib/python3.6/site-packages/django/db/models/query.py", line 1179, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/ubuntu/PycharmProjects/django2mongo/venv/lib/python3.6/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/ubuntu/PycharmProjects/django2mongo/venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1064, in execute_sql
    cursor.execute(sql, params)
  File "/home/ubuntu/PycharmProjects/django2mongo/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/ubuntu/PycharmProjects/django2mongo/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/ubuntu/PycharmProjects/django2mongo/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/ubuntu/PycharmProjects/django2mongo/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ubuntu/PycharmProjects/django2mongo/venv/lib/python3.6/site-packages/djongo/cursor.py", line 44, in execute
    self.result = Result(self.client_conn, self.db_conn, sql, params)
  File "/home/ubuntu/PycharmProjects/django2mongo/venv/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 425, in __init__
    self.parse()
  File "/home/ubuntu/PycharmProjects/django2mongo/venv/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 501, in parse
    raise exe from e
djongo.sql2mongo.SQLDecodeError: FAILED SQL: SELECT "test1_localuser"."id", "test1_localuser"."password", "test1_localuser"."last_login", "test1_localuser"."is_superuser", "test1_localuser"."username", "test1_localuser"."first_name", "test1_localuser"."last_name", "test1_localuser"."email", "test1_localuser"."is_staff", "test1_localuser"."is_active", "test1_localuser"."date_joined" FROM "test1_localuser" LIMIT 1 OFFSET 1Version: 1.2.20

**Comment by nesdis** [comment]
Hello @M1kEk1M I notice that you have already solved this and created a pull request. I will merge this very soon! Thank you once again very much for your continuous support :smile:

**Comment by nesdis** [comment]
The changes have been merged. Yes, test case development is a much needed activity for djongo. Please contribute!!
