### ISSUE TITLE
Authentication Failure with DB user (non-root)

### ISSUE THREAD

**Issue by dotRollen** [nesdis/djongo#80]
#### python manage.py runserver / settings.py
MongoDB user creation steps...
```bash
> use admin
> db.createUser({user: "root", pwd: "password", roles:["root"]})
> mongod --auth --port 27017 --dbpath /var/lib/mongodb
> mongo localhost:27017 -u "root" -p "password" --authenticationDatabase "admin"
> use appdb
> db.createUser({user: "appuser", pwd: "password", roles:["dbOwner"]})
> mongo localhost:27017/appdb -u "appuser" -p "password"
```

Can connect successfully with the bash shell on appdb with userdb no problems. When I put in the appdb and userdb info into the settings.py it fails to authenticate... I used root user instead and it worked fine. Obviously this is not ideal for security and would like to know why it's not authenticating the regular user.

```python
"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 2.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

ADMINS = ((
	os.environ.get('ADMIN_EMAIL_NAME', ''), 
	os.environ.get('ADMIN_EMAIL_ADDRESS', '')
),)

SITES = {
    "api": {"domain": "localhost:8000", "scheme": "http", "name": "api"},
    "front": {"domain": "localhost:9001", "scheme": "http", "name": "front"},
}

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'kitsu.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kitsu.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'NAME': 'appdb',
        'HOST': 'db',
        'PORT': 27017,
        'USER':'appuser',
        'PASSWORD': 'password',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, os.environ.get('STATIC_ROOT', "/usr/local/app/static/"))
STATIC_URL = os.environ.get('STATIC_URL', '/static/')

MEDIA_ROOT = os.path.join(BASE_DIR, os.environ.get('MEDIA_ROOT', "/usr/local/app/media/"))
MEDIA_URL = os.environ.get('MEDIA_URL', "/media/")

```

#### Traceback
```bash
backend_1  | Waiting for MongoDB to respond...
backend_1  | Migrating data models to database
backend_1  | Traceback (most recent call last):
backend_1  |   File "manage.py", line 15, in <module>
backend_1  |     execute_from_command_line(sys.argv)
backend_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
backend_1  |     utility.execute()
backend_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
backend_1  |     self.fetch_command(subcommand).run_from_argv(self.argv)
backend_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
backend_1  |     self.execute(*args, **cmd_options)
backend_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
backend_1  |     output = self.handle(*args, **options)
backend_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/makemigrations.py", line 92, in handle
backend_1  |     loader.check_consistent_history(connection)
backend_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/loader.py", line 275, in check_consistent_history
backend_1  |     applied = recorder.applied_migrations()
backend_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 61, in applied_migrations
backend_1  |     if self.has_table():
backend_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 44, in has_table
backend_1  |     return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
backend_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/introspection.py", line 56, in table_names
backend_1  |     return get_names(cursor)
backend_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/introspection.py", line 51, in get_names
backend_1  |     return sorted(ti.name for ti in self.get_table_list(cursor)
backend_1  |   File "/usr/local/lib/python3.6/site-packages/djongo/introspection.py", line 9, in get_table_list
backend_1  |     return [TableInfo(c,'t') for c in cursor.db_conn.collection_names(False)]
backend_1  |   File "/usr/local/lib/python3.6/site-packages/pymongo/database.py", line 617, in collection_names
backend_1  |     for result in self.list_collections(session=session, **kws)]
backend_1  |   File "/usr/local/lib/python3.6/site-packages/pymongo/database.py", line 586, in list_collections
backend_1  |     ReadPreference.PRIMARY) as (sock_info, slave_okay):
backend_1  |   File "/usr/local/lib/python3.6/contextlib.py", line 81, in __enter__
backend_1  |     return next(self.gen)
backend_1  |   File "/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 983, in _socket_for_reads
backend_1  |     with self._get_socket(server) as sock_info:
backend_1  |   File "/usr/local/lib/python3.6/contextlib.py", line 81, in __enter__
backend_1  |     return next(self.gen)
backend_1  |   File "/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 947, in _get_socket
backend_1  |     with server.get_socket(self.__all_credentials) as sock_info:
backend_1  |   File "/usr/local/lib/python3.6/contextlib.py", line 81, in __enter__
backend_1  |     return next(self.gen)
backend_1  |   File "/usr/local/lib/python3.6/site-packages/pymongo/server.py", line 138, in get_socket
backend_1  |     with self.pool.get_socket(all_credentials, checkout) as sock_info:
backend_1  |   File "/usr/local/lib/python3.6/contextlib.py", line 81, in __enter__
backend_1  |     return next(self.gen)
backend_1  |   File "/usr/local/lib/python3.6/site-packages/pymongo/pool.py", line 920, in get_socket
backend_1  |     sock_info.check_auth(all_credentials)
backend_1  |   File "/usr/local/lib/python3.6/site-packages/pymongo/pool.py", line 609, in check_auth
backend_1  |     auth.authenticate(credentials, self)
backend_1  |   File "/usr/local/lib/python3.6/site-packages/pymongo/auth.py", line 486, in authenticate
backend_1  |     auth_func(credentials, sock_info)
backend_1  |   File "/usr/local/lib/python3.6/site-packages/pymongo/auth.py", line 209, in _authenticate_scram_sha1
backend_1  |     res = sock_info.command(source, cmd)
backend_1  |   File "/usr/local/lib/python3.6/site-packages/pymongo/pool.py", line 517, in command
backend_1  |     collation=collation)
backend_1  |   File "/usr/local/lib/python3.6/site-packages/pymongo/network.py", line 125, in command
backend_1  |     parse_write_concern_error=parse_write_concern_error)
backend_1  |   File "/usr/local/lib/python3.6/site-packages/pymongo/helpers.py", line 145, in _check_command_response
backend_1  |     raise OperationFailure(msg % errmsg, code, response)
backend_1  | pymongo.errors.OperationFailure: Authentication failed.
backend_1  | Traceback (most recent call last):
backend_1  |   File "manage.py", line 15, in <module>
backend_1  |     execute_from_command_line(sys.argv)
backend_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
backend_1  |     utility.execute()
backend_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
backend_1  |     self.fetch_command(subcommand).run_from_argv(self.argv)
backend_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
backend_1  |     self.execute(*args, **cmd_options)
backend_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
backend_1  |     output = self.handle(*args, **options)
backend_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 79, in handle
backend_1  |     executor = MigrationExecutor(connection, self.migration_progress_callback)
backend_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 18, in __init__
backend_1  |     self.loader = MigrationLoader(self.connection)
backend_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/loader.py", line 49, in __init__
backend_1  |     self.build_graph()
backend_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/loader.py", line 206, in build_graph
backend_1  |     self.applied_migrations = recorder.applied_migrations()
backend_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 61, in applied_migrations
backend_1  |     if self.has_table():
backend_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 44, in has_table
backend_1  |     return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
backend_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/introspection.py", line 56, in table_names
backend_1  |     return get_names(cursor)
backend_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/introspection.py", line 51, in get_names
backend_1  |     return sorted(ti.name for ti in self.get_table_list(cursor)
backend_1  |   File "/usr/local/lib/python3.6/site-packages/djongo/introspection.py", line 9, in get_table_list
backend_1  |     return [TableInfo(c,'t') for c in cursor.db_conn.collection_names(False)]
backend_1  |   File "/usr/local/lib/python3.6/site-packages/pymongo/database.py", line 617, in collection_names
backend_1  |     for result in self.list_collections(session=session, **kws)]
backend_1  |   File "/usr/local/lib/python3.6/site-packages/pymongo/database.py", line 586, in list_collections
backend_1  |     ReadPreference.PRIMARY) as (sock_info, slave_okay):
backend_1  |   File "/usr/local/lib/python3.6/contextlib.py", line 81, in __enter__
backend_1  |     return next(self.gen)
backend_1  |   File "/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 983, in _socket_for_reads
backend_1  |     with self._get_socket(server) as sock_info:
backend_1  |   File "/usr/local/lib/python3.6/contextlib.py", line 81, in __enter__
backend_1  |     return next(self.gen)
backend_1  |   File "/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 947, in _get_socket
backend_1  |     with server.get_socket(self.__all_credentials) as sock_info:
backend_1  |   File "/usr/local/lib/python3.6/contextlib.py", line 81, in __enter__
backend_1  |     return next(self.gen)
backend_1  |   File "/usr/local/lib/python3.6/site-packages/pymongo/server.py", line 138, in get_socket
backend_1  |     with self.pool.get_socket(all_credentials, checkout) as sock_info:
backend_1  |   File "/usr/local/lib/python3.6/contextlib.py", line 81, in __enter__
backend_1  |     return next(self.gen)
backend_1  |   File "/usr/local/lib/python3.6/site-packages/pymongo/pool.py", line 920, in get_socket
backend_1  |     sock_info.check_auth(all_credentials)
backend_1  |   File "/usr/local/lib/python3.6/site-packages/pymongo/pool.py", line 609, in check_auth
backend_1  |     auth.authenticate(credentials, self)
backend_1  |   File "/usr/local/lib/python3.6/site-packages/pymongo/auth.py", line 486, in authenticate
backend_1  |     auth_func(credentials, sock_info)
backend_1  |   File "/usr/local/lib/python3.6/site-packages/pymongo/auth.py", line 209, in _authenticate_scram_sha1
backend_1  |     res = sock_info.command(source, cmd)
backend_1  |   File "/usr/local/lib/python3.6/site-packages/pymongo/pool.py", line 517, in command
backend_1  |     collation=collation)
backend_1  |   File "/usr/local/lib/python3.6/site-packages/pymongo/network.py", line 125, in command
backend_1  |     parse_write_concern_error=parse_write_concern_error)
backend_1  |   File "/usr/local/lib/python3.6/site-packages/pymongo/helpers.py", line 145, in _check_command_response
backend_1  |     raise OperationFailure(msg % errmsg, code, response)
backend_1  | pymongo.errors.OperationFailure: Authentication failed.
```

**Comment by nesdis** [comment]
I think you are missing the auth source parameter. This is required for a successful authentication
