### ISSUE TITLE
Cannot Connect

### ISSUE THREAD

**Issue by dabo02** [nesdis/djongo#9]
#### Whenever I try to run manage.py commmands I get connection refused error

<The complete python script used to produce the issue.>

#### Traceback
<Unhandled exception in thread started by <_pydev_bundle.pydev_monkey._NewThreadStartupWithTrace object at 0x7f5833353198>
Traceback (most recent call last):
  File "/root/.IntelliJIdea2017.1/config/plugins/python/helpers/pydev/_pydev_bundle/pydev_monkey.py", line 589, in __call__
    return self.original_func(*self.args, **self.kwargs)
  File "/home/dabo02/Desktop/Projects/Side_Projects/MotaMD/motamdmarketing/lib/python3.5/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/home/dabo02/Desktop/Projects/Side_Projects/MotaMD/motamdmarketing/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 128, in inner_run
    self.check_migrations()
  File "/home/dabo02/Desktop/Projects/Side_Projects/MotaMD/motamdmarketing/lib/python3.5/site-packages/django/core/management/base.py", line 422, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/home/dabo02/Desktop/Projects/Side_Projects/MotaMD/motamdmarketing/lib/python3.5/site-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/dabo02/Desktop/Projects/Side_Projects/MotaMD/motamdmarketing/lib/python3.5/site-packages/django/db/migrations/loader.py", line 52, in __init__
    self.build_graph()
  File "/home/dabo02/Desktop/Projects/Side_Projects/MotaMD/motamdmarketing/lib/python3.5/site-packages/django/db/migrations/loader.py", line 209, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/home/dabo02/Desktop/Projects/Side_Projects/MotaMD/motamdmarketing/lib/python3.5/site-packages/django/db/migrations/recorder.py", line 65, in applied_migrations
    self.ensure_schema()
  File "/home/dabo02/Desktop/Projects/Side_Projects/MotaMD/motamdmarketing/lib/python3.5/site-packages/django/db/migrations/recorder.py", line 52, in ensure_schema
    if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):
  File "/home/dabo02/Desktop/Projects/Side_Projects/MotaMD/motamdmarketing/lib/python3.5/site-packages/djongo/introspection.py", line 6, in table_names
    return sorted(cursor.m_cli_connection.collection_names(False))
  File "/home/dabo02/Desktop/Projects/Side_Projects/MotaMD/motamdmarketing/lib/python3.5/site-packages/pymongo/database.py", line 552, in collection_names
    ReadPreference.PRIMARY) as (sock_info, slave_okay):
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/home/dabo02/Desktop/Projects/Side_Projects/MotaMD/motamdmarketing/lib/python3.5/site-packages/pymongo/mongo_client.py", line 904, in _socket_for_reads
    with self._get_socket(read_preference) as sock_info:
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/home/dabo02/Desktop/Projects/Side_Projects/MotaMD/motamdmarketing/lib/python3.5/site-packages/pymongo/mongo_client.py", line 868, in _get_socket
    server = self._get_topology().select_server(selector)
  File "/home/dabo02/Desktop/Projects/Side_Projects/MotaMD/motamdmarketing/lib/python3.5/site-packages/pymongo/topology.py", line 214, in select_server
    address))
  File "/home/dabo02/Desktop/Projects/Side_Projects/MotaMD/motamdmarketing/lib/python3.5/site-packages/pymongo/topology.py", line 189, in select_servers
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused>

**Comment by dabo02** [comment]
and, how do you connect do a cloud hosted database? I can't seem to find it on the documentation

**Comment by nesdis** [comment]
Hello dabo02

looking at the traceback it seems there is no MongoDb instance running on port 27017, because of which you are failing. 

currently this connector assumes your mongoDB instance is running on localhost:27017. Support for external IP:port needs to be developed. (Not very complex, but lack of time and resources causing delays)

For the moment you can create a SSH tunnel with local port 27017 forwarded to your remote IP cloud port. SSH tunneling is the preferred way to connected to remote DB instances as it ensures security and encryption instead of raw IP access, which can be easily hacked by anyone.

**Comment by nesdis** [comment]
I hope your query has been answered!
