### ISSUE TITLE
Problem with migration of the model with an embedded field

### ISSUE THREAD

**Issue by Sashkow** [nesdis/djongo#92]
Migrating a model with `EmbeddedModelField` made `AttributeError: module 'django.forms.widgets' has no attribute 'BlogForm'` error.

#### Python script
I followed your tutorial https://nesdis.github.io/djongo/integrating-django-with-mongodb/

```python
    # models.py
    from djongo import models

    class Blog(models.Model):
        name = models.CharField(max_length=100)
        tagline = models.TextField()

        class Meta:
            abstract = True


    class Entry(models.Model):
        blog = models.EmbeddedModelField(
            model_container=Blog,
        )

        headline = models.CharField(max_length=255)

    # admin.py
    from django.contrib import admin   
    from .models import Entry
    admin.site.register(Entry)
```
and when I ran
```
    python manage.py makemigrations
    python manage.py runserver
```
I came across an error:
#### Traceback
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/sashkoah/Python/whizzy-restful-server/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/home/sashkoah/Python/whizzy-restful-server/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/sashkoah/Python/whizzy-restful-server/env/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/sashkoah/Python/whizzy-restful-server/env/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/home/sashkoah/Python/whizzy-restful-server/env/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 79, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/home/sashkoah/Python/whizzy-restful-server/env/lib/python3.6/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/sashkoah/Python/whizzy-restful-server/env/lib/python3.6/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/home/sashkoah/Python/whizzy-restful-server/env/lib/python3.6/site-packages/django/db/migrations/loader.py", line 200, in build_graph
    self.load_disk()
  File "/home/sashkoah/Python/whizzy-restful-server/env/lib/python3.6/site-packages/django/db/migrations/loader.py", line 109, in load_disk
    migration_module = import_module("%s.%s" % (module_name, migration_name))
  File "/home/sashkoah/Python/whizzy-restful-server/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/sashkoah/Python/whizzy-restful-server/whizzy/restapi/migrations/0001_initial.py", line 9, in <module>
    class Migration(migrations.Migration):
  File "/home/sashkoah/Python/whizzy-restful-server/whizzy/restapi/migrations/0001_initial.py", line 21, in Migration
    ('blog', djongo.models.fields.EmbeddedModelField(model_container=restapi.models.Blog, model_form_class=django.forms.widgets.BlogForm, null=True)),
AttributeError: module 'django.forms.widgets' has no attribute 'BlogForm'

**Comment by deeptechs** [comment]
I came across the same problem. You mentioned in docs

> To display the embedded models in Django Admin, a Form for the embedded fields is required. Since the embedded field is an abstract model, the form for it can be easily created by using a ModelForm. The BlogForm defines Blog as the model with name and tagline as the form fields.
> 
> If you do not specify a ModelForm for your embedded models, and pass it using the model_form_class argument, Djongo will automatically generate a ModelForm for you.

But if we don't specify (like the above one of @Sashkow ) it is rasing AttributeError: module 'django.forms.widgets' has no attribute 'XXXForm'

**Comment by nesdis** [comment]
Is this happening only with Django Rest Framework? Also which version of Djongo do u use? Can you reproduce once with bare minimum code?

**Comment by nesdis** [comment]
Also there is a line in the sample code:

from djongo.models import forms

Thanks for pointing that out!!

**Comment by deeptechs** [comment]
I solved the problem specifying a Form and pass it using the model_form_class argument. Here is the simple one for Blog class @Sashkow 

```
class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog

        fields = [
            'name',
            'tagline',
        ]
```

@nesdis I am not using  Django Rest Framework. Problem is occurring with your sample codes that explain and use the embedded models.
Here is my package versions from Requirement.txt:
```
dataclasses==0.5
Django==2.0.4
django-crispy-forms==1.7.2
djongo==1.2.23
Pillow==5.1.0
pymongo==3.6.1
pytz==2018.3
sqlparse==0.2.4
```

Thanks for your commitments.

**Comment by nesdis** [comment]
This has been fixed now. There is no need to specify class argument anymore
